### ISSUE TITLE
Upper and lower part of the display resizable

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#100]
It would be good to be able to resize the main waterfall so more space is available for the zoomed waterfall and audio spectrum in the top of the screen.

**Comment by cjcliffe** [comment]
I've added draggable sizers to soapysdr-support; it seemed more necessary now that you can drag the visual scale to be able to adjust the area to work with.  Double click the sizers to reset to defaults.

**Comment by Toontje** [comment]
Working perfectly!
