### ISSUE TITLE
Program startup with default preferences file

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#102]
I use different preferences files for when i am using CubicSDR as SDR program or when i'm using it as panadapter. Would it be possible to start the program with a default preferences file that can be set up for most common use?

**Comment by cjcliffe** [comment]
Would a simple command line parameter that takes a name for the configuration be enough?  

It would be simple to just redirect the configuration file to something like cubicsdr-[configname].xml where [configname] is supplied via command line parameters.

**Comment by Toontje** [comment]
That would be great. And if no command line parameters are given it loads a
default XML file.

**Comment by cjcliffe** [comment]
Latest master will now accept -c [name] or --config [name] to set the config-[name].xml as the active config; default config will be copied to the new one if no file exists.

Thanks!
