### ISSUE TITLE
Save window position and size in preferences file

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#103]
Can you save the latest window position and size in the preferences file or in the plist so we don't have to resize and reposition the window every time i start CubicSDR? A bit in line with issue 100, 101 and 102. Maybe you can combine the three issues.

**Comment by cjcliffe** [comment]
Window position, size and current theme will now be saved with configuration

**Comment by Toontje** [comment]
Nice! Thanks!!

On Fri, Jul 17, 2015 at 7:12 AM, Charles J. Cliffe <notifications@github.com
