### ISSUE TITLE
Axis label, averaging control, audio spectrum view

### ISSUE THREAD

**Issue by redbobcat** [cjcliffe/CubicSDR#104]
Just now tried about 3h direct sampling recv on HF. I think, it is needs a lot:
Waterfall speed control - hard to understand modulation on such slow waterfall, mostly CW looks like constant carrier now.
Y axis of panadapter needs levels labelling (like in gqrx and others). Auto range is great, but manual will be good to (amp testing, noise levels investigation). And averaging control.
Spectrum/scope switch will be great, sometimes spectrum is very useful.

And short manual with hotkeys and hints in project wiki.

- [x] Label Y axis value
- [x] Averaging control
- [x] Spectrum audio view

**Comment by cjcliffe** [comment]
In master branch the spectrum can now be controlled via a speed control slider on the right.

**Comment by cjcliffe** [comment]
- Main I/Q spectrum and audio spectrum now feature peak and floor decibels display
- Waterfall speed control can now be set between 1 and 1024 lines per second
- Waterfall now continues while in background or minimized
- A new spectrum visual is available by dragging left on the scope area, more visuals may be added here :)
