### ISSUE TITLE
Volume doesn't go down to 0

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#118]
You cannot silence CubicSDR.
Video here: https://www.dropbox.com/s/gr4y049tmmifz89/VID_20150725_144144.3gp?dl=0

**Comment by cjcliffe** [comment]
Thanks; it's actually an audio gain slider between 0.0 and 2.0 and is more relevant to balancing the mix between several sources or adjusting the gain of one than attempting to mute -- I've added issue #117 which should make it unnecessary to use the slider to mute the audio and will let you retain your gain levels.
