### ISSUE TITLE
osmocom sdr?

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#125]
I see that osmocom sdr support is not checked off in your todo list yet. I am planning to move from rtl-sdr to SDRplay. Does the SDRplay work with CubicSDR? Or do i need to wait for osmocom support and if so, when are you planning to build that into CubicSDR?

Thanks,

Ton.

**Comment by dc1rdb** [comment]
Already covered by https://github.com/cjcliffe/CubicSDR/issues/64
Regards,
Robert

**Comment by Toontje** [comment]
Correct. Sorry for not finding it. Will mark this one as closed/obsolete/double.
