### ISSUE TITLE
Support For tuning Gain 

### ISSUE THREAD

**Issue by mohammadninja** [cjcliffe/CubicSDR#146]
hi , thanks for this very nice app

when you add Gain tunning option for cubicsdr to .. ?

**Comment by cjcliffe** [comment]
Hello, issue #92 will address this -- it was supposed to be for 0.1.4 but was delayed.

Thanks!

**Comment by Toontje** [comment]
I was in a low noise environment the last couple of days and then the automatic gain really annoys. Yes, i  support the request for a switchable manual gain as well.

**Comment by mohammadninja** [comment]
Thank you very very much
