### ISSUE TITLE
Version wx

### ISSUE THREAD

**Issue by sabas1080** [cjcliffe/CubicSDR#153]
Hi I installed for .deb in Debian 8

And i have this error:

Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1002,wx containers,compatible with 2.8).
Violación de segmento

Thanks

**Comment by cjcliffe** [comment]
Newer AppKit bundles include static wx compiles as will future .debs; this should be resolved now.  Cheers!
