### ISSUE TITLE
Re-scan button on Device Selection screen

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#160]
I didn't have my device connected so the device doesn't show up in the Device Selection screen.
Now i need to close CubicSDR, connect my device, start CubicSDR and then the device is selected.
A Re-scan button would eliminate the need to stop and re-launch CubicSDR.

**Comment by cjcliffe** [comment]
I was close to having one already; it will stop any active stream since it has to free Soapy to re-scan and would probably crash some drivers otherwise; should be able to add this soon though.

**Comment by Toontje** [comment]
No worries. At the moment a nice to have. Get the core right is more important and you're doing a great job at that.

**Comment by Toontje** [comment]
I think this one can be closed, no?

**Comment by cjcliffe** [comment]
Nope, still need to add a refresh button -- only remotes can technically refresh at the moment if you enter the IP twice :)

**Comment by Toontje** [comment]
Does the SDR Devices menu option not do a new detection of connected
devices?

On Sat, Dec 12, 2015 at 9:58 PM, Charles J. Cliffe <notifications@github.com

**Comment by cjcliffe** [comment]
@Toontje nope not yet :)

**Comment by cjcliffe** [comment]
There's now a 'Refresh' button on the Device Dialog in master, it'll stop active streams to prevent crashing but appears to be working well here plugging and unplugging devices or adding SoapyRemotes to the network.
