### ISSUE TITLE
Bookmarks and History log

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#161]
Bookmarks / History / Active session log.
- [x] Create a dialog for bookmarks and history
  - [x] Use tree view
  - [x] Allow sorting by group
  - [x] Allow managing groups
- [x] Split active (live session) and bookmarks sections in tree
  - [x] Activate / bookmark in respective section to transfer from active to bookmark
- [x] Quick search all
- [x] Add "Recent" section for re-creating historical modems for that session
- [x] Allow bookmarking "Recent" and "Active"
- [x] Method to clear recent list
- [x] Method to remove anything from list

**Comment by cjcliffe** [comment]
Feel free to curate the checklist for this issue; I think your original suggestion is in there somewhere :)

**Comment by AlmightyOatmeal** [comment]
I would absolutely love the ability to save bookmarks and be able to group them.

**Comment by cjcliffe** [comment]
@AlmightyOatmeal already partly working in the bookmarks branch (minus actually saving); hopefully will have some early tests out in the next few weeks.

**Comment by cjcliffe** [comment]
@Toontje OSX test build is up at https://github.com/cjcliffe/CubicSDR/releases/tag/0.2.1-alpha1 
Other platform builds will be ready soon

**Comment by Toontje** [comment]
Perfect implementation of this function. For me you can close this issue.

**Comment by cjcliffe** [comment]
@Toontje thanks 👍 closing this up; we can make new ones for specific issues.
