### ISSUE TITLE
Smooth tuning now in 10KHz steps

### ISSUE THREAD

**Issue by BillyBag2** [cjcliffe/CubicSDR#163]
This SW is great, sorry if this error is related to insufficient user IQ. The tuning by dragging was smooth, but now its in 10KHz steps. Is this intentional? How do I unset this mode? I installed again on a different Mac and it was smooth again. Reinstalling on original Mac did not fix this.
Maybe i can delete some preferences but i could not find these.

I am using a Mac book pro and mac book air on latest OSX, 10.11 El Captain.

**Comment by cjcliffe** [comment]
If you right-click on the frequency numbers you can set the frequency snap; you'll probably see a red box around the 10Khz digit just right click it or right-click on the 1Hz digit to disable.

Most of this information shows up on the status bar at the bottom when you hover over things but I really do need to create a manual soon :)
