### ISSUE TITLE
Feature request for auto lock

### ISSUE THREAD

**Issue by vsboost** [cjcliffe/CubicSDR#175]
Hi Charles,

Not sure if this was on the to do list but it would be real handy if you could possibly implement an auto lock feature button so when you click near a signal it automatically moves to the centre of the carrier, Sdrsharper has a similar feature.

**Comment by cjcliffe** [comment]
Yup! might not be immediately obvious; but the "Allow one-shot usage of deep-scanning when manually placing demodulators" in #171 will cover exactly this; and should attempt to detect modulation type as well.

**Comment by vsboost** [comment]
Excellent; ill close this one.
