### ISSUE TITLE
Error when starting CubicSDR

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#186]
No RTL-SDR adapter connected.

```
SoapySDR init..
	API Version: v0.4.0-g4331e634
	ABI Version: v0.4-2
	Install root: /usr/local
	Loading modules... 
[ERROR] SoapySDR::loadModule(/usr/local/lib/SoapySDR/modules/libremoteSupport.so)
  duplicate entry for null ()
	Available factories...null, remote, rtlsdr, sdrplay
```

**Comment by cjcliffe** [comment]
Hmm, I think @guruofquality had something in about this; null module gets included in SoapyRemote as well or something -- it's harmless really since it's not used that's just saying it refused to load it twice..

**Comment by guruofquality** [comment]
Explanation and issue for reference: https://github.com/pothosware/SoapySDR/issues/53

**Comment by cjcliffe** [comment]
@guruofquality thanks, that's the one -- going to close this one so we're not duplicating.
