### ISSUE TITLE
stupid user question

### ISSUE THREAD

**Issue by k9wkj** [cjcliffe/CubicSDR#187]
i must be a dullard
i have no idea how to control the LNA gain in the dongle
i know there is some agc action going on.
but is there? or could there be a control for auto/manual , gain , attack speed
most other programs have a gain control, GQRX is the only one that gives any control over it

**Comment by cjcliffe** [comment]
Is this RTLSDR? and which tuner does the dongle have?

**Comment by k9wkj** [comment]
Ohh yes RTL-SDR its a T2 tuner
Well tuners, I have 5 of them

**Comment by cjcliffe** [comment]
@k9wkj are you just looking to enable the manual gain? If you have the latest build you can just un-check "Automatic Gain" under the settings menu and the manual gain controls will appear.

**Comment by k9wkj** [comment]
ohh my!!!
i havent built latest yet
and i guess i didnt read the change logs!

thanks!

On Wed, Nov 11, 2015 at 8:54 PM, Charles J. Cliffe <notifications@github.com

**Comment by cjcliffe** [comment]
Aye, been quite a few things pushed to master in the last few days :)

https://github.com/cjcliffe/CubicSDR/releases/tag/0.1.16-soapysdr also has a bundled binary version for OSX and Windows.  

Cheers!
