### ISSUE TITLE
Sound card based SDRs

### ISSUE THREAD

**Issue by pwarren** [cjcliffe/CubicSDR#189]
Hi all, 

Would it be possible to use soundcard based SDRs, such as the Peaberry SDR: 
http://ae9rb.com/index.php?main_page=product_info&products_id=8, 
or Softrock: 
http://fivedash.com/index.php?main_page=product_info&products_id=7 
style radios with CubicSDR?

I'm guessing another module for SoapySDR will be needed?

**Comment by cjcliffe** [comment]
@pwarren I've already started the idea over at https://github.com/pothosware/SoapyAudio for just this purpose; please feel free to add these links and any relevant issues there :+1:

**Comment by cjcliffe** [comment]
@pwarren thanks I see you've added stuff over at the SoapyAudio repository.  I'll close this issue for now and comment there when the time comes.
