### ISSUE TITLE
Which to build?

### ISSUE THREAD

**Issue by vsboost** [cjcliffe/CubicSDR#200]
Dumb question forgive me im not an expert at github.

I notice you have a separate branch for digital_experiments, how does that work exactly? do i need to build that separately from the master.

Sorry

**Comment by cjcliffe** [comment]
Ahoy, it's pretty straightforward:

```
$ git fetch
.. should pull in some branches ..
$ git checkout digital_experiments
```

You can get back to master with:
```
$ git checkout master
```

Cheers!

**Comment by vsboost** [comment]
Thank Charles,

Was worried that by building the master i wasn't getting the stuff you have done in the digital_experiments branch.

**Comment by cjcliffe** [comment]
No problem; let me know if you spot any issues; there's a bit of cleanup to do and I'm working on adding something simple to display the digital data output.

**Comment by vsboost** [comment]
Will do.
