### ISSUE TITLE
OOK

### ISSUE THREAD

**Issue by vsboost** [cjcliffe/CubicSDR#204]
Hi Charles,

Not sure how complete it is but not seeing any data in the modem window using OOK, i get OOK lock using a simple rf remote and a nice round circle on the constellation plot  just no 1010010110

Cheers

**Comment by cjcliffe** [comment]
Aye, I still need to hook up the other modes to the console -- Just FSK actually outputs at the moment but I should have some more in this evening

**Comment by vsboost** [comment]
Ahh that would explain it :-)

Ill test some FSK today.
As always Great Work
