### ISSUE TITLE
fskdem does not exist

### ISSUE THREAD

**Issue by Dantali0n** [cjcliffe/CubicSDR#205]
I pulled the digital_experiments this morning an while gmskdem is found within libliquid.h, for some reason al the fskdem classes and methods don’t exist.

I am using ubuntu 14.04

**Comment by cjcliffe** [comment]
You'll need to build it from github source; it was merged more recently and isn't even in the docs yet.

**Comment by cjcliffe** [comment]
I've added a cmake build option for 'ENABLE_LIQUID_EXPERIMENTAL' which I'll keep in place until liquid-dsp bumps it's version flag and I can detect automatically and just notify the user there's newer.
