### ISSUE TITLE
Narrow-band FM mode

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#215]
From #179 
- [x] Copy FM module to a narrow-band 'NBFM' module with suitable defaults
- [ ] Add additional adjustments and filtering suitable for NBFM via new modem properties

**Comment by vielmetti** [comment]
I'm running 0.2.0-rc2 and the "NBFM" setting seems to work just fine for signals on 2 meter amateur radio and for the weather band.

**Comment by cjcliffe** [comment]
@vielmetti thanks for the report; additional filtering will be handled in issue #214
