### ISSUE TITLE
Excessive logging 

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#217]
I think CubicSDR and mir_sdr now start to log excessively. Please make an option to switch off console logging.
See https://www.dropbox.com/s/s7nxzugd9vczogr/log.mov?dl=0

**Comment by Toontje** [comment]
Can we at least get the gain updates muted?

mir_sdr_ReadPacket: Gain update confirmed: Gr=34dB GrToggle=1 gset=0xc9
mir_sdr_ResetUpdateFlags: resetGainUpdate=1 resetRfUpdate=0 resetFsUpdate=0
mir_sdr_SetGr: GR->33[9,0,0,24] gRset->0xC9 DCCALmode=4 DCCALspd=1 GrToggle->1
mir_sdr_SetGrParams: gRmin->0 lnaGrThresh->24

**Comment by SDRplay** [comment]
@Toontje they are currently hardcoded - debug will be programmable in future releases.
