### ISSUE TITLE
OS X does not show version under menu

### ISSUE THREAD

**Issue by phillips321** [cjcliffe/CubicSDR#220]
Can you create an about menu under the CubicSDR top menu.
This will allow us to quickly see what version we are running (I know the title displays it but lots of us have mods to hide this)
It would be useful to also say here where we can get the latest version and the license it's released under.
<img width="246" alt="screen shot 2015-12-10 at 10 24 46" src="https://cloud.githubusercontent.com/assets/2072147/11712997/866174fe-9f28-11e5-86ce-e4d2ac103ff1.png">

**Comment by cjcliffe** [comment]
Latest commit now shows an 'About CubicSDR' menu item with version info popup (copy of title info).  It's mostly a placeholder until I have a more generic about dialog for all platforms. 

Cheers!
