### ISSUE TITLE
Memory usage spike after frequency change

### ISSUE THREAD

**Issue by JoshRovero** [cjcliffe/CubicSDR#221]
Linux FC21 x86-64, with SDRPlay.

Monitor 89.9 MHz FM for 1 hour, slight growth of CubicSDR resident segment size from 107 to 108 MB.  Change frequency to 100.9 FM, memory usage starts growing at 2 MB per second,
surpassing 600 MB in just a few minutes.

**Comment by cjcliffe** [comment]
@JoshRovero make sure you're up to date with master; there was a major memory leak that fits this exact scenario fixed a few days ago.  Let me know if that does the trick.

**Comment by JoshRovero** [comment]
Will do, I probably built a few days ago but didn't bring the radio in
until today.
