### ISSUE TITLE
Sessions

### ISSUE THREAD

**Issue by jdeitch** [cjcliffe/CubicSDR#222]
When loading a Saved Session the bandwidth is not set and the demodulator does not go active.  Is there a hotkey to switch between demodulators?

**Comment by cjcliffe** [comment]
@jdeitch I'll take a look at improving the scope of save/load properties in the session.  There's a plan to add keyboard shortcuts and some light arrows for navigating them in the UI.  You can track the progress here: #91

**Comment by cjcliffe** [comment]
@jdeitch latest commit to master will now load/save bandwidth and activate single-modem save files properly.

**Comment by jdeitch** [comment]
@cjcliffe Works like a charm.  Thank you!

**Comment by jdeitch** [comment]
@cjcliffe Correction to above.  The demodulator does not change to the one specified in the session file.

**Comment by cjcliffe** [comment]
@jdeitch right, I forgot to handle the multiple demodulator scenario; will patch that up

**Comment by cjcliffe** [comment]
Ok, properly fixed now -- CubicSDR will actually save the active demodulator flag to the session file and it will be active when loaded :)

**Comment by jdeitch** [comment]
@cjcliffe Working wonderfully!  Thank you!
