### ISSUE TITLE
Possibility to label devices

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#223]
![screen shot 2015-12-12 at 10 19 58](https://cloud.githubusercontent.com/assets/4884243/11761230/0f9806ce-a0ba-11e5-84ee-2ead0d13708f.png)
I would like to label the detected devices like:
Panadapter
RTL with standard antenna
SDRPlay connected to radio

**Comment by cjcliffe** [comment]
This should be pretty simple, I think I can enable editing names in the tree via simple right-click menu without much trouble

**Comment by cjcliffe** [comment]
@Toontje latest commit to master you can now edit device names :)

**Comment by Toontje** [comment]
Great! I will try it out when i get back home on friday. Fantastic work!

On Tue, Jan 19, 2016 at 1:48 AM, Charles J. Cliffe <notifications@github.com

**Comment by cjcliffe** [comment]
@Toontje

**Comment by cjcliffe** [comment]
@Toontje Switching devices while editing name or offset will now save changes to appropriate device -- good catch thanks :)
