### ISSUE TITLE
Auto-load per-device settings file

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#224]
I have three devices connected. Two RTL and one SDRPlay.
One RTL is connected to it's own antenna so center frequency is variable and I/Q needs not to be swapped, sample rate would be max (3.2M).
Second RTL is a panadapter connected to the IF of the TS-590. So center frequency needs to be fixed, in my case at 73.095MHz and I/Q needs to be swapped and sample rate needs to be between 500kHz and 1MHz.
SDRPlay is connected to RF circuit of the TS-590 so variable center frequency, I/Q not swapped, sample rate not set.
I need to set all the settings every time i switch SDR device. 

I would like for CubicSDR to auto-load default settings files per device so whenever i switch device all the proper parameters for this device are set.

**Comment by cjcliffe** [comment]
I think the SDR-IF settings now cover most of this; the additional settings are covered by the config name parameter; which will become less relevant when I add loading and saving of configurations in #249
