### ISSUE TITLE
Ubuntu 15.10 display refresh issue.

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#231]
Bug uncovered in Ubuntu 15.10 which is causing portions of the display to pause while hovered; guessing it's related to some focus/refresh issues.

**Comment by cjcliffe** [comment]
Unable to reproduce with Nvidia driver in Ubuntu 15.10; I think I'll need to try an intel based system and possibly the window manager from the original report.

**Comment by vsboost** [comment]
Hi Charles, I have Ubuntu 15.10 installed on my surface pro, is there anything you would like me to test?

**Comment by cjcliffe** [comment]
@vsboost perhaps but I'm not quite sure what I'm testing for here yet; does it have integrated intel graphics and if so what chipset?

**Comment by vsboost** [comment]
Intel HD Graphics 4400.

**Comment by vsboost** [comment]
Every so often the display freezes for a split second its random, CPU usage is 94-107% this is using an sdrplay with 2,048 sample rate, switching the sample rate to 1,536 and the waterfall looks slightly jerky and CPU is around 50%, at 8mhz sample rate CPU is around 104%

**Comment by cjcliffe** [comment]
Can't reproduce this specific error and original reporter has stated the GPU driver has additional problems which may make this unrelated.
