### ISSUE TITLE
NFM (Narrowband Frequency Modulation) Support

### ISSUE THREAD

**Issue by laveur** [cjcliffe/CubicSDR#233]
Would it be possible to add support for NFM? It seems to be a pretty common modulation method used in various fields.

**Comment by dc1rdb** [comment]
I found that reducing the bandwidth to around 15 kHz in FM mode is working fine to demodulate NFM.

**Comment by cjcliffe** [comment]
Yup, for now just adjusting the bandwidth technically sets the FM 'mode'; but there are some filters, de-emphasis and such that are needed to make a proper 'NFM' mode.

I'll close this and direct it over to duplicate issue #215 for further discussion though.
