### ISSUE TITLE
SDRPlay API 1.8 available

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#234]
See http://www.sdrplay.com/blog.html

Is it pretty much risk-free to install the latest API and build CubicSDR and all the SoapyStuff from scratch again to benefit from the latest enhancements in the API?

**Comment by cjcliffe** [comment]
I think it's just the Windows API updated so far correct?   I'll have to give it a go and see if there's any problems but I think they have an update for SoapySDRPlay in the works as well.

**Comment by frspin** [comment]
Now new 1.8.1 API is available.
Can we download it and recompile CubicSDR?

Regards
Franco Spinelli
IW2DHW

**Comment by cjcliffe** [comment]
@frspin that's good news; I'd overlooked that it's on all platforms now -- I'll definitely make this a priority now that it's available.

**Comment by cjcliffe** [comment]
latest APIs are building and running no problem, closing this up for now
