### ISSUE TITLE
SSB demodulator bandwidth set wrong?

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#238]
When i set the demodulator bandwidth using the spacebar and the modulation is set to SSB the demodulator bandwidth is set to half of what i enter in the spacebar input box.
AM, FM and DSB is working correctly.

**Comment by cjcliffe** [comment]
Hmm, yep this is an oversight thanks -- internally it uses twice the bandwidth and just displays half; I'll need to make that a consideration for the frequency entry dialog as well.

**Comment by cjcliffe** [comment]
USB/LSB manual input now fixed in master.
