### ISSUE TITLE
How about a quick listing of OS versions required?

### ISSUE THREAD

**Issue by fyngyrz** [cjcliffe/CubicSDR#251]
It could save some (wasted) time and effort for some people if you'd put just a quick list of the OS levels required to run this on the github page. Thanks.

**Comment by cjcliffe** [comment]
Thanks, I've added this to the main Readme.md for the repository and cleaned up some of the Roadmap stuff into the wiki.  Not all working Linux distributions are known but I have a work-in-progress desktop system here with several distributions installed (and more to come) so I can fix where needed and confirm working for each.
