### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by frspin** [cjcliffe/CubicSDR#272]
Improvements to CubicSDR for using in HAM bands

- [x] a NBFM button with a preset of 12500 Hz as bandwidth
- [x] save of Automatic/Manual gain control for each device (required for SDRPlay on HF)

Additional:
- [x] add "Stop/Start" button to file menu

Regards

Franco Spinelli
IW2DHW

**Comment by cjcliffe** [comment]
Thanks @frspin, sounds good -- added to the list for enhancements.

**Comment by jdeitch** [comment]
Can I add a request to this list?  How about a STOP button?  Sometimes you may want to halt the player but not exit.  Skype, etc. come to mind.

Jim

**Comment by cjcliffe** [comment]
@jdeitch the "Refresh" button on the SDR Devices dialog is technically also a "Stop" button.   I can see that adding a Start/Stop to the menu might be a good idea as well -- it's simple enough I'll try and see.

**Comment by cjcliffe** [comment]
NBFM, Start/Stop, saving AGC state / gains per-device and NBFM are implemented and now merged to master.

Cheers!
