### ISSUE TITLE
ALT modifier conflicts

### ISSUE THREAD

**Issue by viraptor** [cjcliffe/CubicSDR#275]
I've got an issue with the action modifiers. ALT conflicts with system actions and is not usable in cubicsdr for me. Alt+click starts moving the window in kde/plasma. (and I think it's a popular linux thing in general) Other modifiers may be conflicting with other environments.

It would be useful to allow setting custom modifier, or adding some clickable state switch.

(this affects setting extra frequencies)

**Comment by cjcliffe** [comment]
@viraptor I had this issue as well but I think it's just a matter of documentation, if you use ALT+Meta (I think?) it should override the default window movement behaviour and function as expected.
