### ISSUE TITLE
Add General Swap I/Q setting for all devices

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#280]
Currently Swap I/Q was migrated to SoapyRTLSDR but there is precedence with the new Rig Control and SDR-IF options for possibly adding back the Swap I/Q feature.  I'm thinking it might be Rig specific and possibly live on that menu..

**Comment by sean808080** [comment]
Yeah...it took me a while to figure out that's what was getting in the way of good audio on my 857.  Thanks for the change you made last week.  Great progress....looking forward to seeing more more more!

**Comment by cjcliffe** [comment]
Thanks @sean808080; latest commit to master now includes a general I/Q swap in the settings menu for all devices -- let me know if that works for you.
