### ISSUE TITLE
SoapySDR remote does not start on Mac OS X

### ISSUE THREAD

**Issue by andresv** [cjcliffe/CubicSDR#283]
CubicSDR.0.1.25-alpha.

![screenshot 2016-02-13 18 29 46](https://cloud.githubusercontent.com/assets/809232/13028722/295c91f4-d280-11e5-988c-f7b8b4641f06.jpg)

Nothing happens when I hit `Start` button. I can see that no connection is made to server.
Server indeed works because it can be opened with `osmocom_fft `:
```
osmocom_fft -a "soapy=0,driver=remote,remote:driver=rtl,remote=10.100.101.2" -s 1024000 -g 20 -v -F
```

**Comment by cjcliffe** [comment]
Possible I broke this in a recent update to the Add Remote option; will take another look

**Comment by cjcliffe** [comment]
Hmm, appears to be working here on RPi2 but I've already got it showing in the local network section; adding it to remote creates a duplicate that appears to work too -- will try moving it outside my network and see if that changes anything.

**Comment by andresv** [comment]
I was using openvpn to connect server and my local machine together, but that should not be the problem and indeed actually CubicSDR is able to connect to server, otherwise there would be no remote devices found.

**Comment by cjcliffe** [comment]
ok; I'll try using openvpn in a similar setup here; it's possible that you may need some additional UDP / MTU related openvpn settings.

**Comment by cjcliffe** [comment]
@andresv currently running a 250kHz stream from an RTL-SDR on my work computer which I've connected via OpenVPN (TunnelBlick) it's been stable for about 20min so far.

Are there any other conditions I need to reproduce the issue?  I did notice it took about 10-15 seconds to refresh the remote server and see the device properties after clicking the device but after that it seemed to work ok.

**Comment by andresv** [comment]
Strange. I can do some more tests on Friday.

**Comment by andresv** [comment]
Actually tried just now and indeed connection is only made to server if i hit the `refresh` button, but nothing happens with `start`.

Not sure how to debug it further.

**Comment by cjcliffe** [comment]
@andresv it's really strange that the device properties aren't shown when you select the device; that means it was able to see the device but wasn't able to query it.  I'd imagine that's also why it's unable to start.  You should see an additional network connection occur when device selected during querying. 

Make sure SoapyRemote and SoapyRTLSDR / SoapyOsmo are up to date and match the host version just in case something has changed in the protocol or handling.
