### ISSUE TITLE
Question: What does this warning mean?

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#297]
[WARNING] mir_sdr version: '1.810' does not equal build version: '1.800'

Well, i know what it means, but what can i do about it?

**Comment by SDRplay** [comment]
Nothing, we're in the process of redoing the SoapySDRPlay library and will address the version numbers at that release.

**Comment by cjcliffe** [comment]
@SDRplay thanks for explanation; closing this one.
