### ISSUE TITLE
Wait-for-Vertical Sync causes very low framerate on Linux/Windows

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#30]
It appears that each of the shared context OpenGL panes (8 of them) will each wait for a vertical sync effectively limiting the framerate (i.e. 60hz / 8 = 7.5fps) -- Disabling vertical sync fixes the issue.

**Comment by croutonage** [comment]
vblank_mode=0 ./CubicSDR 

is an easy way to do this, and boy does it make a difference!

**Comment by cjcliffe** [comment]
@croutonage that seems to fix it (as was suggested by @mryndzionek ); I haven't had a chance to try setting that environment variable during start-up though -- I'm betting it can be set that way if it's initialized before the shared GL context.
