### ISSUE TITLE
Feature Request:  Auto-Select on squelch break

### ISSUE THREAD

**Issue by george-viaud** [cjcliffe/CubicSDR#303]
It's both useful and enjoyable (for some like myself) to watch the demodulation window when listening to a signal.  This helps fine tune for signal drift and monitor envelope.

Right now, only the currently selected modem is displayed in the demodulation window (which makes sense).

It would be nice if, on squelch-break, the option to push that modem to the selected modem would be nice as this would bring it into the demod window.

In the instance that multiple squelch-breaks happen in an overlapping fashion, a "last wins" priority would take place such that the most recent squelch-break would remain the selected demodulator.

This could be toggled perhaps with a keystroke or menu select as other features are mute for example).

Thank you

**Comment by cjcliffe** [comment]
@george-viaud this is actually already done..  If you enable Solo mode with 'S' and have squelch enabled the solo mode will automatically follow the squelch break and focus the modem :)
