### ISSUE TITLE
Feature request:  bookmarking or saving of a frequency/mode/filter settings for later fast recall

### ISSUE THREAD

**Issue by corq** [cjcliffe/CubicSDR#307]
Button or hotkey sequence that would write the currently frequency/mode/filter settings to say, an xml file that the user might also backup/import/export/share to other CubicSDR users, that can be easily recalled from a list.

**Comment by cjcliffe** [comment]
Ahoy,

I think most of this will be covered by #161 but if you have some specifics to add to that list or would like me to clarify or adjust any of the points there I'd be happy to refine it.

**Comment by corq** [comment]
That sounds like what I had in mind, thanks.
