### ISSUE TITLE
upper left (fine tuning?) window goes blank

### ISSUE THREAD

**Issue by tedder** [cjcliffe/CubicSDR#314]
<img width="1200" alt="screen shot 2016-03-16 at 8 42 09 pm" src="https://cloud.githubusercontent.com/assets/97914/13835689/996ccd74-ebb7-11e5-828b-1a360324ca94.png">

As you can see, even when I have a signal, the upper left window goes black. If I restart it'll come back. I can't figure out what causes it. I can still fine tune it, but the signal isn't there.

This is OSX, 0.1.20-alpha.

**Comment by cjcliffe** [comment]
@tedder can you give the build at https://github.com/cjcliffe/CubicSDR/releases/tag/v0.1.25-alpha a try and see if that helps at all? I'd be interested in knowing if this was fixed recently or is still an issue.

Thanks!

**Comment by tedder** [comment]
Sorry for the delay. So far I haven't reproduced it on 0.1.25-alpha.

**Comment by cjcliffe** [comment]
Sounds good to me; thanks for the report.
