### ISSUE TITLE
Serial port drop-down for Rig Control port

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#318]
Every time i boot my PC my serial port name changes, probably because i am using two Prolific adapters. One port always has the same name, the second port changes whenever i unplug and re-plug it or when i boot my PC.
So every time i want to use Rig Control i need to look up the serial port in my Terminal.

Is it possible to create a serial port drop-down similar to the below enumerating the available serial ports?

![screen shot 2016-03-23 at 20 08 02](https://cloud.githubusercontent.com/assets/4884243/13997533/fed4599a-f132-11e5-800f-3986dcbe43a3.png)

**Comment by cjcliffe** [comment]
I use something like this in the Arduino environment regularly; I think I can reproduce it without much trouble.

**Comment by cjcliffe** [comment]
I've added this to the list for #373 -- going to move all this stuff into a dialog.
