### ISSUE TITLE
Getting a seg fault & symbol lookup error

### ISSUE THREAD

**Issue by vsboost** [cjcliffe/CubicSDR#323]
Hi Charles,

With the binary image

Loading:: configuration file '/root/.CubicSDR/config.xml'
Unhandled DataElement toString for type: 0
Loaded PPM for device 'Generic RTL2832U OEM :: 00000001' at 0ppm
Loaded offset for device 'Generic RTL2832U OEM :: 00000001' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'HackRF One' at 0ppm
Loaded offset for device 'HackRF One' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'PulseAudio' at 0ppm
Loaded offset for device 'PulseAudio' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'SDRPlay RSP' at 0ppm
Loaded offset for device 'SDRPlay RSP' at 0Hz
SDR post-processing thread started..
Spectrum visual data thread started.
Spectrum visual data thread started.
./CubicSDR: symbol lookup error: ./CubicSDR: undefined symbol: gdk_mir_display_get_type

Not sure what i have done but thought i should let your know.

Cheers

**Comment by vsboost** [comment]
Thought i would attach some more info if it helps.
------------------
root@kali-sp2:~/Downloads/CubicSDR/build# cmake ../ -DCMAKE_BUILD_TYPE=Release -DwxWidgets_CONFIG_EXECUTABLE=~/Develop/wxWidgets-staticlib/bin/wx-config
-- The C compiler identification is GNU 5.3.1
-- The CXX compiler identification is GNU 5.3.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
64 bit compiler detected
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found LIQUID: /usr/local/lib/libliquid.so  
-- Found wxWidgets: -L/root/Develop/wxWidgets-staticlib/lib;-pthread;;;/root/Develop/wxWidgets-staticlib/lib/libwx_gtk3u_gl-3.1.a;-lGL;-lGLU;/root/Develop/wxWidgets-staticlib/lib/libwx_gtk3u-3.1.a;-lgtk-3;-lgdk-3;-lpangocairo-1.0;-lpango-1.0;-latk-1.0;-lcairo-gobject;-lcairo;-lgdk_pixbuf-2.0;-lgio-2.0;-lgobject-2.0;-lgthread-2.0;-pthread;-lglib-2.0;-lX11;-lXxf86vm;-lSM;-lgtk-3;-lgdk-3;-lpangocairo-1.0;-lpango-1.0;-latk-1.0;-lcairo-gobject;-lcairo;-lgdk_pixbuf-2.0;-lgio-2.0;-lgobject-2.0;-lglib-2.0;-lpng;-lz;-lwxregexu-3.1;-lwxtiff-3.1;-lwxjpeg-3.1;-lz;-ldl;-lm (found version "3.1.0") 
-- Copying /root/Downloads/CubicSDR/font/*.fnt to directory /root/Downloads/CubicSDR/build/x64
-- Configuring file vera_sans_mono12.fnt
-- Configuring file vera_sans_mono24.fnt
-- Configuring file vera_sans_mono18.fnt
-- Configuring file vera_sans_mono16.fnt
-- Configuring file vera_sans_mono48.fnt
-- Configuring file vera_sans_mono32.fnt
-- Copying /root/Downloads/CubicSDR/font/*.png to directory /root/Downloads/CubicSDR/build/x64
-- Configuring file vera_sans_mono12_0.png
-- Configuring file vera_sans_mono24_0.png
-- Configuring file vera_sans_mono16_0.png
-- Configuring file vera_sans_mono18_0.png
-- Configuring file vera_sans_mono48_0.png
-- Configuring file vera_sans_mono32_0.png
-- Copying /root/Downloads/CubicSDR/icon/CubicSDR.ico to directory /root/Downloads/CubicSDR/build/x64
-- Configuring file CubicSDR.ico
-- Configuring done
-- Generating done
-- Build files have been written to: /root/Downloads/CubicSDR/build
root@kali-sp2:~/Downloads/CubicSDR/build# make
Scanning dependencies of target CubicSDR
[  1%] Building CXX object CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o
[  2%] Building CXX object CMakeFiles/CubicSDR.dir/src/AppFrame.cpp.o
[  4%] Building CXX object CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o
[  5%] Building CXX object CMakeFiles/CubicSDR.dir/src/FrequencyDialog.cpp.o
[  7%] Building CXX object CMakeFiles/CubicSDR.dir/src/IOThread.cpp.o
[  8%] Building CXX object CMakeFiles/CubicSDR.dir/src/ModemProperties.cpp.o
[ 10%] Building CXX object CMakeFiles/CubicSDR.dir/src/sdr/SDRDeviceInfo.cpp.o
[ 11%] Building CXX object CMakeFiles/CubicSDR.dir/src/sdr/SDRPostThread.cpp.o
[ 12%] Building CXX object CMakeFiles/CubicSDR.dir/src/sdr/SDREnumerator.cpp.o
[ 14%] Building CXX object CMakeFiles/CubicSDR.dir/src/demod/DemodulatorPreThread.cpp.o
[ 15%] Building CXX object CMakeFiles/CubicSDR.dir/src/demod/DemodulatorThread.cpp.o
[ 17%] Building CXX object CMakeFiles/CubicSDR.dir/src/demod/DemodulatorWorkerThread.cpp.o
[ 18%] Building CXX object CMakeFiles/CubicSDR.dir/src/demod/DemodulatorInstance.cpp.o
[ 20%] Building CXX object CMakeFiles/CubicSDR.dir/src/demod/DemodulatorMgr.cpp.o
[ 21%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/Modem.cpp.o
[ 22%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/ModemAnalog.cpp.o
[ 24%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/ModemDigital.cpp.o
[ 25%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemAM.cpp.o
[ 27%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemDSB.cpp.o
[ 28%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemFM.cpp.o
[ 30%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemFMStereo.cpp.o
[ 31%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemIQ.cpp.o
[ 32%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemLSB.cpp.o
[ 34%] Building CXX object CMakeFiles/CubicSDR.dir/src/modules/modem/analog/ModemUSB.cpp.o
[ 35%] Building CXX object CMakeFiles/CubicSDR.dir/src/audio/AudioThread.cpp.o
[ 37%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/Gradient.cpp.o
[ 38%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/Timer.cpp.o
[ 40%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/MouseTracker.cpp.o
[ 41%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/GLExt.cpp.o
[ 42%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/GLFont.cpp.o
[ 44%] Building CXX object CMakeFiles/CubicSDR.dir/src/util/DataTree.cpp.o
[ 45%] Building CXX object CMakeFiles/CubicSDR.dir/src/panel/ScopePanel.cpp.o
[ 47%] Building CXX object CMakeFiles/CubicSDR.dir/src/panel/SpectrumPanel.cpp.o
[ 48%] Building CXX object CMakeFiles/CubicSDR.dir/src/panel/WaterfallPanel.cpp.o
[ 50%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/ColorTheme.cpp.o
[ 51%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/PrimaryGLContext.cpp.o
[ 52%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/InteractiveCanvas.cpp.o
[ 54%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/MeterCanvas.cpp.o
[ 55%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/MeterContext.cpp.o
[ 57%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/TuningCanvas.cpp.o
[ 58%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/TuningContext.cpp.o
[ 60%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/ModeSelectorCanvas.cpp.o
[ 61%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/ModeSelectorContext.cpp.o
[ 62%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/ScopeCanvas.cpp.o
[ 64%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/ScopeContext.cpp.o
[ 65%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/SpectrumCanvas.cpp.o
[ 67%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/WaterfallCanvas.cpp.o
[ 68%] Building CXX object CMakeFiles/CubicSDR.dir/src/visual/GainCanvas.cpp.o
[ 70%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/VisualProcessor.cpp.o
[ 71%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/ScopeVisualProcessor.cpp.o
[ 72%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/SpectrumVisualProcessor.cpp.o
[ 74%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/FFTVisualDataThread.cpp.o
[ 75%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/FFTDataDistributor.cpp.o
[ 77%] Building CXX object CMakeFiles/CubicSDR.dir/src/process/SpectrumVisualDataThread.cpp.o
[ 78%] Building CXX object CMakeFiles/CubicSDR.dir/src/ui/GLPanel.cpp.o
[ 80%] Building CXX object CMakeFiles/CubicSDR.dir/src/forms/SDRDevices/SDRDevices.cpp.o
[ 81%] Building CXX object CMakeFiles/CubicSDR.dir/src/forms/SDRDevices/SDRDevicesForm.cpp.o
[ 82%] Building CXX object CMakeFiles/CubicSDR.dir/src/forms/SDRDevices/SDRDeviceAdd.cpp.o
[ 84%] Building CXX object CMakeFiles/CubicSDR.dir/src/forms/SDRDevices/SDRDeviceAddForm.cpp.o
[ 85%] Building CXX object CMakeFiles/CubicSDR.dir/external/rtaudio/RtAudio.cpp.o
[ 87%] Building CXX object CMakeFiles/CubicSDR.dir/external/lodepng/lodepng.cpp.o
[ 88%] Building CXX object CMakeFiles/CubicSDR.dir/external/tinyxml/tinyxml.cpp.o
[ 90%] Building CXX object CMakeFiles/CubicSDR.dir/external/tinyxml/tinystr.cpp.o
[ 91%] Building CXX object CMakeFiles/CubicSDR.dir/external/tinyxml/tinyxmlparser.cpp.o
[ 92%] Building CXX object CMakeFiles/CubicSDR.dir/external/tinyxml/tinyxmlerror.cpp.o
[ 94%] Building CXX object CMakeFiles/CubicSDR.dir/external/cubicvr2/math/cubic_math.cpp.o
[ 95%] Building CXX object CMakeFiles/CubicSDR.dir/src/sdr/SoapySDRThread.cpp.o
[ 97%] Building CXX object CMakeFiles/CubicSDR.dir/src/ui/UITestCanvas.cpp.o
[ 98%] Building CXX object CMakeFiles/CubicSDR.dir/src/ui/UITestContext.cpp.o
[100%] Linking CXX executable x64/CubicSDR
[100%] Built target CubicSDR
root@kali-sp2:~/Downloads/CubicSDR/build# cd x64/
root@kali-sp2:~/Downloads/CubicSDR/build/x64# ./CubicSDR 
Loading:: configuration file '/root/.CubicSDR/config.xml'
Unhandled DataElement toString for type: 0
Loaded PPM for device 'Generic RTL2832U OEM :: 00000001' at 0ppm
Loaded offset for device 'Generic RTL2832U OEM :: 00000001' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'HackRF One' at 0ppm
Loaded offset for device 'HackRF One' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'PulseAudio' at 0ppm
Loaded offset for device 'PulseAudio' at 0Hz
Unhandled DataElement toString for type: 0
Loaded PPM for device 'SDRPlay RSP' at 0ppm
Loaded offset for device 'SDRPlay RSP' at 0Hz
SDR post-processing thread started..
Spectrum visual data thread started.
Spectrum visual data thread started.
FFT visual data thread started.

Audio Device #0 PulseAudio
	Default Output? Yes
	Default Input? Yes
	Input channels: 2
	Output channels: 2
	Duplex channels: 2
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
		32-bit float normalized between plus/minus 1.0.
	Supported sample rates:
		8000hz
		16000hz
		22050hz
		32000hz
		44100hz
		48000hz
		96000hz

SDR enumerator starting.
SoapySDR init..
	API Version: v0.5.0-gb16b6d6b
	ABI Version: v0.5-1
	Install root: /usr/local
	Loading modules... 
[ERROR] SoapySDR::loadModule(/usr/local/lib/SoapySDR/modules/libHackRFSupport.so)
  hackrf failed ABI check: Library ABI=0.5-1, Module ABI=0.4-2
	Available factories...null, rtlsdr, sdrplay
mir_sdr_Init: starting hardware initialization
mir_sdr_Init: gR=40dB fs=2.048MHz rf=222.064MHz bw=1.536MHz if=0.000MHz

mir_sdr_usb_USB DLL: Revision 0.1.1

Available vertical sync SwapInterval functions: 
	glxSwapIntervalEXT: No
	DRI2SwapInterval: No
	glxSwapIntervalMESA: No
	glxSwapIntervalSGI: No
No vertical sync swap interval functions available.
Loaded font 'Bitstream Vera Sans Mono' from '/root/Downloads/CubicSDR/build/x64/vera_sans_mono16.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/root/Downloads/CubicSDR/build/x64/vera_sans_mono12.fnt', parsed 167 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/root/Downloads/CubicSDR/build/x64/vera_sans_mono24.fnt', parsed 167 characters.
mir_sdr_usb_Init: Timeout expired/failed to establish connection with the device

mir_sdr_2500_Init: mir_sdr_usb_Init() failed
mir_sdr_Init: mir_sdr_2500_Init() Error 1

Reporting enumeration complete.
SDR enumerator done.
FFT visual data thread done.

(CubicSDR:2954): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(CubicSDR:2954): Gtk-CRITICAL **: gtk_widget_set_size_request: assertion 'GTK_IS_WIDGET (widget)' failed
Terminating SDR thread..
Terminating SDR post-processing thread..
SDR post-processing thread done.
Terminating Visual Processor threads..
Spectrum visual data thread done.
Spectrum visual data thread done.
root@kali-sp2:~/Downloads/CubicSDR/build/x64# 
![screenshot from 2016-04-03 20-46-25](https://cloud.githubusercontent.com/assets/11001973/14232029/6857dcf4-f9dd-11e5-8998-3d095fddf1b2.png)

**Comment by vsboost** [comment]
![screenshot from 2016-04-03 20-53-52](https://cloud.githubusercontent.com/assets/11001973/14232056/4c630432-f9de-11e5-92eb-f3b89fc51d5c.png)

If i close that box first i can start and all is working.

**Comment by cjcliffe** [comment]
@vsboost I'm seeing that dialog too -- I think it's related to some clearing of the glError state I may have disabled -- I'll fix that up and redo a build.

**Comment by cjcliffe** [comment]
@vsboost thanks for the help -- pull latest master and the OpenGL error dialog should be fixed up.

**Comment by vsboost** [comment]
Issue is now fixed.
Thanks
