### ISSUE TITLE
Donations/other

### ISSUE THREAD

**Issue by theforcedk** [cjcliffe/CubicSDR#328]
Charles, do you have a PayPal account for donations or can we help in other way? Appreciate all your hard work on this software - quite a task doing it all alone. Anything at all, hardware, other stuff or a paypal email, let me know. Supporting projects like this is important.

Thanks

**Comment by vsboost** [comment]
http://cubicsdr.com/?page_id=86

**Comment by theforcedk** [comment]
@vsboost Ah, excellent - I never actually visited the website itself, good stuff :) thank you
