### ISSUE TITLE
Test using LNA4ALL (HackRF mod/bias)

### ISSUE THREAD

**Issue by theforcedk** [cjcliffe/CubicSDR#331]
@cjcliffe Just wanted to let you/and others know that I've tested the bias setting successfully, with a LNA4ALL (HackRF mod) - http://lna4all.blogspot.dk/. No issues. Closing this for future reference.

**Comment by cjcliffe** [comment]
@theforcedk thanks -- I'm considering picking a couple of these up so that's good to know it will work properly 👍
