### ISSUE TITLE
Airspy not working with 0.1.27

### ISSUE THREAD

**Issue by gilbertoverg** [cjcliffe/CubicSDR#333]
With version 0.1.25 all is working fine, but with 0.1.27 all spectrums and waterfall remains blank

![untitled](https://cloud.githubusercontent.com/assets/18484638/14563287/6b88a0fa-0321-11e6-94c7-29128279ec00.png)

**Comment by cjcliffe** [comment]
@gilbertoverg hmm, I compiled my own copy of the Airspy host this time around so I probably did something strange -- I'll post another build in this issue soon for you to try.

**Comment by cjcliffe** [comment]
@gilbertoverg here's a build that uses the latest official release version instead of the GitHub master version of the airspy host -- let me know if this works any better: [CubicSDR-0.1.27-Darwin.dmg.zip](https://github.com/cjcliffe/CubicSDR/files/227118/CubicSDR-0.1.27-Darwin.dmg.zip)

**Comment by gilbertoverg** [comment]
@cjcliffe test build works perfectly. Thank you!

**Comment by cjcliffe** [comment]
@gilbertoverg good to hear; I'll update the 0.1.27 release build with this fix -- cheers!
