### ISSUE TITLE
Do not put AppImage into a zip file

### ISSUE THREAD

**Issue by probonopd** [cjcliffe/CubicSDR#334]
Thanks for providing an [AppImage](http://appimage.org/). Makes testing this application on Linux a joy.

Here are some minor suggestions for further improvement:

As you might be aware, the AppImage is an ISO file that mounts itself at runtime. It is already compressed, so you gain relatively little by putting it into a zip file. However, the user has to unpack it. This is not necessary if you just provide the AppImage itself for download. 

Possibly you did this so that the file is executable without specific user intervention. Granted, if you provide the AppImage for download rather than a zip then the user has to set the executable bit, but this is easy in most GUIs. Also, if you keep the ".AppImage" extension, then users can find help easily on what to do with this file.

By doing this, you could also make use of automated, easy binary delta updates using [AppImageUpdate](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md).

Are you aware that your binary is not stripped? You could save some space by running `strip` on it.

Finally, your AppImage requires at least glibc 2.15 which means that it will not run on distributions older than 2012ish. Is that acceptable for you? Otherwise, you could compile on an older build host distribution which would increase the compatibility of the resulting AppImage.

**Comment by cjcliffe** [comment]
@probonopd thanks! AppImageKit is working well so far and I'm looking to improve what I can -- I'm going to investigate everything you've suggested here for the 0.2.0 release build.   

I'll probably ping you here again soon if I have any questions :)

**Comment by probonopd** [comment]
@cjcliffe By the way, the AppImage is working great. Running it on Ubuntu 16.04 and listening to some FM radio. 

But I see an error saying

```
(CubicSDR:4003): Gtk-CRITICAL **: gtk_distribute_natural_allocation: assertion 'extra_space >= 0' failed
[ERROR] SoapySDR::loadModule(././/local/lib/SoapySDR/modules/libsdrPlaySupport.so)
  dlopen() failed: libmirsdrapi-rsp.so: cannot open shared object file: No such file or direct
```

**Comment by cjcliffe** [comment]
@probonopd Nothing to worry about; that's the SDRPlay module being noisy about not finding the mirsdr lib since it's not included in the bundle -- it needs to be installed separately since they're only available in binary form on the SDRPlay site.

**Comment by cjcliffe** [comment]
@probonopd I've added a new build -- no longer compressed, CubicSDR bin is stripped (saved around 1MB) and I've added the .AppImage extension.

Going to stick with glibc 2.15 as SoapySDRPlay requires it, but I'll re-think making an alternate build if there's demand.

Thanks again for all your hard work and assistance!
