### ISSUE TITLE
Feature request: please add recording to the application

### ISSUE THREAD

**Issue by dmitryelj** [cjcliffe/CubicSDR#339]
Hi guys,

Cubic SDR is the really great app for SDR receivers (its much better than HDSDR, for example). 

Only one feature, that is missing - no recording possibility in the app. Only because of this sometimes I need to reboot to Windows from MacOS, if I need to save something interesting. 
When the recording will be added, CubicSDR will be the complete solution for using with receiver.

Thanks.

**Comment by cjcliffe** [comment]
@dmitryelj thanks -- glad you're finding it useful.  There's an issue in related to this already but I'll consolidate once I start to sort the 0.2.x issues.
