### ISSUE TITLE
Feature request: Make Peak Hold display also for current demod view

### ISSUE THREAD

**Issue by vsonnier** [cjcliffe/CubicSDR#342]
I don't know if that would be really usefull or not, since I'm no specialist: 
Make the Peak Hold option also display  a peak hold on the detailed, current demodulator view which looks more precise and reflecting more the "real" shape of the signal.

**Comment by cjcliffe** [comment]
@vsonnier good call; it's already supported by that view I've just never thought to enable it.  Adding this to the enhancements, thanks!

**Comment by vsonnier** [comment]
I've implemented it in https://github.com/cjcliffe/CubicSDR/pull/368. It just works.

**Comment by cjcliffe** [comment]
looking good thanks!  I've also just added 'P' as the keyboard peak-hold toggle key.

**Comment by vsonnier** [comment]
Indeed, P as global shortcut is convenient. Thanks !
