### ISSUE TITLE
[, ] nudge dosn't work on OSX with non english keyboard layout

### ISSUE THREAD

**Issue by effeerre75** [cjcliffe/CubicSDR#343]
It works fine switching to english layout.

**Comment by cjcliffe** [comment]
@effeerre75  Hmm, do those keys still produce '[' and ']' when typed in non-english or does it map to something else?

**Comment by effeerre75** [comment]
In the Italian layout, for example, they produce "è" and "+". Then "[" and "]" are produced by pressing "alt è" and "alt +"  but dosen't work on CubicSDR. You can easly check it adding a new keyboard layout and then enabling the software keyboard. Let's me know if you need more info!
Thanks!

**Comment by cjcliffe** [comment]
@effeerre75 give this build a go and let me know if it works for you:

[CubicSDR-0.1.28-Darwin-keytest.dmg.zip](https://github.com/cjcliffe/CubicSDR/files/271767/CubicSDR-0.1.28-Darwin-keytest.dmg.zip)

Cheers!

**Comment by effeerre75** [comment]
Works really fine thanks! It work also without pressing the "alt" key: this is really handy!
Have a nice day!

**Comment by cjcliffe** [comment]
good to hear, if there's others like that I have a way to catch them now.

Cheers!
