### ISSUE TITLE
Provide Win32/64 binaries with AirSpy support

### ISSUE THREAD

**Issue by vsonnier** [cjcliffe/CubicSDR#362]
Well PothosSDR provides a CubicSDR build in Win32/Win64 binaries, (http://downloads.myriadrf.org/builds/PothosSDR/?C=M;O=D) with apparently AirSpy related libs: airpsy.dll, SoapyOsmoSDR.dll, and AirSpySupport.dll in modules.
 
So maybe it is now possible to provide AirSpy support in Windows pre-built binaries, while for now it is 
"(OSX) only" as Doc says.

I do not own an AirSpy so I can't test it myself, but  since the AirSpy Mini is out there, it will likely becomes even more popular and so that it would be useful for CubicSDR marketing as well :)

**Comment by cjcliffe** [comment]
Airspy support should now be in the latest windows binaries -- tried adding it to the Linux bundles but there's a segfault somewhere when attempting to load it.  My AirSpy Mini is en-route so I'll be finishing up the SoapyAirSpy module which will make it a lot simpler to compile and bundle (no SoapyOsmo or boost required).
