### ISSUE TITLE
Changing Active Demodulator Output

### ISSUE THREAD

**Issue by bodrick** [cjcliffe/CubicSDR#37]
It seems in Windows at least when I try and change the output of the demodulator, the menu doesn't update properly, it still will have the prior device selected, however if i then select another device, the device that I had previously selected is then selected.  It also seems that the actual doesn't get updated unless I select it twice.

**Comment by bodrick** [comment]
I forgot to add that this is Windows 8.1 64bit

**Comment by cjcliffe** [comment]
This is definitely a bug, it was working previously but appears to have been broken.

**Comment by cjcliffe** [comment]
Fix for this issue is now committed to master branch.
