### ISSUE TITLE
How about a build with Flatpak?

### ISSUE THREAD

**Issue by digver** [cjcliffe/CubicSDR#397]
I seen various issues here regarding builds for Linux and the different distributions. It looks like the current thought is to use Appimage, but it seems like that has issues as well --  #363 

Has [Flatpak](http://flatpak.org) been considered? It may be a better choice than Appimage -- Flatpak is supposed to be distro agnostic and runs apps in a sandbox.

**Comment by cjcliffe** [comment]
@digver I've been starting to think about it since #377 was reported so I'd definitely be interested in trying  it out.

**Comment by digver** [comment]
@cjcliffe I've been giving it a try. Here's the manifest I'm working with for flatpak-builder. 

[org.gnome.CubicSDR.json](https://gist.github.com/digver/99af1debbbad2176e4d4abbbc4cfafdd)

For the most part its based on the linux build instructions. 

The only place I've diverged is wth wxWidgets. I removed the configure options that looked like were for a static build. And that's where I have problems wxWidgets looks like it builds okay. but then CSDR fails after a lot of error output. I suspect it may be a wx-config issue but haven't yet had enough time to figure it out. 

The paths are a bit specific to my file system setup and I know its pretty dirty but it's a step.

**Comment by cjcliffe** [comment]
@digver thanks! I'll take a look soon -- wxWidgets build instructions have been static for awhile as there were too many different versions between distros so it was easier to bring your own "known working" version separate from the distro's and greatly simplified the instructions.

**Comment by digver** [comment]
@cjcliffe I guess static or dynamic doesn't really matter if it's one application running in a sandbox. 

In any case it looks like wxWidgets was not building with opengl and due to an error in the manifest I didn't notice. With the manifest corrected I can see wx is Isnt finding the opengl lib. I'll have to figure that out tomorrow.

**Comment by digver** [comment]
I've had some success building a CubicSDR.flatpak.  [I forked CSDR](https://github.com/digver/CubicSDR) and you can find the manifest, a test bundle, and a README file with some guidance on how to duplicate a build.True to form its all very rough. I don't know  how best to organize the directory and files. For now its in a a dir named flatpac. Any feedback is welcome.

CSDR can be run from flatpak but I don't know to what degree. I wasn't in a position tonight to actually try it out.

Some things I know are missing
- for the moment there are only modules for SoapySDR and SoapyAudio
- no hamlib 
- The worst part is I forgot to add a socket for pulseaudio, so no sound
- I did not give any permission to access the file system
- More I'm sure, especially since I don't know what I'm doing

**Comment by cjcliffe** [comment]
@digver thanks very much for getting this started; I should have a chance to get into it soon but you're making good progress 👍

**Comment by cjcliffe** [comment]
@digver I've set up a simple flatpak repository at https://github.com/cjcliffe/CubicSDR-flatpak that avoids having to check out CubicSDR before flatpak checks out CubicSDR :)

I've got the Makefile seemingly working now; just running some test builds and seeing where to go from here.

**Comment by cjcliffe** [comment]
@digver CubicSDR-flatpak build now working here for rtl-sdr and airspy; just working on adding additional modules.

**Comment by digver** [comment]
@cjcliffe great! I'll clone it in a bit. I think you're right a separate repository is the way to go.

**Comment by digver** [comment]
@cjcliffe  Adding device=all was a next step for me  after discovering I couldn't access USB devices, but along with that I believe device =dri can be removed  -- isn't redundant with the all?

Also we probably want to allow access to some files at least to save configs.  --filesystem=/home or --filesystem=~/path/to/config

**Comment by cjcliffe** [comment]
Ah, yeah will have to add some paths -- I'm done updates for tonight but everything except UHD and RFSpace should be good to go.

**Comment by digver** [comment]
Its all looking great and builds nicely here, but am not anywhere near by bench to try things out.

If you don't get to it first I'll see if I can figure out how to deal with the SoapySDRPlay. They don't make it easy to download the API/drivers.  It may require having the user install the drivers and the give SoapySDRPlay module access to the file location. I guess that would work for a local build but problematic for distribution.

Most of this is a learning process for me. I need to figure out how to sync a fork and make a pull-request for this stuff.

**Comment by cjcliffe** [comment]
@digver Looking good and working well here; I'll close this up for now and we can open new issues related to the flatpak usage or improvements.   Thanks again for your help!
