### ISSUE TITLE
FM broadcast de-emphasis

### ISSUE THREAD

**Issue by Alrescha-git** [cjcliffe/CubicSDR#412]
I'd like to suggest adding de-emphasis to the FM and (especially) FMS modes.

While the sound quality is currently excellent, it is a little too harsh to be listening for pleasure.  Adding 50us (EU)/75us (NA) would be a big help.

- [x] FM Stereo de-emphasis
- [ ] FM General de-emphasis

**Comment by cjcliffe** [comment]
@Alrescha-git agreed; this should be fairly straightforward to add to FM Stereo modem now; will take a look before doing the 0.2.0 final build

**Comment by cjcliffe** [comment]
@Alrescha-git I've added de-emphasis support for FM Stereo which will lead the way as the first use of the modem properties UI in 0.2.0.

I'll be working on filtering options for the modem properties of other modems soon so I'll leave this issue open as a reminder to implement the de-emphasis for FM Mono.

**Comment by Alrescha-git** [comment]
Thank you.  I am looking forward to giving it a try.

**Comment by cjcliffe** [comment]
@Alrescha-git will be included in the rc5 build; cheers!

**Comment by Alrescha-git** [comment]
Downloaded and gave it a listen - fantastic.

**Comment by cjcliffe** [comment]
@Alrescha-git sounding great here as well -- better than expected; thanks for reminding me to finally look into this.  Hoping to add some more filters to other modes with the new settings UI too.

**Comment by yo2ldk** [comment]
nice add stereo option, Thank you !
 but, if we are in any other mode, am usb,lsb, if I push "F" taste, remain in selected mode not changing to FM.
Also if you can made user colour display, that will be great, and fill spectrum ...etc.  :)
 all the best !
