### ISSUE TITLE
Program Crashing

### ISSUE THREAD

**Issue by ericharjula** [cjcliffe/CubicSDR#420]
Using CubicSDR with Nooelec NEsdr Smart on windows 7. Program crashes about 10 minutes with continuous use.

**Comment by cjcliffe** [comment]
@ericharjula are you using the latest 0.2.0-rc5 version from https://github.com/cjcliffe/CubicSDR/releases ? many windows related crashes were resolved recently.

**Comment by ericharjula** [comment]
No I was not. I just downloaded it. I'll give it a shot and see what happens. Thank you
