### ISSUE TITLE
It is difficult to adjust squelch when signal level is low 

### ISSUE THREAD

**Issue by Torrio888** [cjcliffe/CubicSDR#427]
It is difficult to adjust squelch when signal level is low. 
![brazilian satcom pirates](https://cloud.githubusercontent.com/assets/21010324/17648604/188bcc7e-621c-11e6-9354-71fd0affe81a.png)

**Comment by cjcliffe** [comment]
@Torrio888 thanks -- I recently noticed this as well and the latest commits to master and future release builds include a dynamic squelch range that's much easier to set the trigger level with.

If you're not building from source then keep an eye out for the RC6 build on the releases page likely later this week -- https://github.com/cjcliffe/CubicSDR/releases which will include the squelch updates.
