### ISSUE TITLE
Zoom presets for HAM bands.

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#428]
Can you create some zoom presets for the HAM bands? Or even better, configurable?

Thanks and keep up the great work!

Ton.

**Comment by cjcliffe** [comment]
I'll take a look at getting the range input working that we discussed before at least; I think the configuration of zooms would be a good addition to the bookmarks though.

**Comment by cjcliffe** [comment]
@Toontje can now type ranges into center frequency input dialog in master branch :)

**Comment by Toontje** [comment]
Thank you! Now i need to get all my build tools working again.

**Comment by cjcliffe** [comment]
@Toontje I've added the saving of zoom presets to #161 so it isn't forgotten; but it looks like this will work for the moment so I'll close it up.
