### ISSUE TITLE
Help! Beta RC6.

### ISSUE THREAD

**Issue by lon55** [cjcliffe/CubicSDR#434]
I love this update. I works very smoothly and I have exercised every function for the last two days without a crash running windows 8.

However, I can't figure out how to pipe audio to other apps via VAC. There doesn't seem to be a function in the audio pull-down box, unless I am just missing it.

**Comment by cjcliffe** [comment]
@lon55 the "audio output" per-modem is now in the modem properties box beside the modulation buttons -- if the outputs aren't showing in that drop-down list when you open it there might be a problem with the audio device enumeration -- can you confirm the VACs are showing in other applications?

Try running from the command line like so:
```
cd "C:\Program Files\CubicSDR\"
CubicSDR.exe > cubic_output.txt
```

And then quit right away and paste the contents of cubic_output.txt in this issue and we should see the audio device init list in there.

**Comment by lon55** [comment]
It was simpler than this, I believe:

![modem properties](https://cloud.githubusercontent.com/assets/21312413/18074057/d157d1de-6e61-11e6-9de9-a067ce05653d.PNG)

**Comment by lon55** [comment]
The tab for Audio Out is the Modem Properties tab you were referring to, I'm guessing.  Everything is working fine.  Thanks much

**Comment by cjcliffe** [comment]
yup that's it -- glad it wasn't something more serious; I'll have some more details in the 0.2.0 manual release :)
