### ISSUE TITLE
Loading SoapySDR Modules

### ISSUE THREAD

**Issue by heath33** [cjcliffe/CubicSDR#450]
Running fresh install of Debian Testing (up to date) and using a SDRPlay (recent API Driver).  The rest built per the Build Linux page. Source cloned from https://github.com/cjcliffe/CubicSDR.git ..  I've got hamlib-utils libhamlib-dev  and that seems to all be working (it even works in CubicSDR).

When I build CubicSDR with -DUSE_HAMLIB=1 the application hangs on startup, specifically it will not find the SoapySDR module Local>"SDRPlay RSP".  

When I build CubicSDR without the Hamlib flag, the application does not hang and works fine.

I had it all working back in Version 0.2.0-beta-rc2 on an older install, but can't get it going on this fresh install (can't get CubicSDR to find SDRPlay in 0.2.0-beta-rc2 with Rig Control flag now)

Likely just me ... but I thought I'd share.

Heath

**Comment by vsonnier** [comment]
This issue has got stale. CubicSDR recent versions has shown to work well under Linux with the SDRPlay, including Hamlib, so I'm closing this issue.
