### ISSUE TITLE
Quickly jump to view/band

### ISSUE THREAD

**Issue by TonMachielsen** [cjcliffe/CubicSDR#451]
Here is the use case:
I have saved my settings per HAM band i want to watch/listen to. Every time i want to see a different band i need to File, Open Session, Browse for the correct session file and open it.
It would improve my workflow a lot if i could select session files from the main screen. In my case as HAM band selector, but i can imagine that other people have other uses for a preset selector on the main screen.

**Comment by cjcliffe** [comment]
@TonMachielsen there's a bookmarks branch in the works which has basic integrated active, bookmark and recents list with drag & drop support and grouping.

I think you'll be able to create groups easily and there will be an option to "open all in group" but I don't see why I couldn't add an option to save the center frequency/view like sessions do as another branch of items in the bookmarks list so you can just double click to jump to them.

**Comment by cjcliffe** [comment]
@Toontje Interesting; perhaps some sort of bar at the top of the application where you could pin bookmarks.

**Comment by Toontje** [comment]
How about between the modem waterfall and the main waterfall here:

<img width="838" alt="screen shot 2016-10-17 at 11 03 15" src="https://cloud.githubusercontent.com/assets/4884243/19431596/64f9b070-9459-11e6-9fce-367d50bf6efb.png">

or, even better, between the frequency display and the main waterfall here:

<img width="793" alt="screen shot 2016-10-17 at 11 03 29" src="https://cloud.githubusercontent.com/assets/4884243/19431606/6beda7c4-9459-11e6-9f32-b8e105ad05ee.png">

**Comment by cjcliffe** [comment]
Hmm, perhaps a standard ribbon UI on the top for favourite bookmarks and views and other things; would like to avoid dividing or cluttering the main UI though -- will have to think about that but can at least start with supporting it in the bookmark manager.

**Comment by Toontje** [comment]
How about doing it like SDR Touch? You can hide the bookmarks menu where you have the DSB settings now. Like this:
![sdr-touch-live-radio-via-usb-screenshot-004-1277x718](https://cloud.githubusercontent.com/assets/4884243/20476963/d9cc3ba8-afd3-11e6-876a-df8f3e0c845f.jpg)

**Comment by Toontje** [comment]
For me this is now covered by the Bookmarks function. As far as i'm concerned you can close this issue.

**Comment by cjcliffe** [comment]
Excellent 👍  we can revisit pinning something to a button bar if the UI features become relevant.

**Comment by Toontje** [comment]
No need. It’s perfect as it is.
