### ISSUE TITLE
Windows  dragging mouse flys right

### ISSUE THREAD

**Issue by TheSkorm** [cjcliffe/CubicSDR#465]
Not really sure how to explain this but on my Windows 10 install of v0.2.0 when I'm dragging the demodulator around in either the small or big view it frequently forces my mouse pointer to the right hand side of the screen making me loose where the demod window should of been which is frustrating. 

I've tried with hover tips off but that doesn't seem to effect it

I've updated a zipped MP4 for the problem occurring. You'll notice that it causes a click event on the waterfall speed and the demodulator squelch sliders.

[FFsplit-161123-193100.zip](https://github.com/cjcliffe/CubicSDR/files/608370/FFsplit-161123-193100.zip)

**Comment by vsonnier** [comment]
This issue is too old, Windows 10 was updated from that time, and now that I have Windows 10 as well I never managed to reproduce this behavior. Maybe it is related to the Aero Snap configuration ?

Anyway, I'm closing this one up.
