### ISSUE TITLE
What is up with new releases? OS X Sierra support? New API support? SDRPlay 2.0 support?

### ISSUE THREAD

**Issue by MiamiC70** [cjcliffe/CubicSDR#471]
What is up with new releases? OS X Sierra support? New API support? SDRPlay 2.0 support?

**Comment by SDRplay** [comment]
We're working on SoapySDRPlay on for both RSP1 and RSP2 - hopefully have something to test soon.

**Comment by cjcliffe** [comment]
@MiamiC70 should hopefully have an experimental build out with a bookmark manager before the end of the year which will have updated Soapy API support for SDRPlay as well.

**Comment by MiamiC70** [comment]
Will that build be supporting the new SDRPlay 2?

**Comment by cjcliffe** [comment]
@MiamiC70 I'm unsure as of the compatibility of the current lib with the new API but SoapySDR should at least be up to date to accept the new module when it's ready.

**Comment by cjcliffe** [comment]
@MiamiC70 Latest builds at https://github.com/cjcliffe/CubicSDR/releases/tag/0.2.1-alpha1 should work with the RSP1 and RSP2 with SDRPlay API installed on Sierra.

Build guide updates for Sierra will be done soon as well; cheers!

**Comment by MiamiC70** [comment]
Excellent,  thank you
