### ISSUE TITLE
Problem installing CubicSDR on Mac OSX 10.11.6

### ISSUE THREAD

**Issue by Venz299** [cjcliffe/CubicSDR#472]
I have tried to install CubicSDR using the Building guide. Everything works as advertised, but when Building CubicSDR at the "cmake" step everything came to a standstill. A message came up" "Configuring incomplete, errors occured!"

Here's the code:

`iMac-van-Sven:CubicSDR svenscheffers$ cd build
iMac-van-Sven:build svenscheffers$ cmake ../ -DwxWidgets_CONFIG_EXECUTABLE=/Users/svenscheffers/wxWidgets/wxWidgets-staticlib/bin/wx-config -DCMAKE_BUILD_TYPE=Release -DBUNDLE_APP=1 -DCPACK_BINARY_DRAGNDROP=1
-- The C compiler identification is AppleClang 7.3.0.7030031
-- The CXX compiler identification is AppleClang 7.3.0.7030031
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
64 bit compiler detected
-- Found OpenGL: /System/Library/Frameworks/OpenGL.framework  
-- Found LIQUID: /usr/local/lib/libliquid.dylib  
CMake Error at /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find wxWidgets (missing: wxWidgets_LIBRARIES
  wxWidgets_INCLUDE_DIRS)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.5.2/share/cmake/Modules/FindwxWidgets.cmake:887 (find_package_handle_standard_args)
  CMakeLists.txt:123 (find_package)

-- Configuring incomplete, errors occurred!
See also "/Users/svenscheffers/Dev/SoapySDR/build/CubicSDR/build/CubicSDR/build/CMakeFiles/CMakeOutput.log".
iMac-van-Sven:build svenscheffers$ 
`

What went wrong. To be shure I repeated previous steps, even the steps of the other builds, but no joy for now. I use OSX 10.11.6 on my iMac.

Thanks in advance for your help.

Venz

**Comment by cjcliffe** [comment]
Ahoy @Venz299 -- there's a few possibilities here and I'm tracking a possibly related issue.

I've forgotten that someone already contributed a converted version of the instructions to the manual site which I'll probably remove and replace with a link to https://github.com/cjcliffe/CubicSDR/wiki/Build-OSX -- if you used the instructions from the manual try these ones instead for wxWidgets and see if the situation improves.

Otherwise can you confirm that `/Users/svenscheffers/wxWidgets/wxWidgets-staticlib/bin/wx-config` exists?  It should have provided  wxWidgets_LIBRARIES
and wxWidgets_INCLUDE_DIRS -- is it possible you missed the `make install` step of building wxWidgets?

It's also possible with recent updates to the build instructions that there's still a problem somewhere -- I was tweaking the paths for wxWidgets which were previously in error; I'll re-read and re-try my own instructions again soon to be sure.

**Comment by Venz299** [comment]
Thanks for your quick response. The new instructions are working. I'm now able to run all the steps. without error messages.

But...Unfortunately, when I start the CubicRTL program, a popup appears with the message that the program is unexpectedly stopped. Ignore/report/open again. (but then in Dutch ;)). As I use an RTLSDR dongle, I installed the additional SoapyRTLSDR module, but no joy. Still get the popup message.

Rebooting my Mac and then tried again, still no joy. :'(

**Comment by cjcliffe** [comment]
@Venz299 can you remove the SoapyRTLSDR module and try installing SoapyAudio?  That would help see if basic mic input is working and determine if this is an RTL-SDR specific issue.

If SoapyAudio does the same; try removing it too and see what happens with no modules; if it still crashes possibly try re-building SoapySDR itself and then SoapySDR modules and CubicSDR again in that order.

**Comment by Venz299** [comment]
Thanks. I tried the first steps without result. Then I removed everything and started again. Before installing CubicSDR I installed the SoapySDR and Soapy RTLSDR. That does the trick. Now It's up and running.

**Comment by cjcliffe** [comment]
@Venz299 good to hear; if there was any Soapy stuff that CubicSDR could build against already installed before you built SoapySDR then it would end up incompatible with the final SoapySDR build.

Glad that's all it was and thanks for helping me notice to fix up the documentation links :)
