### ISSUE TITLE
Sorting of ranges

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#478]
Awesome work on the bookmarks! Exactly what i was looking for!!

One question: What is the sorting of the ranges based on?
<img width="167" alt="screen shot 2016-12-30 at 09 35 10" src="https://cloud.githubusercontent.com/assets/4884243/21561890/75751508-ce73-11e6-9ed1-e7ead729b3e3.png">

**Comment by cjcliffe** [comment]
@Toontje they're ordered by the center frequency of the view; the visible range and center frequency are separate so it's good to have the center freq in view range (place with 'C') if you're switching sample rates often.

**Comment by Toontje** [comment]
Can sorting be made optional?

**Comment by cjcliffe** [comment]
@Toontje yup and will probably be the norm once more sorting/management UI is implemented.  

Right now it's not so much 'sorting' it internally that I can turn off as much as it's just the current display criteria which was easiest to implement.
