### ISSUE TITLE
Modifying ranges

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#479]
How do i modify a range? I know you can modify the label, but how do i modify the frequencies?

**Comment by cjcliffe** [comment]
@Toontje yup this is an oversight for sure; I'll add a way to edit them.

**Comment by cjcliffe** [comment]
Master branch now includes a button to update an existing range to the active view; cheers!

**Comment by Toontje** [comment]
Nice! If only i knew how to build CubicSDR properly.... How's the Civic? ;-)

**Comment by cjcliffe** [comment]
@Toontje aye; sorry been reluctant to upgrade my MacBook yet to get it building but machine at work should be doable in the next couple weeks.  Haven't gone car shopping yet; just got the old one towed this morning :)
