### ISSUE TITLE
Compilation errors on OS X with the new version

### ISSUE THREAD

**Issue by mehdideveloper** [cjcliffe/CubicSDR#483]
Hi
After checking out the new version, I've got multiple compilation errors (It was OK the last time I checked, about 1 month ago)

Error log: http://pastebin.com/JKPNREiA

**Comment by starvald** [comment]
no good for me either on ubuntu 16.04 x64.

same errors.

**Comment by vsonnier** [comment]
Confirmed also on Win64. Problem should be fixed by #484.

**Comment by cjcliffe** [comment]
Thanks all for getting this reported and fixed quickly! 👍
