### ISSUE TITLE
Ability to collapse the scope... or...

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#487]
...so i can have a larger zoomed modem waterfall and spectrum.
I guess that means that the tuning bar needs to move as well. :-(

Or give more functionality to the scope. Like the digital lab maybe? With CW, PSK, RTTY, JT, etc decoders?

**Comment by cjcliffe** [comment]
@Toontje there's going to be more visualizer options there in the future besides just scope, etc. and it will likely be where the visual filtering tools are going to go.
