### ISSUE TITLE
Please make demod snapping optional

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#488]
Can you make the demodulator snapping in the waterfall optional?

**Comment by cjcliffe** [comment]
@Toontje not sure what you mean exactly; you can disable snapping by right-clicking the highlighted digit on the frequency tuning bar?

**Comment by Toontje** [comment]
I tried again and i understand what's happening. When i have a modem active and i want to create a second active modem i cannot create an active modem of which the center frequency falls within the bandwidth of the first one. The modem selector than "snaps" to the center frequency of the first created modem.
All clear. Please close the issue as a self-answered question. ;-)

**Comment by cjcliffe** [comment]
@Toontje ahh; I mis-interpreted it as the frequency snap option.

There is actually a solution already built-in for for moving the active modem within it's own bandwidth since the first release; just double-click instead of single ;)

Will close this one up.

**Comment by Toontje** [comment]
Thanks for the tip!
