### ISSUE TITLE
CubicSDR Hangs while attempting to connect with remote server (SoapySDR/SDRPlay)

### ISSUE THREAD

**Issue by corq** [cjcliffe/CubicSDR#496]
Symptom, Cubic finds remote SDR properly, attempt to connect with default CubicSDR audio/sample rate settings. SDR connects, audio begins when I click waterfall, but quickly freezes before I can adjust samplerate or test lower settings.

If this is pebkac or something I can adjust, please advise ;-)

Note: this is while connecting to new 64 bit SDRPlay update for ARM64:
 SDRplay_RSP_API-ARM64-2.09.1.run, and I'll also post this over at their forums but thought I'd post here as well.

Logs I've captured, unsure if helpful:

cat CubicSDR.logs 
Loading:: configuration file '/home/corq/.CubicSDR/config.xml'

Audio Device #0 PulseAudio
	Default Output? Yes
	Default Input? Yes
	Input channels: 2
	Output channels: 2
	Duplex channels: 2
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
		32-bit float normalized between plus/minus 1.0.
	Supported sample rates:
		8000hz
		16000hz
		22050hz
		32000hz
		44100hz
		48000hz
		96000hz

Available vertical sync SwapInterval functions: 
	glxSwapIntervalEXT: No
	DRI2SwapInterval: No
	glxSwapIntervalMESA: No
	glxSwapIntervalSGI: No
No vertical sync swap interval functions available.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono12_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono16_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono18_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono24_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono27_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono32_0.png', parsed 255 characters.
Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono36_0.png', parsed 255 characters.
SDR enumerator starting.
SoapySDR init..
	API Version: v0.6.0
	ABI Version: v0.6-dev
	Install root: /usr/local
	Loading modules... 
	Available factories...null, remote

Reporting enumeration complete.
SDR enumerator done.
ERROR: thread '9SDRThread' has not terminated in time ! (> 2000 ms)
SDR enumerator starting.
SoapySDR init..
	API Version: v0.6.0
	ABI Version: v0.6-dev
	Install root: /usr/local
	Loading modules... 
	Available factories...null, remote
  driver = remote
  label = SDRplay Dev0 RSP1 B0001P0001
  remote = tcp://192.168.1.20:1234
  remote:driver = sdrplay
Make device 0
  mir_sdr_api_version=2.090000
  mir_sdr_hw_version=1

Reporting enumeration complete.
SDR enumerator done.
SDR thread starting.
device init()
Stream MTU: 357
starting readLoop()
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '101' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '102' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '103' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '104' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '105' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '106' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '107' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '108' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '109' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '110' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '111' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '112' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '113' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '114' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '115' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '116' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '117' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '118' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '119' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '120' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '121' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '122' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '123' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '124' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '125' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '126' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '127' exceeds threshold of '100'
Warning: ReBuffer 'SDRPostThreadVisualDataBuffers' count '128' exceeds threshold of '100'

**Comment by vsonnier** [comment]
This issue is replaced by #603, which will be closed as well in a near future because the root cause has been found in the SoapySDRPlay module. Consequently, I'm closing this old issue.
