### ISSUE TITLE
X11 forwarding produces an audio error

### ISSUE THREAD

**Issue by bogdanr** [cjcliffe/CubicSDR#518]
I am running it through a SSH tunnel and I am receiving an error that is not there when I run it locally.
`DemodulatorThread::run() cannot push ati into audioOutputQueue, is full !`

The command I use to run it remotely is:
`ssh -C -Y 192.168.1.120 CubicSDR`

**Comment by vsonnier** [comment]
This issue is too old, and has received no feedback. Closing.
