### ISSUE TITLE
Bookmark Issues

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#525]
From @vsonnier #519 --

- [x] More often than not, when activating a Bookmark, Active, Recent, the demod view aligns properly but the main Waterfall/Spectrum doesn't move.
- [x] When activating (in Active list ?) often a demod is created on top of a existing one. (thanks to OpenGL, it's even visible on screen directly !). You can even delete it, the old one then shows up.

**Comment by cjcliffe** [comment]
Been tinkering; looks like some events are firing from programmatic calls causing properties to bounce back and forth as well as the selection event fires both a select and de-select event which isn't handled properly; should have this solved soon.

**Comment by cjcliffe** [comment]
@vsonnier I've merged some fixes for this;  managed to boil it down to a few minor changes -- let me know if that's working any better for you as well.

**Comment by vsonnier** [comment]
@cjcliffe Issue item 1 seem OK now, thanks. 
I'm now working on item 2 about the duplicated demodulators, so I'll get back to you when it is ready.

**Comment by vsonnier** [comment]
@cjcliffe Hi there ! I've comitted on master c8cca67fc749242081f4c36b54f5ef40a6125c7e
which fixes item 2, plus some other cleanups around Bookmarks. Tell me what you think !

**Comment by cjcliffe** [comment]
@vsonnier looks great thanks; will close this one up!
