### ISSUE TITLE
CubicSDR 0.2.2-alpha hangs when samplerate > 2.048MHz

### ISSUE THREAD

**Issue by acseuser** [cjcliffe/CubicSDR#529]
I'm running Ubuntu 16.04, and the current version of CubicSDR, I think.

IT is connected to an SDRplay via a local USB port - seems to work OK: I can demodulate stuff, and I don't get warning msgs in the syslog about buffer errors. But if I increase the SampleRate to > 2.048MHz, the machine hangs; only way out is a power off reboot. I think the SDRplay is supposed to operate upto 8MHz BW.

Here's a snippet of the syslog at startup:
Mar 29 03:32:28 Jess gnome-session[1628]: Loading:: configuration file '/home/simonr/.CubicSDR/config.xml'
Mar 29 03:32:28 Jess gnome-session[1628]: Audio Device #0 PulseAudio
Mar 29 03:32:28 Jess gnome-session[1628]: #011Default Output? Yes
Mar 29 03:32:28 Jess gnome-session[1628]: #011Default Input? Yes
Mar 29 03:32:28 Jess gnome-session[1628]: #011Input channels: 2
Mar 29 03:32:28 Jess gnome-session[1628]: #011Output channels: 2
Mar 29 03:32:28 Jess gnome-session[1628]: #011Duplex channels: 2
Mar 29 03:32:28 Jess gnome-session[1628]: #011Native formats:
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01116-bit signed integer.
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01132-bit signed integer.
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01132-bit float normalized between plus/minus 1.0.
Mar 29 03:32:28 Jess gnome-session[1628]: #011Supported sample rates:
Mar 29 03:32:28 Jess gnome-session[1628]: #011#0118000hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01116000hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01122050hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01132000hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01144100hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01148000hz
Mar 29 03:32:28 Jess gnome-session[1628]: #011#01196000hz

And this is the log when I installed the SDRplay:
Mar 29 02:13:22 Jess kernel: [ 2265.103701] usb 2-1.3: new high-speed USB device number 4 using ehci-pci
Mar 29 02:13:22 Jess kernel: [ 2265.196462] usb 2-1.3: New USB device found, idVendor=1df7, idProduct=2500
Mar 29 02:13:22 Jess kernel: [ 2265.196470] usb 2-1.3: New USB device strings: Mfr=0, Product=0, SerialNumber=1
Mar 29 02:13:22 Jess kernel: [ 2265.196474] usb 2-1.3: SerialNumber: 0000000001
Mar 29 02:13:22 Jess mtp-probe: checking bus 2, device 4: "/sys/devices/pci0000:00/0000:00:1d.0/usb2/2-1/2-1.3"
Mar 29 02:13:22 Jess mtp-probe: bus: 2, device: 4 was not an MTP device
Mar 29 02:13:22 Jess gnome-session[1628]: mir_sdr_usb_GetDevices Dev0:vid=1df7 pid=2500 rev=0206 serno=B0002P0003 bus=002 port=003 devAvail=1
Mar 29 02:13:22 Jess gnome-session[1628]:   driver = sdrplay
Mar 29 02:13:22 Jess gnome-session[1628]:   label = SDRplay Dev0 RSP1 B0002P0003
Mar 29 02:13:22 Jess gnome-session[1628]: Make device 0
Mar 29 02:13:22 Jess gnome-session[1628]: mir_sdr_usb_GetDevices Dev0:vid=1df7 pid=2500 rev=0206 serno=B0002P0003 bus=002 port=003 devAvail=1
Mar 29 02:13:22 Jess gnome-session[1628]: mir_sdr_usb_SetDeviceIdx idx=0 numDevices=1
Mar 29 02:13:22 Jess gnome-session[1628]: Opened device with idVendor = 0x1df7 idProduct = 0x2500 fwVersion = 0x0206 busNum = 002 portNum = 003
Mar 29 02:13:22 Jess gnome-session[1628]:   mir_sdr_api_version=2.090000
Mar 29 02:13:22 Jess gnome-session[1628]:   mir_sdr_hw_version=1
Mar 29 02:13:22 Jess gnome-session[1628]: mir_sdr_usb_ReleaseDeviceIdx 0
Mar 29 02:13:22 Jess gnome-session[1628]: Reporting enumeration complete.
Mar 29 02:13:22 Jess gnome-session[1628]: SDR enumerator done.
Mar 29 02:13:24 Jess gnome-session[1628]: mir_sdr_usb_GetDevices Dev0:vid=1df7 pid=2500 rev=0206 serno=B0002P0003 bus=002 port=003 devAvail=1
Mar 29 02:13:24 Jess gnome-session[1628]: mir_sdr_usb_SetDeviceIdx idx=0 numDevices=1
Mar 29 02:13:24 Jess gnome-session[1628]: Opened device with idVendor = 0x1df7 idProduct = 0x2500 fwVersion = 0x0206 busNum = 002 portNum = 003
Mar 29 02:13:25 Jess gnome-session[1628]: SDR thread starting.
Mar 29 02:13:25 Jess gnome-session[1628]: device init()
Mar 29 02:13:25 Jess gnome-session[1628]: [INFO] Using format CF32.
Mar 29 02:13:25 Jess gnome-session[1628]: Stream MTU: 65536
Mar 29 02:13:25 Jess gnome-session[1628]: mir_sdr_StreamInit()
Mar 29 02:13:25 Jess gnome-session[1628]: mir_sdr_Init: starting hardware initialization
Mar 29 02:13:25 Jess gnome-session[1628]: mir_sdr_Init: gR=40dB fs=2.048MHz rf=100.000MHz bw=1.536MHz if=0.000MHz
Mar 29 02:13:25 Jess gnome-session[1628]: DownConvert: Enable=0 DecM=1 OutScale=0 (fs=2.048000 bw=1536 if=0)
Mar 29 02:13:25 Jess gnome-session[1628]: mir_sdr_usb_USB DLL: Revision 0.1.1

Any further info. required ?

Thanks,
SR

**Comment by cjcliffe** [comment]
Haven't experienced this myself with Ubuntu 16 and RSPv1 -- I'll keep this open and tagged for 'help wanted' -- if others experience the same we might get more insight.

The only thing off the top of my head I can think to ask is whether you're using the RSP with a USB extension cable or Hub?  That's the only time I've experienced significant drop-outs and crashes with the RSP1 was when communication was poor -- if that's the case using a shorter cable or adding some ferrite beads to the USB cable might help.

**Comment by acseuser** [comment]
Charles,
Nope, no hub - RSP1 directly to laptop. via a decent (I thought) USB cable. I will try another, just in case.
I can achieve 8MHz using a different, older laptop, so the RSP / cable combo can do it. Unfortunately, this laptop doesn't have a windows partition, so it's not a perfect comparison..

Thanks,
SR

**Comment by ElectronicBattle** [comment]
I've had the same problem. Trying to get a locally compiled version of CubicSDR 022 or the (appimages 020 or 021) to recognise the SDRPlay RSP was only possible by adding three entries to modprobe.d/blacklist.conf, namely 
# blacklist sdr_msi3101
# blacklist msi001
# blacklist msi2500
(info from http://kb9rlw.blogspot.co.uk/2017/06/step-by-step-install-of-sdrplay-rsp2.html)

Changing the RSP's  i/p sample rate from 2048 causes my complete OS to lock up (linux Mint 18.1, Mate edition ==16.04 base) and even ctrl+alt+F1 etc. won't spawn a new session. Mains reboot needed!

The same happens for gqrx too. 

I don't know what to do to help you if you were to try to find a solution to this problem, which is clearly not peculiar to CubicSDR alone.

**Comment by dunaybd** [comment]
No problem with Linux Mint 18.2 (based on Ubuntu 16.04) and RSP2.

**Comment by vsonnier** [comment]
No problem either with Windows 7/10 x64 using the API v2.10 and RSP2.

**Comment by stuzog** [comment]
CubicSDR-0.2.3-x86_64.AppImage launches in Linux Mint 18.2 but no signal showing, just this is Terminal:

```
SDRThread::readStream(): 2. SoapySDR read failed with code: -1
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
```
repeated multiple times.

**Comment by vsonnier** [comment]
Be bold and suppose the remaning issues are indeed AppImage ones, listed in #611, so I'm closing this one.
