### ISSUE TITLE
Bookmark XML has every parameter node twice (Mac)

### ISSUE THREAD

**Issue by stevefal** [cjcliffe/CubicSDR#536]
When editing bookmark XML, I notice that every <modem> entry contains two copies of each parameter node. I assume that only one is necessary:

            <modem>
                <bandwidth>10000</bandwidth>
                <frequency>26965000</frequency>
                <type>AM</type>
                <user_label>%43%42%31</user_label>
                <squelch_level>-54.0722</squelch_level>
                <squelch_enabled>1</squelch_enabled>
                <output_device>MOTU: MOTU 896mk3 Hybrid</output_device>
                <gain>1</gain>
                <muted>0</muted>
                <active>1</active>
                <bandwidth>10000</bandwidth>
                <frequency>26965000</frequency>
                <type>AM</type>
                <user_label />
                <squelch_level>-54.0722</squelch_level>
                <squelch_enabled>1</squelch_enabled>
                <output_device>MOTU: MOTU 896mk3 Hybrid</output_device>
                <gain>1</gain>
                <muted>0</muted>
                <active>1</active>
            </modem>

**Comment by vsonnier** [comment]
@stevefal Thanks you for your report ! After a few tests, I can confirm the duplicate issue was accidentally solved in the commit https://github.com/cjcliffe/CubicSDR/commit/c8cca67fc749242081f4c36b54f5ef40a6125c7e.

**Comment by stevefal** [comment]
Thanks.
