### ISSUE TITLE
Add 'make install' target and dependency checks.

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#54]
- [ ] Add check to ensure wxWidgets >= 3.0
- [x] Add check for any other libs used
- [x] Add 'make install' target
- [x] Add 'make uninstall' target

**Comment by croutonage** [comment]
>>wx-widgets >= 3.0 (it first found my old 2.0 headers wich ended up in some compile errors

Had this issue too.. it needs to be 3.0 , but cmake will accept 2.8, then give compile errors. Perhaps easily fixed by editing the readme file/build instructions

**Comment by camconn** [comment]
On OpenSUSE 13.2 I had to install these packages:
- `bitstream-vera-fonts`
- `automake`
- `autoconf`
- `cmake`
- `wxwidgets-3_0`
- `wxwidgets-3_0-devel
- `rtaudio-devel`
- `rtaudio-debugsource`
- `librtaudio4`
- `librtlsdr0`
- `libosmosdr0`

I had to compile the following packages from scratch, as there were OpenSUSE packages:
- Liquid DSP (https://github.com/jgaeddert/liquid-dsp)

I didn't install these things at all:
- LodePNG (http://lodev.org/lodepng/)
- BMFont (http://www.angelcode.com/products/bmfont/)

**Comment by cjcliffe** [comment]
Can't find a reliable solution to the final wxWidgets issue here; going to handle it with documentation.
