### ISSUE TITLE
Another buffer problem?

### ISSUE THREAD

**Issue by frspin** [cjcliffe/CubicSDR#558]
Listening to VOA Radiogram and receiving a long image in MFSK32 with Fldigi. CubicSDR is tuned to 15670 kHz AM mode. Image have an "out of sync" near the end. It seem a buffer problem in CubicSDR or in SoapySDR.
Some image, received with a Ft897D and Fldigi on an Asus T200TA don't have problem
My setup was a I5 processor, 4 cores, 4 Gb of RAM and Ubuntu 16.04/64 bit
Same image, received on same Linux machine Saturday using an old CiaoRadio H101 SDR don't have problem.
![pic_2017-06-11_195034z](https://user-images.githubusercontent.com/3316507/27014243-26f76202-4ef5-11e7-8ad3-0d9c235943f3.png)

**Comment by k9wkj** [comment]
ill add to this
ive been trying to get consistent JT65 decodes on 6M
and its really seeming like there is jitter trouble
i may have to fire up my desktop and give it whirl
more investigation needed  will report back

**Comment by vsonnier** [comment]
Summer cleanup time !  Any news on the issue @frspin @k9wkj ? 
If not I'll close the issue.

**Comment by vsonnier** [comment]
Closing by lack of activity.
