### ISSUE TITLE
strong tone at LimeSDR & CubicSDR2.2 for USB reception

### ISSUE THREAD

**Issue by mtossain** [cjcliffe/CubicSDR#560]
When selection DX transmission on 20m band, using USB as modem, I get strong carrier tone, which makes hearing conversation impossible. Are there others having the same problem?

**Comment by Dantali0n** [comment]
I have recently received my LimeSDR but the summer has kept me from trying it out. I will try to test if I experience the same problem soon.

**Comment by romeojulietthotel** [comment]
To reproduce the problem without all the details of your setup would be hard or difficult or maybe even impossible.  What antenna port do you have enabled?

**Comment by vsonnier** [comment]
This issue has gone stale, considering the various improvements on the LimeSDR front. Closing.
