### ISSUE TITLE
Low frequency cut

### ISSUE THREAD

**Issue by nrcharles** [cjcliffe/CubicSDR#562]
I can currently tighten up the frequency range on the high side of the modem but not the low side.  This means that for certain narrow signals like CW when they get very tight, they get shifted down on frequency.  Is there a way to add a frequency offset?

**Comment by cjcliffe** [comment]
Yup, this would be handled in #214 with a 'visual notch filter'.  Should be implemented in general for all modes with basic parametric visual controls.
