### ISSUE TITLE
What happened to the AppImage?

### ISSUE THREAD

**Issue by probonopd** [cjcliffe/CubicSDR#570]
It is still missing from the latest release.

**Comment by cjcliffe** [comment]
@probonopd was having issues with build and actual physical build system but will try to get it up to date soon.

**Comment by vsonnier** [comment]
@probonopd An ApplImage have been released for v0.23. I suppose the issues are gone, then.

**Comment by probonopd** [comment]
Cool, thanks, it's working for me.
