### ISSUE TITLE
Frequency offset > 2Ghz

### ISSUE THREAD

**Issue by mcauser** [cjcliffe/CubicSDR#574]
I am using a [RXTXDX.com SUP-2400 downverter](https://rxtxdx.com/CQ-Microwave-Downconverter-p89750717) and would like to shift the display frequency by 2,400,000,000.

It seems the interface limits the frequency offset to +/- 2,000,000,000

**Comment by vsonnier** [comment]
@mcauser Hello, I think I've fixed the issue in the current master. Beware, now offsets are entered in KHz, not Hz as before.
