### ISSUE TITLE
Enhancement to audio recording.

### ISSUE THREAD

**Issue by starvald** [cjcliffe/CubicSDR#587]
been testing out recording and it's working like a champ.

would it be possible to have Cubic make a new file every hour or detect if a file was deleted and start a new one?

hoping to be able to setup a remote pc to constantly record and pull off the days recordings without having to manually double tap 'R' for each modem.

ty.

**Comment by cryoguy** [comment]
How to record an audio file?

**Comment by starvald** [comment]
in the audio_recording branch so it's work in progress, and you'll need to self compile.

**Comment by vsonnier** [comment]
I've just pushed the enhancement to the `audio_recording` branch. Have fun !
