### ISSUE TITLE
Bookmark ranges zoomlevel not working correctly

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#593]
![screen shot 2017-12-26 at 19 17 59](https://user-images.githubusercontent.com/4884243/34362175-af5e5d18-ea71-11e7-905c-6afea906859d.jpg)
In this image you can see that i have created a range from 7MHz-7.04MHz. When i select Go to Range the waterfall display shows me 7.25MHz-7.29MHz.
Can you make CubicSDR make a good effort to select the right range and the best fitting zoom level for that range in the waterfall when i click Go to Range?

**Comment by vsonnier** [comment]
@Toontje Hello ! I think I've found the problem. Could you please test the last master to see if its good for you ? Thanks !

**Comment by Toontje** [comment]
I'd have to set up my build environment again, but yes, i will test it and let you know what i find.

**Comment by cjcliffe** [comment]
@Toontje 0.2.3 build is available on the releases page which now includes this fix.

**Comment by vsonnier** [comment]
Hello @Toontje ! Could you confirm your problem is either fixed or not with v0.23 version ? Thanks !

**Comment by vsonnier** [comment]
Well, no news is good news I suppose, so I'm closing this issue.

**Comment by Toontje** [comment]
Sorry for not responding. No news means no time in my case...
