### ISSUE TITLE
Support of sdrplay RSP1A 

### ISSUE THREAD

**Issue by fe8769a** [cjcliffe/CubicSDR#597]
CubicSDR is the best software to monitor Inmarsat Communications with sdrplay . (easy to use, stability in time) . New SDRplay 1A come with Bias T include . Cubicsdr 0.22 doesn't have this option 

When this option will be available or changing sdrplay dll will offer this ?

Thanks for answer

**Comment by vsonnier** [comment]
@fe8769a The support is already there in the through the SoapySDRplay module. (a kind of driver if you wish).

True CubicSDR 0.22 have been released in May so did not had this update.

Waiting for CubicSDR 0.23 to be released, you have then several options:
-  Re-compile the SoapySDRplay module yourself from the master (see CubicSDR Wiki),
-  If you run Windows 64bit, use the PothosSDR distribution that have an up-to-date CubicSDR build (http://downloads.myriadrf.org/builds/PothosSDR/?C=M;O=D),
-  If you run MacOS you can use the version SDRplay provides (https://www.sdrplay.com/downloads/) which is packaged with a RSP1A compatible module.
