### ISSUE TITLE
CubicSDR crash On LXUbuntu 16.04 LTS x64

### ISSUE THREAD

**Issue by ClaudeMa** [cjcliffe/CubicSDR#599]
CubicSdr crash on XUbuntu 16.04 LTS

System:
CPU Intel(R) Core(TM)2 Duo CPU     E6750  @ 2.66GHz
RAM 4096 Mo

radio device:
SDRPlay rsp1A
SDR-RTL usb dongle

follow output of gdb (stacktrace is empty after crash.

> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
> Loading:: configuration file '/home/claude/.CubicSDR/config.xml'
> [New Thread 0x7fffec148700 (LWP 26055)]
> [New Thread 0x7fffeb947700 (LWP 26056)]
> [New Thread 0x7fffeb146700 (LWP 26057)]
> [New Thread 0x7fffe0833700 (LWP 26058)]
> [New Thread 0x7fffdfc75700 (LWP 26059)]
> [New Thread 0x7fffded67700 (LWP 26060)]
> [New Thread 0x7fffde566700 (LWP 26061)]
> 
> Audio Device #0 PulseAudio
> 	Default Output? Yes
> 	Default Input? Yes
> 	Input channels: 2
> 	Output channels: 2
> 	Duplex channels: 2
> 	Native formats:
> 		16-bit signed integer.
> 		32-bit signed integer.
> 		32-bit float normalized between plus/minus 1.0.
> 	Supported sample rates:
> 		8000hz
> 		16000hz
> 		22050hz
> 		32000hz
> 		44100hz
> 		48000hz
> 		96000hz
> 
> Available vertical sync SwapInterval functions: 
> 	glxSwapIntervalEXT: No
> 	DRI2SwapInterval: No
> 	glxSwapIntervalMESA: No
> 	glxSwapIntervalSGI: No
> No vertical sync swap interval functions available.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono12_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono16_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono18_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono24_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono27_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono32_0.png', parsed 255 characters.
> Loaded font 'Bitstream Vera Sans Mono' from '/usr/local/share/cubicsdr/fonts/vera_sans_mono36_0.png', parsed 255 characters.
> [New Thread 0x7fffdcf5b700 (LWP 26062)]
> SDR enumerator starting.
> SoapySDR init..
> 	API Version: v0.7.0
> 	ABI Version: v0.6
> 	Install root: /usr/local
> 	Loading modules... 
> 	Available factories...null, remote, rtlsdr, sdrplay
> [New Thread 0x7fffcde0a700 (LWP 26063)]
> [New Thread 0x7fffcd609700 (LWP 26064)]
> [New Thread 0x7fffcce08700 (LWP 26065)]
> [Thread 0x7fffcce08700 (LWP 26065) exited]
> [New Thread 0x7fffcce08700 (LWP 26066)]
> [Thread 0x7fffcce08700 (LWP 26066) exited]
> [New Thread 0x7fffcce08700 (LWP 26067)]
> [Thread 0x7fffcce08700 (LWP 26067) exited]
> [New Thread 0x7fffcce08700 (LWP 26068)]
> Detached kernel driver
> Found Rafael Micro R820T tuner
> Reattached kernel driver
> [Thread 0x7fffcce08700 (LWP 26068) exited]
> [New Thread 0x7fffcce08700 (LWP 26096)]
> [Thread 0x7fffcce08700 (LWP 26096) exited]
> [New Thread 0x7fffcce08700 (LWP 26097)]
>   available = Yes
>   driver = rtlsdr
>   label = Generic RTL2832U OEM :: 00000001
>   manufacturer = Realtek
>   product = RTL2838UHIDIR
>   rtl = 0
>   serial = 00000001
>   tuner = Rafael Micro R820T
> Make device 0
> [New Thread 0x7fffcce08700 (LWP 26098)]
> [Thread 0x7fffcce08700 (LWP 26097) exited]
> [Thread 0x7fffcce08700 (LWP 26098) exited]
> [New Thread 0x7fffcce08700 (LWP 26099)]
> Detached kernel driver
> Found Rafael Micro R820T tuner
>   origin=https://github.com/pothosware/SoapyRTLSDR
>   rtl=0
> Reattached kernel driver
> [Thread 0x7fffcce08700 (LWP 26099) exited]
> 
>   driver = sdrplay
>   label = SDRplay Dev0 RSP1A 255 1716004A93
> Make device 1
> [New Thread 0x7fffcce08700 (LWP 26126)]
> [New Thread 0x7fffcce08700 (LWP 26127)]
> [Thread 0x7fffcce08700 (LWP 26126) exited]
> [New Thread 0x7fffcce08700 (LWP 26128)]
> [Thread 0x7fffcce08700 (LWP 26127) exited]
> [New Thread 0x7fffc3fff700 (LWP 26129)]
>   mir_sdr_api_version=2,110000
>   mir_sdr_hw_version=255
> [Thread 0x7fffc3fff700 (LWP 26129) exited]
> 
> [Thread 0x7fffcce08700 (LWP 26128) exited]
> 
> Reporting enumeration complete.
> SDR enumerator done.
> [Thread 0x7fffdcf5b700 (LWP 26062) exited]
> [New Thread 0x7fffcce08700 (LWP 26135)]
> [Thread 0x7fffcce08700 (LWP 26135) exited]
> [New Thread 0x7fffcce08700 (LWP 26136)]
> [Thread 0x7fffcce08700 (LWP 26136) exited]
> [New Thread 0x7fffcce08700 (LWP 26137)]
> [New Thread 0x7fffc37fe700 (LWP 26138)]
> [New Thread 0x7fffc2ffd700 (LWP 26140)]
> SDR thread starting.
> device init()
> [INFO] Using format CF32.
> Device Stream MTU: 65536
> [New Thread 0x7fffc27fc700 (LWP 26141)]
> starting readLoop()
> [New Thread 0x7fffc1ffb700 (LWP 26142)]
> [New Thread 0x7fffc17fa700 (LWP 26143)]
> [New Thread 0x7fffc0ff9700 (LWP 26144)]
> [New Thread 0x7fffaffff700 (LWP 26145)]
> [New Thread 0x7fffaf7fe700 (LWP 26146)]
> [New Thread 0x7fffaeffd700 (LWP 26147)]
> [New Thread 0x7fffae7fc700 (LWP 26148)]
> 
> Audio Device #0 PulseAudio
> 	Default Output? Yes
> 	Default Input? Yes
> 	Input channels: 2
> 	Output channels: 2
> 	Duplex channels: 2
> 	Native formats:
> 		16-bit signed integer.
> 		32-bit signed integer.
> 		32-bit float normalized between plus/minus 1.0.
> 	Supported sample rates:
> 		8000hz
> 		16000hz
> 		22050hz
> 		32000hz
> 		44100hz
> 		48000hz
> 		96000hz
> 
> DemodulatorThread::run() cannot push ati into audioOutputQueue, is full !
> The program 'CubicSDR' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'BadDrawable (invalid Pixmap or Window parameter)'.
>   (Details: serial 4765235 error_code 9 request_code 154 minor_code 8)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the --sync command line
>    option to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> [Thread 0x7fffcde0a700 (LWP 26063) exited]
> [Thread 0x7fffcd609700 (LWP 26064) exited]
> [Thread 0x7fffae7fc700 (LWP 26148) exited]
> [Thread 0x7fffaeffd700 (LWP 26147) exited]
> [Thread 0x7fffaf7fe700 (LWP 26146) exited]
> [Thread 0x7fffaffff700 (LWP 26145) exited]
> [Thread 0x7fffc0ff9700 (LWP 26144) exited]
> [Thread 0x7fffc17fa700 (LWP 26143) exited]
> [Thread 0x7fffc1ffb700 (LWP 26142) exited]
> [Thread 0x7fffc27fc700 (LWP 26141) exited]
> [Thread 0x7fffc2ffd700 (LWP 26140) exited]
> [Thread 0x7fffc37fe700 (LWP 26138) exited]
> [Thread 0x7fffcce08700 (LWP 26137) exited]
> [Thread 0x7fffde566700 (LWP 26061) exited]
> [Thread 0x7fffded67700 (LWP 26060) exited]
> [Thread 0x7fffe0833700 (LWP 26058) exited]
> [Thread 0x7fffeb146700 (LWP 26057) exited]
> [Thread 0x7fffeb947700 (LWP 26056) exited]
> [Thread 0x7fffec148700 (LWP 26055) exited]
> [Thread 0x7ffff7f29e80 (LWP 26051) exited]
> [Inferior 1 (process 26051) exited with code 01]
>

**Comment by ClaudeMa** [comment]
seems occurs when the screen saver activates

**Comment by vsonnier** [comment]
@ClaudeMa CubicSDR is an OpenGL application. Does your screen saver an OpenGL app as well ? 
Maybe there is some kind of exclusive access to the GPU.

In this case you may have to disable your screen saver.

**Comment by vsonnier** [comment]
@ClaudeMa Hello ! Any news on your screen saver issues ?

**Comment by vsonnier** [comment]
Closed by lack of constructive input. (I'm in a Cleanup Time mood.)
