### ISSUE TITLE
audio_recording branch with no recording function in Arch Linux

### ISSUE THREAD

**Issue by cryoguy** [cjcliffe/CubicSDR#600]
I git-cloned and compiled the audio_recording branch in my Arch linux system.  I do not see any audio recording function, such as path setting under File menu etc; there is no difference to the master branch.  Any thoughts or suggestions?

**Comment by starvald** [comment]
hmm arch user here too, i compiled from aur but changed the source line to
`source=(cubicsdr-git::"git+https://github.com/cjcliffe/cubicsdr.git#branch=audio_recording")`

**Comment by cjcliffe** [comment]
@cryoguy the recording start / stop button will also appear in the left-side bookmark list when selecting an active demodulator.

**Comment by parkerlreed** [comment]
Also just to note, it's in master now. :) (So the PKGBUILD fix isn't needed anymore)

**Comment by vsonnier** [comment]
Binaries v0.23 with this feature are now released for every pltaform, so this can be closed.
