### ISSUE TITLE
Wrong frequencies displayed in CubicSDR

### ISSUE THREAD

**Issue by ClaudeMa** [cjcliffe/CubicSDR#604]
After a while of searching station to listen i found that displayed frequencies is not the received frequencies.
At beginning, frequencies was correct.

Frequencies displayed is 6898 khz for a station transmitting on 7310 khz (Verified on my shortwave receiver)
top waterfall and bottom waterfall are not sync (see screenshot)
stopping CubicSR and lauching Gqrx station is on the good frenquencies. (7310 khz)
stopping Gqrx and restating CubicSDR station is always found on 6898 khz

Frequencies offset is set at 0khz and no ppm set

Cubic SDR last version from git
SDRPLAY RSP1A
Linux Xubuntu 16.04 LTS

![capture d ecran_2018-01-22_22-39-39](https://user-images.githubusercontent.com/2773730/35246603-8fbe4340-ffc7-11e7-98b1-18ac8d63e652.png)

**Comment by vsonnier** [comment]
@ClaudeMa you are experiencing #590, or #338 about the need of filtering on the main waterfall, which are a long, but interesting story implying DSP matters.
I'm closing this issue then, please continue the discussion at #590 if you wish.
