### ISSUE TITLE
Rig Control Drop-down missing in Linux Mint 18.1 Cinnamon 32bit

### ISSUE THREAD

**Issue by K6ETA** [cjcliffe/CubicSDR#606]
The Rig Control menu is not appearing after manually installing the 0.2.3 TAR - the rest of the program is working flawlessly with SDRPlay. Great software - THANK YOU.

**Comment by vsonnier** [comment]
@K6ETA You need to build CubicSDR with HAMLIB enabled, i.e having I think `hamlib-utils` and `libhamlib-dev` packages and such installed, and building with CMake adding `-DUSE_HAMLIB=1`.
Alternatively, why not using the ApplImage ?

**Comment by vsonnier** [comment]
@K6ETA Ping ! Any news on your issue ?

**Comment by K6ETA** [comment]
Oh, hi Vincent,

Yes I recompiled the software using the mentioned commands and bingo! Rig control appeared and works perfectly with my IC-7300! Well, almost perfectly at least. Occasionally it doesn't fully sync the frequency, but it works 95% of the time!

I must say, CubicSDR is a fine bit of coding! Many thanks!

Steve K6ETA



------ Original Message ------

**Comment by vsonnier** [comment]
@K6ETA Thats great ! Have fun with CubicSDR !
