### ISSUE TITLE
undefined symbol: hb_font_funcs_set_variation_glyph_func

### ISSUE THREAD

**Issue by jtalics** [cjcliffe/CubicSDR#613]
user1@perovskite:~/Downloads$ ./CubicSDR-0.2.3-x86_64.AppImage 
./CubicSDR-0.2.3-x86_64.AppImage: symbol lookup error: /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0: undefined symbol: hb_font_funcs_set_variation_glyph_func

**Comment by parkerlreed** [comment]
See also

https://github.com/cjcliffe/CubicSDR/issues/611

**Comment by vsonnier** [comment]
@jtalics @parkerlreed I'm closing this issue, please continue the discussion in #611. Thanks !
