### ISSUE TITLE
Spyserver

### ISSUE THREAD

**Issue by ifuchs** [cjcliffe/CubicSDR#625]
Is there currently a way to use CubicSDR with a Spyserver? Would like to run a RTL-SDR on RPi and use CubicSDR remotely.

**Comment by guruofquality** [comment]
I would recommend to install SoapyRemote: https://github.com/pothosware/SoapyRemote/wiki

But in regards to the spyserver protocol specifically, any volunteers to make a SoapySpyClient or SoapySpyServer (I guess in this case client)? more info https://github.com/pothosware/SoapySDR/issues/156 :-)

**Comment by ifuchs** [comment]
Thanks for the quick reply. I am somewhat new to SDR. So functionally, SoapyRemote is to CubicSDR and Gqrx what Spyserver is to SDR#?

**Comment by mmgarland3** [comment]
Yes, except the SoapySDR library is open and supports dozens of SDRs, and
numerous applications use the SoapySDR client driver.

SDR# and Spyserver are closed implementation owned by Airspy and actively
lock-out support for other products.
