### ISSUE TITLE
Bug: Zoom won't hold

### ISSUE THREAD

**Issue by a-raccoon** [cjcliffe/CubicSDR#630]
The feature 'Right drag or wheel to Zoom' doesn't hold still and fights against the user to reset to the unzoomed Sample Rate width.

Feature suggest:  Also allow Ctrl + and Ctrl - to also set the zoom depth, with Ctrl 0 to reset.  Show the zoom width value (ie, Sample width), and allow arbitrary zoom value input.

**Comment by vsonnier** [comment]
@a-raccoon I fixed the inconsistencies in both zoom kinds (bandwidth on one side, vertical scale on the other), see the commit in master:
- Right-drag now does the same thing on both Spectrum and Waterfall, i.e change and hold vertical scale,
- So Right-drag on Waterfall no longer zoom bandwidth, there are already much more practical ways to do it (up/down, wheel)
- Right-click to reset vertical scale stays only enabled on Spectrum.
- Adapted mouse cursors to reflect the possible moves on Spectrum and Waterfall.
- Fixed and updated both Waterfall and Spectrum tooltips to describe those features.
