### ISSUE TITLE
Feature: Select Audio Device

### ISSUE THREAD

**Issue by a-raccoon** [cjcliffe/CubicSDR#632]
CubicSDR lets you specify the Audio Sample Rate for each of the Playback Audio Devices (output) your system supports, but it does not let you actually specify which Playback Audio Device you wish to use.

Suggestion: Let the user specify which audio device to use.

Currently: CubicSDR only uses whichever device you specify as the System Default Playback Device.  This isn't very useful.  In the Windows RTL-SDR world, it's necessary to pipe audio from one program to another program for things like digital decoding (ie, DSD+ for D-STAR, P25, DMR, etc).

**Comment by vsonnier** [comment]
@a-raccoon What you are looking for is already there:
![cropimage](https://user-images.githubusercontent.com/5152742/37298593-0343f40c-2621-11e8-96c4-a29997253273.png)

You can choose here an output device for a particular modem, and make another choice for another modem. This choice is saved in a session file per-modem and is properly restored at session reload.

**Comment by a-raccoon** [comment]
Thank you.  I searched the documentation did not find this with keyword `device`.  But now I see it under `audio out`.  http://cubicsdr.readthedocs.io/en/latest/application-window.html?highlight=audio

**Comment by dslotter** [comment]
I see where I should be able to select audio devices under the Modem, but as you can see in this attached screen capture, I have four audio out devices, but only "PulseAudio" shows up. This is under Ubuntu Linux 16.04. Does CubicSDR v0.2.5 under Linux not have the capability to send to a particular audio output device? I read the documentation and couldn't find any help on this. Please advise, and thanks.

![image](https://user-images.githubusercontent.com/6873871/68040539-e5197e00-fca4-11e9-8ce9-0bc1e4856d8b.png)

**Comment by dslotter** [comment]
I see where I should be able to select audio devices under the Modem, but as you can see in this attached screen capture, I have four audio out devices, but only "PulseAudio" shows up. This is under Ubuntu Linux 16.04. Does CubicSDR v0.2.5 under Linux not have the capability to send to a particular audio output device? I read the documentation and couldn't find any help on this. Please advise, and thanks.

![image](https://user-images.githubusercontent.com/6873871/68040769-640eb680-fca5-11e9-9115-49733014099b.png)

**Comment by adeptex** [comment]
You need to install rtaudio from http://github.com/thestk/rtaudio/
