### ISSUE TITLE
Issues with wxWidgets v3.11

### ISSUE THREAD

**Issue by vsonnier** [cjcliffe/CubicSDR#635]
This issue gathers the various problems encountered during the migration to wxWidgets v3.11: (checked when solved)
- [X] @Magalex-2x14 : OS X 10.13.3, wxWidgets 3.1.1 - missing the labels on the buttons below the bookmarks. Same commit but with wxWidgets 3.1.0 - all OK.
- [X] @parkerlreed : Syntax incompatible with wxWidgets v3.04
- [X] @Magalex-2x14 : OS X 10.13.3, wxWidgets 3.1.1 : improper BookmarkView refresh, forced by re-focus.
- [X] Windows 10 : very slow, blocking refresh of `BookmarkView`.
- [X]  Windows 10: Buttons labels are invisible.

**Comment by vsonnier** [comment]
Solutions  / Suggestions:
- @parkerlreed : The minimum requirement is wxWidgets v3.1, so you have to compile it from scratch, see the Wiki. The previous wxWidgets v3.0x syntax compatibility was pure luck, and had to end one day.
- @Magalex-2x14 : Same story here on Windows 10. The custom text button color given from the current theme doesn't work well. I see if I can fix it, or else leave the default color would do.

**Comment by Magalex-2x14** [comment]
@vsonnier I also noticed that with 3.1.1 when new modem is added, corresponding buttons do not appear (bookmark, start recording, remove active). They appears only after "refocusing" -  I have to change focus to the bookmarks or ranges, then back to the modems.

**Comment by parkerlreed** [comment]
(And by a long compile time it took nearly 8 minutes on a 4 core/10 thread machine running make at -j10. A bit lengthy and would only be longer for somebody running lower hardware)

**Comment by vsonnier** [comment]
@parkerlreed It is quite long indeed, but you have only to do it every 2 years given the super-slow wxWidgets release schedule.

I've push 1 commit on the master branch, which reverts most of the `BookmarkView` modifications... The control refresh is really slow, but at least it is correct.

**Comment by MicroJoe** [comment]
v3.1.x is shipped as binary release for Debian, Ubuntu and Fedora : http://codelite.org/LiteEditor/WxWidgets31Binaries

**Comment by parkerlreed** [comment]
Ahh thanks. Wonder why all the official repos seem to be behind (I guess due to compat with older software)

**Comment by vsonnier** [comment]
Hello @Magalex-2x14, @parkerlreed and all. I've commited some changes on the master, which I believe fixes the following points:
- Invisible button labels (Windows, OS-X). I forced them to white instead of using the actual theme color. 
- Slow `BookmarkView` refresh (Windows). Turns out the UI events were calling themselves back and forth.
- (Maybe ?) Improper control refresh (OS X). I've restored most of the old `BookmarkView` control logic, plus added other fixes.  

Please tell me how it goes for you.

**Comment by Magalex-2x14** [comment]
OS X. Invisible button labels are still invisible (maybe labels must be forced to black? White labels becomes visible when the button is pressed...) In the rest everything seems OK.
![cubicsdr v0 2 3 www cubicsdr com 2018-03-24 19-01-04](https://user-images.githubusercontent.com/4982025/37866029-dadfcf94-2f95-11e8-8326-ef7670726156.png)

**Comment by vsonnier** [comment]
Thanks @Magalex-2x14. Funny thing, colors are exactly inverted on Windows 10:
![cropimage](https://user-images.githubusercontent.com/5152742/37866328-872c72d2-2f89-11e8-85cb-a2914b7cdb67.png)

So finally in the last commit I removed the buttons custom colors. Less sexy, but should be OK on all platforms.
What about your UI refreshing problems ?

**Comment by vsonnier** [comment]
Great ! Thanks for your input, I think we can close this issue then.
