### ISSUE TITLE
error: ‘wxGLContextAttrs’ has not been declared

### ISSUE THREAD

**Issue by bdn76** [cjcliffe/CubicSDR#641]
Debian testing x64

[  1%] Building CXX object CMakeFiles/CubicSDR.dir/external/rtaudio/RtAudio.cpp.o
[  3%] Building CXX object CMakeFiles/CubicSDR.dir/src/AppConfig.cpp.o
[  3%] Building CXX object CMakeFiles/CubicSDR.dir/src/AppFrame.cpp.o
[  4%] Building CXX object CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o
[  5%] Building CXX object CMakeFiles/CubicSDR.dir/src/FrequencyDialog.cpp.o
In file included from /home/dima/src/CubicSDR/src/CubicSDR.h:13:0,
                 from /home/dima/src/CubicSDR/src/AppConfig.cpp:5:
/home/dima/src/CubicSDR/src/visual/PrimaryGLContext.h:19:70: error: ‘wxGLContextAttrs’ has not been declared
     PrimaryGLContext(wxGLCanvas *canvas, wxGLContext *sharedContext, wxGLContextAttrs* ctxAttrs);
                                                                      ^~~~~~~~~~~~~~~~
In file included from /home/dima/src/CubicSDR/src/visual/ScopeCanvas.h:13:0,
                 from /home/dima/src/CubicSDR/src/AppFrame.h:15,
                 from /home/dima/src/CubicSDR/src/CubicSDR.h:22,
                 from /home/dima/src/CubicSDR/src/AppConfig.cpp:5:
/home/dima/src/CubicSDR/src/visual/ScopeContext.h:15:67: error: ‘wxGLContextAttrs’ has not been declared
     ScopeContext(ScopeCanvas *canvas, wxGLContext *sharedContext, wxGLContextAttrs *ctxAttrs);
                                                                   ^~~~~~~~~~~~~~~~
In file included from /home/dima/src/CubicSDR/src/visual/ScopeCanvas.h:17:0,
                 from /home/dima/src/CubicSDR/src/AppFrame.h:15,
                 from /home/dima/src/CubicSDR/src/CubicSDR.h:22,
                 from /home/dima/src/CubicSDR/src/AppConfig.cpp:5:
/home/dima/src/CubicSDR/src/visual/InteractiveCanvas.h:15:47: error: ‘wxGLAttributes’ does not name a type; did you mean ‘TiXmlAttribute’?
etc

> 
$ dpkg -l | grep wx
ii  libgnuradio-wxgui3.7.11:amd64             3.7.11-8                  amd64                     gnuradio wxgui functions
ii  libwxbase3.0-0v5:amd64                    3.0.4+dfsg-3              amd64                     wxBase library (runtime) - non-GUI support classes of wxWidgets toolkit
ii  libwxbase3.0-dev                          3.0.4+dfsg-3              amd64                     wxBase library (development) - non-GUI support classes of wxWidgets toolkit
ii  libwxgtk3.0-0v5:amd64                     3.0.4+dfsg-3              amd64                     wxWidgets Cross-platform C++ GUI toolkit (GTK+ runtime)
ii  libwxgtk3.0-dev                           3.0.4+dfsg-3              amd64                     wxWidgets Cross-platform C++ GUI toolkit (GTK+ development)
ii  python-wxgtk3.0                           3.0.2.0+dfsg-6            amd64                     Python interface to the wxWidgets Cross-platform C++ GUI toolkit
ii  python-wxversion                          3.0.2.0+dfsg-6            all                       API for selecting the wxPython version to use
ii  wx-common                                 3.0.4+dfsg-3              amd64                     wxWidgets Cross-platform C++ GUI toolkit (common support files)
ii  wx3.0-headers                             3.0.4+dfsg-3              all                       wxWidgets Cross-platform C++ GUI toolkit (header files)
$

**Comment by vsonnier** [comment]
This is a dupplicate of #635: the minimum wxWidgets requirement version is v3.1x, the v3.0x branch is no longer compatible.
