### ISSUE TITLE
Win32 0.2.3 build not working with SDRPlay remotely

### ISSUE THREAD

**Issue by ve9gj** [cjcliffe/CubicSDR#647]
I have SoapyServer running on a pi with a SDRPlay. CubicSDR linux x64 and Win64 will find the SoapyRemote SDRPlay on the LAN and works great.  I also have a Windows tablet running 32 bit Win10 and it will not find the remote SDRPlay at all.  Will not work even if I enter the remote IP:port manually.  Is Win32 expected to work with a SoapyRemote SDRPlay or is something missing?
73 and thanks for the great software!!
Glenn VE9GJ

**Comment by SDRplay** [comment]
I wasn't sure if you had the pre-built binaries or built it yourself. Have you tried the 32bit install on the 64bit machine? I have both installed and I'm sure they both work. I'm not at my desk to be able to re-test. Travelling for next couple of days, but will try it out if no one else has by then.

**Comment by ve9gj** [comment]
Good idea, never thought about that.  So I uninstalled the 64bit on my Win7 box and installed the 32 bit and it works great.  So that proves that the 32bit version does indeed work.  There is just something strange going on with my 32bit Win10 tablet. https://www.irulu.com/2-in-1-tablet-quad-core-6000mah-w20.html
Sorry for the noise!
73
VE9GJ
