### ISSUE TITLE
Mint 18.3 - Gdk-ERROR ** ---- This probably reflects a bug in the program

### ISSUE THREAD

**Issue by JanuszWaw** [cjcliffe/CubicSDR#653]
After compiling (from src) under Mint 18.3 Cinnamon 64bit (Linux PC-IRX 4.13.0-41-generic #46~16.04.1-Ubuntu SMP Thu May 3 10:06:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux) and trying to start CubicSDR 0.2.4 I get a message: (the previous version 0.2.3, compiled in the same way works without a problem)
--------
$ ./CubicSDR 
Loading:: configuration file '/<...>/.CubicSDR/config.xml'
Loaded 217 rig models via hamlib.
(CubicSDR:8922): Gdk-ERROR **: The program 'CubicSDR' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 228 error_code 2 request_code 154 (GLX) minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Pułapka debuggera/breakpoint
S

**Comment by vsonnier** [comment]
@JanuszWaw Since #569 has already a discussion thread going on, please continue there, thanks!
