### ISSUE TITLE
CubicSDR not able to read from RTL-SDR

### ISSUE THREAD

**Issue by soichih** [cjcliffe/CubicSDR#660]
CubicSDR is detecting my RTL-SDR running on Ubuntu 16.04, but it's not able to read data from it.

```
Reporting enumeration complete.
SDR enumerator done.
usb_open error -1
SDR thread starting.
device init()
[INFO] Using format CF32.
Stream MTU: 131072
starting readLoop()
SDRThread::readStream(): read failed with code: -1
SDRThread::readStream(): read failed with code: -1
SDRThread::readStream(): read failed with code: -1
SDRThread::readStream(): read failed with code: -1
SDRThread::readStream(): read failed with code: -1
...
```

As instructed by the README, I've run the connect command but it's failing

```
sudo snap connect cubicsdr-master-casept:raw-usb core:raw-usb
error: snap "cubicsdr-master-casept" has no plug named "raw-usb"
```

I've also tried following instead

```
sudo snap connect cubicsdr-casept:raw-usb core:raw-usb
```
which worked, but I am still seeing the same error message from CubicSDR.

**Comment by vsonnier** [comment]
Stale issue, package usb-related installation problems, nothing to do with CubicSDR itself. Let this issue die a peacefull death. (Spring cleanup time)
