### ISSUE TITLE
Solved: CubicSDR not starting after upgrade Arch Linux

### ISSUE THREAD

**Issue by Terminalator** [cjcliffe/CubicSDR#662]
After updating I am now getting this error:
```
[john@jupiter64 ~]$ cubicsdr 
Fatal Error: Mismatch between the program and library build versions detected.
The library used 3.1.1 (wchar_t,compiler with C++ ABI 1011,wx containers,compatible with 3.0),
and your program used 3.1.1 (wchar_t,compiler with C++ ABI 1012,wx containers,compatible with 3.0).
Aborted (core dumped)
```

Strange thing is, the AUR shows this: Package Details: cubicsdr-git 2:r1486.490f72c-1

but I see this: 

```
[john@jupiter64 ~]$ yaourt -Q cubicsdr-git
local/cubicsdr-git 2:r1515.2f84df3-1
```

I've tried removing and re-installing but still the same.

Any help? Thanks``

**Comment by Terminalator** [comment]
Any idea how I can downgrade CubicSDR to a previous version?

**Comment by Terminalator** [comment]
After trying several times I got this to build OK.

**Comment by vsonnier** [comment]
Great ! Let's continue discussion on #663 then :)

**Comment by cyberdavev** [comment]
I have exactly the same problem. How did you manage to fix this?

**Comment by Terminalator** [comment]
I don't honestly know @cyberdavev . I just rebuilt everything (using yaourt) including:

aur/wxgtk-common-dev 3.1.1-1 [installed] (3) (0.31)
aur/wxgtk2-dev 3.1.1-1 [installed] (3) (0.31)
aur/wxgtk2.8 2.8.12.1-6 [installed] (Out of Date) (27) (0.46)
aur/wxgtk3-dev 3.1.1-1 [installed] (3) (0.31)
