### ISSUE TITLE
Couln't create Opengl context

### ISSUE THREAD

**Issue by ClaudeMa** [cjcliffe/CubicSDR#664]
hi 

I have build Cubicsdr on 3 linux platform Debian 9, Ubuntu 18.04 and Fedora 97
followings instructions here
https://github.com/cjcliffe/CubicSDR/wiki/Build-Linux 
because i need sdrplay RSP1A support.
On all platform, when i start CubicSdr i receive "Couln't create Opengl context".
If i download an appimage when starting, no message but sdrplay not detected.
Is there something wrong or missed in the wiki page?
thanks
Claude

**Comment by MrJBSwe** [comment]
I have the same problem on Ubuntu studio 18.04
( but CubicSDR will run after the error, without opengl ? )

observations
 opengl samples for wxwidgets   cube,penguin etc  -  works 
 CubicSDR-0.2.4-x86_64.AppImage - work without error 
 running without nvidia drivers work ( without opengl I guess ..slow )
 Ogre3D demos works

**Comment by cjcliffe** [comment]
@ClaudeMa @MrJBSwe I think this is related to wxWidgets 3.1.0; I'll update the instructions but basically just replace wxWidgets-3.1.0 with wxWidgets-3.1.1 in the guide.

**Comment by ClaudeMa** [comment]
Many Thanks for reply Charles
Now work with wxWidget 3.1.1
No error message and button are now "readable"
