### ISSUE TITLE
Use system fonts instead of self-packaged?

### ISSUE THREAD

**Issue by mdomsch** [cjcliffe/CubicSDR#669]
Just you have built CubicSDR to use system-provided libraries whenever possible, can you please provide a way to discover and use system-provided Bitstream Vera fonts (e.g. bitstream-vera-sans-mono-fonts package in Fedora) ?

**Comment by vsonnier** [comment]
@mdomsch Hello ! CubicSDR doesn't actually use  Bitstream Vera fonts directly, but a bitmaped version of them that has been preprocessed by the tool [BMPFont](http://www.angelcode.com/products/bmfont/). Besides, the font names are hardcoded in the source code, so... CubicSDR can't use external fonts, no.
