### ISSUE TITLE
Need to add step to "Build static wxWidgets" instructions

### ISSUE THREAD

**Issue by ramseyrt** [cjcliffe/CubicSDR#671]
Hello,

While attempting to install wxWidgets on my Raspberry Pi 3 running Raspbian (current build as of 7 Aug 2018), I received the following error:

./configure --with-opengl --disable-shared --enable-monolithic --with-libjpeg --with-libtiff --with-libpng --with-zlib --disable-sdltest --enable-unicode --enable-display --enable-propgrid --disable-webkit --disable-webview --disable-webviewwebkit --prefix=`echo ~/Develop/wxWidgets-staticlib` CXXFLAGS="-std=c++0x"

...lots of output...

configure: error: OpenGL libraries not available

I had to install freeglut3-dev to get the ./configure to complete properly.

"Build static wxWidgets:"
https://github.com/cjcliffe/CubicSDR/wiki/Build-Linux#build-static-wxwidgets

FYI,

Rob Ramsey

**Comment by cjcliffe** [comment]
@ramseyrt thanks for the info; I've updated the page to include it as a default requirement.
