### ISSUE TITLE
Please support wxWidgets 3.0 also

### ISSUE THREAD

**Issue by swt2c** [cjcliffe/CubicSDR#672]
I noticed in e46d7f9 that you switched to wxWidgets 3.1 APIs.  It is fine to use these APIs but unfortunately most Linux distributions have wxWidgets 3.0 and won't update to 3.1 as it is a development release (with unstable API/ABI).  It would be appreciated if you could add back support for 3.0 (keeping 3.1 support as well is fine).

**Comment by parkerlreed** [comment]
They can't/won't. It's not feasible to support both versions. Also please search past issues. 

https://github.com/cjcliffe/CubicSDR/issues/635
