### ISSUE TITLE
fixed error DemodulatorInstance.cpp

### ISSUE THREAD

**Issue by GkvJeep** [cjcliffe/CubicSDR#675]
DemodulatorInstance.cpp

64 pipeIQInputData = std::make_shared<DemodulatorThreadInputQueue>();
65 pipeIQInputData->set_max_num_items(100);
67 pipeIQDemodData = std::make_shared< DemodulatorThreadPostInputQueue>();
68 pipeIQInputData->set_max_num_items(100);
line 68 repeat line 65
change line 68 to 
pipeIQDemodData->set_max_num_items(100);

**Comment by vsonnier** [comment]
Thanks @GkvJeep , this is indeed a cut-n-paste error. I've also tuned the AudioThread queue size as well.
