### ISSUE TITLE
fixed errors

### ISSUE THREAD

**Issue by GkvJeep** [cjcliffe/CubicSDR#678]
SDRPostThread.cpp
 31  dcFilter = iirfilt_crcf_create_dc_blocker(0.0005f);

Call create,not DESTROY.

add line 36
 // destroy filter object
    iirfilt_crcf_destroy(dcFilter);

**Comment by vsonnier** [comment]
We can indeed add a `iirfilt_crcf_destroy(dcFilter);` in the `SDRPostThread` destructor for cleanliness. Although not doint it would not be problematic, since `SDRPostThread` has application lifetime.
