### ISSUE TITLE
No time anymore? Moved on to other projects?

### ISSUE THREAD

**Issue by Toontje** [cjcliffe/CubicSDR#680]
![screen shot 2018-09-07 at 20 12 17](https://user-images.githubusercontent.com/4884243/45235828-657b6380-b2da-11e8-9470-2e3f249b883c.jpg)

**Comment by cjcliffe** [comment]
@Toontje not moved on; this is still my primary focus for open source development; I've just been busy with non open-source and real-world issues, tasks and projects.
