### ISSUE TITLE
error ?

### ISSUE THREAD

**Issue by GkvJeep** [cjcliffe/CubicSDR#689]
setAudioSampleRate  call   setSampleRate(sampleRate) 

void DemodulatorInstance::setAudioSampleRate(int sampleRate) {
    demodulatorPreThread->setSampleRate(sampleRate);
}

change ?!!!!!

void DemodulatorInstance::setAudioSampleRate(int sampleRate) {
    demodulatorPreThread->setAudioSampleRate(sampleRate);
}

**Comment by vsonnier** [comment]
Oups indeed @GkvJeep, thanks for the fix ! By luck, the `DemodulatorPreThread` did not trust the wrong provided sample rate and actually re-read it from `DemodulatorInstance` itself. 

Have fun with CubicSDR !
