### ISSUE TITLE
LimeSDR Mini and CubicSDR

### ISSUE THREAD

**Issue by righthalfplane** [cjcliffe/CubicSDR#692]
Good News - LimeSDR Mini works with CubicSDR-0.2.5-Darwin.dmg on MacOS Sierra - 
                    - it is missing some features, but that is libLimeSuite's fault.

Bad News  - CubicSDR-0.2.5-x86_64.AppImage crashed with the LimeSDR Mini on ubuntu 16.04

Good News - CubicSDR-0.2.3 works with  LimeSDR Mini after using after installing LimeSuite-master.zip on ubuntu 16.04

Good News - CubicSDR-0.2.4 works with LimeSDR Mini after using after installing LimeSuite-master.zip on on MacOS Sierra and MacOS High Sierra

A Side Note - gqrx works with LimeSDR Mini on ubuntu 16.04 and has more features.

**Comment by righthalfplane** [comment]
LimeSDR Mini works with CubicSDR-0.2.4-win64.exe on windows 7 after installing the driver - https://wiki.myriadrf.org/LimeSDR-Mini_driver_installation. This installation process did not work for me and I had to start at "Printers and Devices" and do a install from disk for the LimeSDR Mini. The only problem with CubicSDR-0.2.4-win64 seem to be it would not turn anything below about 30 MHZ. The LimeSDR Mini is supposed to go down to 10MHZ.

**Comment by righthalfplane** [comment]
CubicSDR-0.2.5-Darwin.dmg has two problems on MacOS Sierra. It generates out of range error messages for any frequency below about 30 MHZ and it gives warnings about usb pipes not being closed.  I have another programs that uses SoapySDR and it has no problem tuning below 30 MHZ with no problem, but it does give the warning message  "libusb: warning [libusb_exit] application left some devices open"

*******************
CubicSDR  output -


ERROR] SetFrequencySXR(29.1833 MHz) - required VCO frequency is out of range [3800-7714] MHz
[ERROR] SetFrequencySXR(28.1833 MHz) - required VCO frequency is out of range [3800-7714] MHz
Terminating SDR thread..
SDRThread::readStream(): 3.1 iqDataOutQueue output queue is full, discard processing of the batch...
readLoop() ended.
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 4
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 4
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 4
libusb: warning [darwin_abort_transfers] aborting all transactions on interface 1 pipe 4
device deinit()
SDR thread done.
Terminating SDR post-processing thread..
Terminating All Demodulators..
Terminating Visual Processor threads..
Garbage collected demodulator instance '28.183'... 
Application termination complete.
libusb: warning [libusb_exit] application left some devices open

**Comment by cjcliffe** [comment]
@righthalfplane thanks for the reports; I'll try building against the latest limesuite for the next build

**Comment by vsonnier** [comment]
@righthalfplane Please see #716 and #718 where issues about LimeSDR vs MacOS are listed, and where we also solved the problem of using LimeSDR with high sample rates.

**Comment by vsonnier** [comment]
Outdated issue. Spring cleanup.
