### ISSUE TITLE
Crash when empty sample rates returned by listSampleRates()

### ISSUE THREAD

**Issue by grutz** [cjcliffe/CubicSDR#704]
CubicSDR crashes on https://github.com/cjcliffe/CubicSDR/blob/master/src/sdr/SDRDeviceInfo.cpp#L212 when `SoapySDR::Device::listSampleRates()` returns the default vector (e.g., the Soapy driver does not implement it).

Seeing this with SoapyBladeRF.

**Comment by vsonnier** [comment]
Hi @grutz, CubicSDR no support (yet) `getSampleRateRange` as you can see in this issue : https://github.com/pothosware/SoapyBladeRF/pull/27 so still _requires_ `listSampleRates` to be properly implemented. 
Please use the BladeRF PR https://github.com/pothosware/SoapyBladeRF/pull/27 to get your device working in the meantime.

**Comment by vsonnier** [comment]
Ping @grutz, @guruofquality has just pushed the related PRs into SoapyBladeRF `master`, could you please try these and let us know if it solves your problems ?

**Comment by grutz** [comment]
@vsonnier This specific issue is working with the master SoapyBladeRF branch as I can load the BladeRF now and see data. Thanks!
