### ISSUE TITLE
AppImage saving setting to incorrect? location

### ISSUE THREAD

**Issue by warren-axiell** [cjcliffe/CubicSDR#705]
Hello, 

I am using your .AppImage version which is fantastic, thanks!  However, it was not saving any of my settings.  I ran strace on it and found it was trying to read them from ~/.CubicSDR-0.2.4-x86_64/ but was writing them to ~/.CubicSDR/

I ended up symlinking the two and everything now works fine. 

Thanks!

**Comment by cjcliffe** [comment]
@warren-axiell interesting, it should only be using ~/.CubicSDR/ -- thanks for the report.

**Comment by cjcliffe** [comment]
@warren-axiell I think I have it fixed now; here's the AppImage test build if you'd like to confirm:

[CubicSDR-0.2.5-x86_64.zip](https://github.com/cjcliffe/CubicSDR/files/3175624/CubicSDR-0.2.5-x86_64.zip)
