### ISSUE TITLE
Tooltips are helpful... but annoying

### ISSUE THREAD

**Issue by Kashouryo** [cjcliffe/CubicSDR#712]
![image](https://user-images.githubusercontent.com/37679684/53692215-f719e880-3dc6-11e9-891b-63c33b40b523.png)

Tooltips are everywhere in this programme and often block the mouse operation. For example in the waterfall, when the user tried to locate a frequency, a tooltip will pop out and block the user's view.

Suggestion: Add a setting to toggle on and off these tooltips.

Thank you and 73!

**Comment by vsonnier** [comment]
I agree, they are. That's why there is an option to toggle them on/off. Here they are off.

![2019-03-03_085143_cr](https://user-images.githubusercontent.com/5152742/53692512-ae940800-3d91-11e9-9570-8890f180b7d1.png)

Have fun with CubicSDR !
