### ISSUE TITLE
CubicSDR 0.2.5 High CPU when SDRplay RSP2 is shut off (paused)

### ISSUE THREAD

**Issue by dslotter** [cjcliffe/CubicSDR#733]
When I've got CubicSDR 0.2.5 running, but have selected "Stop/Start Device" in the menu to stop (pause) the currently running SDR, CubicSDR still has high CPU usage. Here's what it shows for me on Ubuntu 16.04.6 Linux:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND         
32129 dave      20   0 2903472 142964  40696 R  51.3  0.9  55:47.62 CubicSDR        

When I start CubicSDR (fresh launch) and have not yet started a SDR device, then I have "relatively" low CPU:

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND         
15948 dave      20   0 1444224  97460  57968 S   7.7  0.6   0:02.51 CubicSDR        

I am using the SDRPlay RSP 2 when this occurs. Of interesting note that this high CPU does not occur when stopping (pausing) my LimeSDR mini.

dave@Moonquake:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

dave@Moonquake:~$ dpkg -l | grep -i sdr
ii  freedv                                                      1.1-1                                              amd64        Software Defined Radio (SDR)
ii  gqrx-sdr                                                    2.11.5-gqrx1~xenial                                amd64        Software defined radio receiver
ii  gr-osmosdr                                                  0.1.4.127-myriadrf2~xenial                         amd64        Gnuradio blocks from the OsmoSDR project
ii  libgnuradio-osmosdr0.1.4:amd64                              0.1.4.127-myriadrf2~xenial                         amd64        Gnuradio blocks from the OsmoSDR project
ii  libmirisdr0:amd64                                           0.0.4.59ba37-4                                     amd64        Software defined radio support for Mirics hardware (development files)
ii  libosmosdr0:amd64                                           0.1.8.effcaa7-5                                    amd64        Software defined radio support for OsmoSDR hardware (library)
ii  librtlsdr-dev                                               0.6.0-myriadrf1~xenial                             amd64        Software defined radio receiver for Realtek RTL2832U (development)
ii  librtlsdr0:amd64                                            0.6.0-myriadrf1~xenial                             amd64        Software defined radio receiver for Realtek RTL2832U (library)
ii  libsoapysdr0.6:amd64                                        0.6.1-myriadrf~xenial                              amd64        software defined radio interface library
ii  libsoapysdr0.7:amd64                                        0.7.1-myriadrf1~ubuntu16.04                        amd64        software defined radio interface library
ii  rtl-sdr                                                     0.6.0-myriadrf1~xenial                             amd64        Software defined radio receiver for Realtek RTL2832U (tools)
ii  soapysdr-module-lms7                                        19.01.0.71.025ffa1-myriadrf1~xenial                all          Lime Suite - SoapySDR bindings metapackage
ii  soapysdr-tools                                              0.7.1-myriadrf1~ubuntu16.04                        amd64        software defined radio interface library tools
ii  soapysdr0.7-module-lms7:amd64                               19.01.0.71.025ffa1-myriadrf1~xenial                amd64        Lime Suite - SoapySDR bindings

dave@Moonquake:~/projects/hamradio/sdr/sdrplay2/SoapySDRPlay/build$ cat Version.cpp 
#include <SoapySDR/Modules.hpp>
            static const SoapySDR::ModuleVersion registersdrPlaySupportVersion("0.3.0-31a3a36");
 
Please let me know if you need additional information. I'm ready to assist in troubleshooting in any way possible.

**Comment by vsonnier** [comment]
This is way too old, and we have both SDRPlay API v3 and a completly new SoapySDRPlay module thanks to the effors of @fventuri and @SDRPlay and others. This particular issue is not relevant anymore.
