### ISSUE TITLE
Crash when selecting LimeSDR USB in initial window

### ISSUE THREAD

**Issue by chorca** [cjcliffe/CubicSDR#735]
I have the latest Git version of CubicSDR compiled against
- wxWidgets 3.1.2
- Latest Git SoapySDR
- Latest Git liquid-dsp
- Latest Git LimeSuite

When I run CubicSDR, the interface comes up and it shows the initial radio selection screen, where it lists the LimeSDR device with the correct serial number. When I select the device in the list, some of it's properties show up in the window on the right, however, they aren't selectable and neither is the "start" button. A few seconds after selecting the LimeSDR device in the list, the whole program closes.

Video of the issue:
https://imgur.com/mQMA5Ow

Output from CubicSDR:
[cubicsdr_output.txt](https://github.com/cjcliffe/CubicSDR/files/3205155/cubicsdr_output.txt)

I compiled most of the supporting packages via this guide: http://blog.reds.ch/?p=43
and built wxWidgets and liquid-dsp according to the build guide on the wiki here, installing them into the same prefix.

It seems like something in the background is crashing but not sure how to debug what's stopping.

**Comment by vsonnier** [comment]
Completly outdated issue. Spring cleanup.
