### ISSUE TITLE
Windows 10 CubicSDR project (Debug) issue

### ISSUE THREAD

**Issue by MarcKaufman** [cjcliffe/CubicSDR#737]
When building the Debug variant of CubicSDR, the Linker .lib files imported from wxWidgets need to be the debug variants, which have the same name as the Release libraries with 'd' appended. See  CubicSDR (project) Linker->Input->Additional Dependencies

**Comment by vsonnier** [comment]
This is not the way to do it, please folllow the guide here: https://github.com/cjcliffe/CubicSDR/wiki/Build-Windows#debugging-cubicsdr

You'll get a `Release` build, unoptimized, with debugging information which is perfectly fine for debugging (I use this).
The only advantage you would get using a `Debug` config would be linking with C++ Debug Runtimes having debug-like instrumentation. 
The drawback is that regular and Debug runtimes are incompatible with each other, so everything must be re-compiled, including dependencies.

Of course, nothing stops you attempting this, but it is truly not necessary to debug in CubicSDR.
