### ISSUE TITLE
Windows: std::binary_function not supported in MSVC 2019

### ISSUE THREAD

**Issue by MarcKaufman** [cjcliffe/CubicSDR#739]
In the latest release of Visual Studio 2019 (10.0.18362.) std::binary_function has been removed. I replaced it with a local declaration, and changed to binary_function (no std::) in 3 include files. You may wish to clean this up in a different way. Files are BookmarkMgr.h, IOThread.h, util/DataTree.h

(added after #include declarations)

#ifndef BINARY_FUNCTION
template <class Arg1, class Arg2, class Result>
struct binary_function {
	typedef Arg1 first_argument_type;
	typedef Arg2 second_argument_type;
	typedef Result result_type;
};
#define BINARY_FUNCTION
#endif

**Comment by vsonnier** [comment]
Hello @MarcKaufman,
Technically std::binary_function has not been removed, but it is true iy has been deprecated in C+11+. It compiles for me in Visual Studio 2016 16.1.1, so maybe you forced some C++ standard where it has been removed.
Still, removing old cruft is always good, so I've commited a change where std:binary_function has been removed entirely.
