### ISSUE TITLE
Impossible finish the compilation: CubicSDR.cpp.o

### ISSUE THREAD

**Issue by giorgiofolle** [cjcliffe/CubicSDR#75]
After i have installed liquid-dps i tryed to compile cubic sdr , but after i type : "sudo make" i have this error message and i can't compile nothing.

$ sudo make 
[sudo] password for giorgio: 
[  2%] Building CXX object CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o
/opt/CubicSDR/src/CubicSDR.cpp:12:2: error: #error "OpenGL required: set wxUSE_GLCANVAS to 1 and rebuild the library"
 #error "OpenGL required: set wxUSE_GLCANVAS to 1 and rebuild the library"
  ^
In file included from /opt/CubicSDR/src/visual/PrimaryGLContext.h:10:0,
                 from /opt/CubicSDR/src/CubicSDR.h:10,
                 from /opt/CubicSDR/src/CubicSDR.cpp:15:
/opt/CubicSDR/src/util/GLFont.h:85:5: error: ‘GLuint’ does not name a type
     GLuint texId;
     ^
In file included from /opt/CubicSDR/src/CubicSDR.h:10:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:15:
/opt/CubicSDR/src/visual/PrimaryGLContext.h:14:44: error: expected class-name before ‘{’ token
 class PrimaryGLContext: public wxGLContext {
                                            ^
/opt/CubicSDR/src/visual/PrimaryGLContext.h:19:33: error: expected ‘)’ before ‘*’ token
     PrimaryGLContext(wxGLCanvas *canvas, wxGLContext *sharedContext);
                                 ^
/opt/CubicSDR/src/visual/PrimaryGLContext.h:21:35: error: ‘GLenum’ has not been declared
     static wxString glGetwxString(GLenum name);
                                   ^
In file included from /opt/CubicSDR/src/CubicSDR.cpp:15:0:
/opt/CubicSDR/src/CubicSDR.h:28:23: error: expected ‘;’ at end of member declaration
     PrimaryGLContext &GetContext(wxGLCanvas *canvas);
                       ^
/opt/CubicSDR/src/CubicSDR.h:28:45: error: expected ‘)’ before ‘*’ token
     PrimaryGLContext &GetContext(wxGLCanvas *canvas);
                                             ^
In file included from /opt/CubicSDR/src/CubicSDR.cpp:15:0:
/opt/CubicSDR/src/CubicSDR.h: In constructor ‘CubicSDR::CubicSDR()’:
/opt/CubicSDR/src/CubicSDR.h:23:5: error: uninitialized reference member in ‘class PrimaryGLContext&’ [-fpermissive]
     CubicSDR() :
     ^
In file included from /opt/CubicSDR/src/CubicSDR.cpp:15:0:
/opt/CubicSDR/src/CubicSDR.h:28:34: note: ‘PrimaryGLContext& CubicSDR::GetContext’ should be initialized
     PrimaryGLContext &GetContext(wxGLCanvas *canvas);
                                  ^
In file included from /usr/include/wx-3.0-unofficial/wx/window.h:22:0,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/cursor.h: In constructor ‘wxBusyCursorSuspender::wxBusyCursorSuspender()’:
/usr/include/wx-3.0-unofficial/wx/cursor.h:93:22: error: ‘wxIsBusy’ was not declared in this scope
         if( wxIsBusy() )
                      ^
/usr/include/wx-3.0-unofficial/wx/cursor.h:95:26: error: ‘wxBusyCursor’ has not been declared
             wxSetCursor( wxBusyCursor::GetStoredCursor() );
                          ^
/usr/include/wx-3.0-unofficial/wx/cursor.h:95:58: error: ‘wxSetCursor’ was not declared in this scope
             wxSetCursor( wxBusyCursor::GetStoredCursor() );
                                                          ^
/usr/include/wx-3.0-unofficial/wx/cursor.h: In destructor ‘wxBusyCursorSuspender::~wxBusyCursorSuspender()’:
/usr/include/wx-3.0-unofficial/wx/cursor.h:100:22: error: ‘wxIsBusy’ was not declared in this scope
         if( wxIsBusy() )
                      ^
/usr/include/wx-3.0-unofficial/wx/cursor.h:102:26: error: ‘wxBusyCursor’ has not been declared
             wxSetCursor( wxBusyCursor::GetBusyCursor() );
                          ^
/usr/include/wx-3.0-unofficial/wx/cursor.h:102:56: error: ‘wxSetCursor’ was not declared in this scope
             wxSetCursor( wxBusyCursor::GetBusyCursor() );
                                                        ^
In file included from /usr/include/wx-3.0-unofficial/wx/window.h:25:0,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/region.h: In member function ‘bool wxRegionBase::Intersect(const wxRect&)’:
/usr/include/wx-3.0-unofficial/wx/region.h:242:37: error: invalid use of incomplete type ‘class wxRegion’
     return DoIntersect(wxRegion(rect));
                                     ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:37:28: error: forward declaration of ‘class wxRegion’
 class WXDLLIMPEXP_FWD_CORE wxRegion;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/window.h:25:0,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/region.h: In member function ‘bool wxRegionBase::Subtract(const wxRect&)’:
/usr/include/wx-3.0-unofficial/wx/region.h:247:36: error: invalid use of incomplete type ‘class wxRegion’
     return DoSubtract(wxRegion(rect));
                                    ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:37:28: error: forward declaration of ‘class wxRegion’
 class WXDLLIMPEXP_FWD_CORE wxRegion;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/window.h:25:0,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/region.h: In member function ‘bool wxRegionBase::Xor(const wxRect&)’:
/usr/include/wx-3.0-unofficial/wx/region.h:252:31: error: invalid use of incomplete type ‘class wxRegion’
     return DoXor(wxRegion(rect));
                               ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:37:28: error: forward declaration of ‘class wxRegion’
 class WXDLLIMPEXP_FWD_CORE wxRegion;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14:0,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/window.h: At global scope:
/usr/include/wx-3.0-unofficial/wx/window.h:99:12: error: field ‘font’ has incomplete type ‘wxFont’
     wxFont font;
            ^
/usr/include/wx-3.0-unofficial/wx/window.h:102:14: error: field ‘colFg’ has incomplete type ‘wxColour’
     wxColour colFg;
              ^
/usr/include/wx-3.0-unofficial/wx/window.h:106:14: error: field ‘colBg’ has incomplete type ‘wxColour’
     wxColour colBg;
              ^
/usr/include/wx-3.0-unofficial/wx/window.h:240:17: error: ‘wxWindowID’ has not been declared
     void SetId( wxWindowID winid ) { m_windowId = winid; }
                 ^
/usr/include/wx-3.0-unofficial/wx/window.h:241:5: error: ‘wxWindowID’ does not name a type
     wxWindowID GetId() const { return m_windowId; }
     ^
/usr/include/wx-3.0-unofficial/wx/window.h:247:12: error: ‘wxWindowID’ does not name a type
     static wxWindowID NewControlId(int count = 1)
            ^
/usr/include/wx-3.0-unofficial/wx/window.h:254:36: error: ‘wxWindowID’ has not been declared
     static void UnreserveControlId(wxWindowID id, int count = 1)
                                    ^
/usr/include/wx-3.0-unofficial/wx/window.h:1458:13: error: ‘WXWidget’ does not name a type
     virtual WXWidget GetHandle() const = 0;
             ^
/usr/include/wx-3.0-unofficial/wx/window.h:1460:34: error: ‘WXWidget’ has not been declared
     virtual void AssociateHandle(WXWidget WXUNUSED(handle)) { }
                                  ^
/usr/include/wx-3.0-unofficial/wx/window.h:1520:21: error: ‘wxWindowID’ has not been declared
                     wxWindowID winid,
                     ^
/usr/include/wx-3.0-unofficial/wx/window.h:1528:21: error: ‘wxWindowID’ has not been declared
                     wxWindowID winid,
                     ^
/usr/include/wx-3.0-unofficial/wx/window.h:1571:5: error: ‘wxWindowIDRef’ does not name a type
     wxWindowIDRef        m_windowId;
     ^
/usr/include/wx-3.0-unofficial/wx/window.h:1599:26: error: field ‘m_cursor’ has incomplete type ‘wxCursor’
     wxCursor             m_cursor;
                          ^
/usr/include/wx-3.0-unofficial/wx/window.h:1600:26: error: field ‘m_font’ has incomplete type ‘wxFont’
     wxFont               m_font;                // see m_hasFont
                          ^
/usr/include/wx-3.0-unofficial/wx/window.h:1601:26: error: field ‘m_backgroundColour’ has incomplete type ‘wxColour’
     wxColour             m_backgroundColour,    //     m_hasBgCol
                          ^
/usr/include/wx-3.0-unofficial/wx/window.h:1602:26: error: field ‘m_foregroundColour’ has incomplete type ‘wxColour’
                          m_foregroundColour;    //     m_hasFgCol
                          ^
/usr/include/wx-3.0-unofficial/wx/window.h:1609:26: error: field ‘m_updateRegion’ has incomplete type ‘wxRegion’
     wxRegion             m_updateRegion;
                          ^
/usr/include/wx-3.0-unofficial/wx/window.h:765:33: error: incomplete type ‘wxNavigationKeyEvent’ used in nested name specifier
     bool NavigateIn(int flags = wxNavigationKeyEvent::IsForward)
                                 ^
/usr/include/wx-3.0-unofficial/wx/window.h:770:31: error: incomplete type ‘wxNavigationKeyEvent’ used in nested name specifier
     bool Navigate(int flags = wxNavigationKeyEvent::IsForward)
                               ^
/usr/include/wx-3.0-unofficial/wx/window.h: In member function ‘void wxWindowBase::SetId(int)’:
/usr/include/wx-3.0-unofficial/wx/window.h:240:38: error: ‘m_windowId’ was not declared in this scope
     void SetId( wxWindowID winid ) { m_windowId = winid; }
                                      ^
/usr/include/wx-3.0-unofficial/wx/window.h: In static member function ‘static void wxWindowBase::UnreserveControlId(int, int)’:
/usr/include/wx-3.0-unofficial/wx/window.h:256:9: error: ‘wxIdManager’ has not been declared
         wxIdManager::UnreserveId(id, count);
         ^
/usr/include/wx-3.0-unofficial/wx/window.h: In member function ‘wxWindow* wxWindowBase::GetGrandParent() const’:
/usr/include/wx-3.0-unofficial/wx/window.h:1956:31: error: invalid use of incomplete type ‘class wxWindow’
     return m_parent ? m_parent->GetParent() : NULL;
                               ^
In file included from /usr/include/wx-3.0-unofficial/wx/wx.h:26:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:8:
/usr/include/wx-3.0-unofficial/wx/utils.h:55:28: error: forward declaration of ‘class wxWindow’
 class WXDLLIMPEXP_FWD_CORE wxWindow;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20:0,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/nonownedwnd.h: At global scope:
/usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:25:54: error: invalid use of incomplete type ‘class wxWindow’
 class WXDLLIMPEXP_CORE wxNonOwnedWindowBase : public wxWindow
                                                      ^
In file included from /usr/include/wx-3.0-unofficial/wx/wx.h:26:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:8:
/usr/include/wx-3.0-unofficial/wx/utils.h:55:28: error: forward declaration of ‘class wxWindow’
 class WXDLLIMPEXP_FWD_CORE wxWindow;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/defs.h:695:0,
                 from /usr/include/wx-3.0-unofficial/wx/wxprec.h:12,
                 from /opt/CubicSDR/src/CubicSDR.cpp:5:
/usr/include/wx-3.0-unofficial/wx/nonownedwnd.h: In member function ‘bool wxNonOwnedWindowBase::SetShape(const wxRegion&)’:
/usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:37:9: error: ‘HasFlag’ was not declared in this scope
         wxCHECK_MSG
         ^
In file included from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20:0,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:43:22: error: invalid use of incomplete type ‘const class wxRegion’
         return region.IsEmpty() ? DoClearShape() : DoSetRegionShape(region);
                      ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:37:28: error: forward declaration of ‘const class wxRegion’
 class WXDLLIMPEXP_FWD_CORE wxRegion;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/toplevel.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/iconbndl.h: In member function ‘wxIcon wxIconBundle::GetIcon(wxCoord, int) const’:
/usr/include/wx-3.0-unofficial/wx/iconbndl.h:85:9: error: return type ‘class wxIcon’ is incomplete
         { return GetIcon(wxSize(size, size), flags); }
         ^
/usr/include/wx-3.0-unofficial/wx/iconbndl.h:85:51: error: invalid use of incomplete type ‘class wxIcon’
         { return GetIcon(wxSize(size, size), flags); }
                                                   ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:34:28: error: forward declaration of ‘class wxIcon’
 class WXDLLIMPEXP_FWD_CORE wxIcon;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/toplevel.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/iconbndl.h: In member function ‘wxIcon wxIconBundle::GetIconOfExactSize(wxCoord) const’:
/usr/include/wx-3.0-unofficial/wx/iconbndl.h:91:9: error: return type ‘class wxIcon’ is incomplete
         { return GetIconOfExactSize(wxSize(size, size)); }
         ^
/usr/include/wx-3.0-unofficial/wx/iconbndl.h:91:55: error: invalid use of incomplete type ‘class wxIcon’
         { return GetIconOfExactSize(wxSize(size, size)); }
                                                       ^
In file included from /usr/include/wx-3.0-unofficial/wx/font.h:21:0,
                 from /usr/include/wx-3.0-unofficial/wx/window.h:23,
                 from /usr/include/wx-3.0-unofficial/wx/nonownedwnd.h:14,
                 from /usr/include/wx-3.0-unofficial/wx/toplevel.h:20,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/gdicmn.h:34:28: error: forward declaration of ‘class wxIcon’
 class WXDLLIMPEXP_FWD_CORE wxIcon;
                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/frame.h:18:0,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/toplevel.h: In member function ‘virtual bool wxTopLevelWindowBase::IsActive()’:
/usr/include/wx-3.0-unofficial/wx/toplevel.h:226:61: error: ‘FindFocus’ was not declared in this scope
     virtual bool IsActive() { return IsDescendant(FindFocus()); }
                                                             ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h:226:62: error: ‘IsDescendant’ was not declared in this scope
     virtual bool IsActive() { return IsDescendant(FindFocus()); }
                                                              ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h: In member function ‘virtual bool wxTopLevelWindowBase::IsVisible() const’:
/usr/include/wx-3.0-unofficial/wx/toplevel.h:279:53: error: ‘IsShown’ was not declared in this scope
     virtual bool IsVisible() const { return IsShown(); }
                                                     ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h: In member function ‘virtual void wxTopLevelWindowBase::DoGetScreenPosition(int*, int*) const’:
/usr/include/wx-3.0-unofficial/wx/toplevel.h:324:27: error: ‘DoGetPosition’ was not declared in this scope
         DoGetPosition(x, y);
                           ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h: At global scope:
/usr/include/wx-3.0-unofficial/wx/toplevel.h:396:5: error: expected class-name before ‘{’ token
     {
     ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h:401:20: error: ‘wxWindowID’ has not been declared
                    wxWindowID winid,
                    ^
/usr/include/wx-3.0-unofficial/wx/toplevel.h: In constructor ‘wxTopLevelWindow::wxTopLevelWindow(wxWindow*, int, const wxString&, const wxPoint&, const wxSize&, long int, const wxString&)’:
/usr/include/wx-3.0-unofficial/wx/toplevel.h:407:15: error: class ‘wxTopLevelWindow’ does not have any field named ‘wxTopLevelWindowNative’
             : wxTopLevelWindowNative(parent, winid, title,
               ^
In file included from /opt/CubicSDR/src/AppFrame.h:3:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/frame.h: At global scope:
/usr/include/wx-3.0-unofficial/wx/frame.h:62:18: error: ‘wxWindowID’ has not been declared
                  wxWindowID winid,
                  ^
/usr/include/wx-3.0-unofficial/wx/frame.h: In member function ‘virtual bool wxFrameBase::IsClientAreaChild(const wxWindow*) const’:
/usr/include/wx-3.0-unofficial/wx/frame.h:181:39: error: ‘IsClientAreaChild’ is not a member of ‘wxTopLevelWindow’
         return !IsOneOfBars(child) && wxTopLevelWindow::IsClientAreaChild(child);
                                       ^
In file included from /opt/CubicSDR/src/visual/ScopeCanvas.h:9:0,
                 from /opt/CubicSDR/src/AppFrame.h:6,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/ScopeContext.h: At global scope:
/opt/CubicSDR/src/visual/ScopeContext.h:12:39: error: ‘wxGLContext’ has not been declared
     ScopeContext(ScopeCanvas *canvas, wxGLContext *sharedContext);
                                       ^
In file included from /opt/CubicSDR/src/AppFrame.h:6:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/ScopeCanvas.h:12:38: error: expected class-name before ‘{’ token
 class ScopeCanvas: public wxGLCanvas {
                                      ^
In file included from /opt/CubicSDR/src/visual/SpectrumCanvas.h:9:0,
                 from /opt/CubicSDR/src/AppFrame.h:7,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/InteractiveCanvas.h:9:44: error: expected class-name before ‘{’ token
 class InteractiveCanvas: public wxGLCanvas {
                                            ^
In file included from /opt/CubicSDR/src/visual/SpectrumCanvas.h:10:0,
                 from /opt/CubicSDR/src/AppFrame.h:7,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/SpectrumContext.h:12:45: error: ‘wxGLContext’ has not been declared
     SpectrumContext(SpectrumCanvas *canvas, wxGLContext *sharedContext);
                                             ^
In file included from /opt/CubicSDR/src/visual/WaterfallCanvas.h:10:0,
                 from /opt/CubicSDR/src/AppFrame.h:8,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/WaterfallContext.h:11:47: error: ‘wxGLContext’ has not been declared
     WaterfallContext(WaterfallCanvas *canvas, wxGLContext *sharedContext);
                                               ^
/opt/CubicSDR/src/visual/WaterfallContext.h:18:5: error: ‘GLuint’ does not name a type
     GLuint waterfall[2];
     ^
In file included from /opt/CubicSDR/src/visual/MeterCanvas.h:10:0,
                 from /opt/CubicSDR/src/AppFrame.h:9,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/MeterContext.h:12:39: error: ‘wxGLContext’ has not been declared
     MeterContext(MeterCanvas *canvas, wxGLContext *sharedContext);
                                       ^
In file included from /opt/CubicSDR/src/visual/TuningCanvas.h:10:0,
                 from /opt/CubicSDR/src/AppFrame.h:10,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/TuningContext.h:12:41: error: ‘wxGLContext’ has not been declared
     TuningContext(TuningCanvas *canvas, wxGLContext *sharedContext);
                                         ^
In file included from /opt/CubicSDR/src/visual/ModeSelectorCanvas.h:10:0,
                 from /opt/CubicSDR/src/AppFrame.h:11,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/opt/CubicSDR/src/visual/ModeSelectorContext.h:12:53: error: ‘wxGLContext’ has not been declared
     ModeSelectorContext(ModeSelectorCanvas *canvas, wxGLContext *sharedContext);
                                                     ^
In file included from /opt/CubicSDR/src/CubicSDR.cpp:16:0:
/opt/CubicSDR/src/AppFrame.h:43:24: error: invalid use of incomplete type ‘class wxFrame’
 class AppFrame: public wxFrame {
                        ^
In file included from /usr/include/wx-3.0-unofficial/wx/wx.h:26:0,
                 from /opt/CubicSDR/src/CubicSDR.cpp:8:
/usr/include/wx-3.0-unofficial/wx/utils.h:54:28: error: forward declaration of ‘class wxFrame’
 class WXDLLIMPEXP_FWD_CORE wxFrame;
                            ^
/opt/CubicSDR/src/CubicSDR.cpp: In member function ‘virtual bool CubicSDR::OnInit()’:
/opt/CubicSDR/src/CubicSDR.cpp:86:95: error: ‘wxGetSingleChoiceIndex’ was not declared in this scope
         int devId = wxGetSingleChoiceIndex(wxT("Devices"), wxT("Choose Input Device"), choices);
                                                                                               ^
/opt/CubicSDR/src/CubicSDR.cpp: At global scope:
/opt/CubicSDR/src/CubicSDR.cpp:142:40: error: ‘PrimaryGLContext& CubicSDR::GetContext’ is not a static member of ‘class CubicSDR’
 PrimaryGLContext& CubicSDR::GetContext(wxGLCanvas *canvas) {
                                        ^
/opt/CubicSDR/src/CubicSDR.cpp:142:40: error: ‘wxGLCanvas’ was not declared in this scope
/opt/CubicSDR/src/CubicSDR.cpp:142:52: error: ‘canvas’ was not declared in this scope
 PrimaryGLContext& CubicSDR::GetContext(wxGLCanvas *canvas) {
                                                    ^
/opt/CubicSDR/src/CubicSDR.cpp:142:60: error: expected ‘,’ or ‘;’ before ‘{’ token
 PrimaryGLContext& CubicSDR::GetContext(wxGLCanvas *canvas) {
                                                            ^
In file included from /usr/include/wx-3.0-unofficial/wx/toplevel.h:22:0,
                 from /usr/include/wx-3.0-unofficial/wx/frame.h:18,
                 from /opt/CubicSDR/src/AppFrame.h:3,
                 from /opt/CubicSDR/src/CubicSDR.cpp:16:
/usr/include/wx-3.0-unofficial/wx/weakref.h: In instantiation of ‘void wxWeakRefImpl<T, false>::AssignHelper(T*, wxInt2Type<0>) [with T = wxWindow]’:
/usr/include/wx-3.0-unofficial/wx/weakref.h:141:80:   required from ‘void wxWeakRefImpl<T, false>::Assign(TDerived*) [with TDerived = wxWindow; T = wxWindow]’
/usr/include/wx-3.0-unofficial/wx/weakref.h:220:9:   required from ‘wxWeakRef<T>::wxWeakRef(T*) [with T = wxWindow]’
/usr/include/wx-3.0-unofficial/wx/toplevel.h:262:58:   required from here
/usr/include/wx-3.0-unofficial/wx/weakref.h:155:62: error: cannot dynamic_cast ‘pobj’ (of type ‘class wxWindow*’) to type ‘class wxTrackable*’ (source is a pointer to incomplete type)
         wxTrackable *ptbase = dynamic_cast<wxTrackable*>(pobj);
                                                              ^
CMakeFiles/CubicSDR.dir/build.make:54: set di istruzioni per l'obiettivo "CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o" non riuscito
make[2]: *** [CMakeFiles/CubicSDR.dir/src/CubicSDR.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/CubicSDR.dir/all" non riuscito
make[1]: *** [CMakeFiles/CubicSDR.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2

**Comment by cjcliffe** [comment]
The error is probably correct, "```#error "OpenGL required: set wxUSE_GLCANVAS to 1 and rebuild the library```"

You'll need to compile wxWidgets with wxGLCanvas support as suggested, pass ```--with-opengl``` when running `configure` for wxWidgets.
