### ISSUE TITLE
Disable audio

### ISSUE THREAD

**Issue by aik** [cjcliffe/CubicSDR#750]
Is there a way to disable audio in linux?

**Comment by parkerlreed** [comment]
As in processing or just mute it?

**Comment by aik** [comment]
mute. there is no option "no audio" so I select one of those which are not connected anywhere but every time I tune to a new frequency, cubucsdr switches to the default audio and turns that on.
I am trying to see activities in wifi range so listening to this does not make sense.

**Comment by parkerlreed** [comment]
The button right below the volume slider on the far top right should be mute.

**Comment by parkerlreed** [comment]
![image](https://user-images.githubusercontent.com/841440/64391968-bbcbd100-d018-11e9-8f5e-6db0ae919dbb.png)

**Comment by vsonnier** [comment]
@parkerlreed As @parkerlreed says : `The M (Mute)` button mute all. Note that you can mute a demod individually by pressing `M` on a currently highlighted demod.
