### ISSUE TITLE
CubicSDR demodulators

### ISSUE THREAD

**Issue by tchuber** [cjcliffe/CubicSDR#756]
I just recompiled CubicSDR with Soapy and still can't select sitgnals on waterfall or drag the demodulater to new freq or even make new ones.  I can enter freq with space then type it in or use the rig control both ways seems to work but would like to select with the waterfall if I could any ideas? 

Tom WD0BFO

**Comment by vsonnier** [comment]
Read The Fucking Manual as computer geeks say :) Those questions has been answers countless times. How-tos:

- the Manual is here: https://cubicsdr.readthedocs.io/en/latest/ Not necessarily up-to-date but written in human language , and you can grab the concepts there. 
- Read the tootips, they can guide you to setup a demod and other things
- Experiment, your house won't burn down. The general advice is that the Menus are for "static" settings (choice of AGC, bandwidth, graphic settings) , the Main screen for everything else: you can click, scroll, drag on this screen to see what happens and use the displayed tooltops as suggestions. You can create / delete demods, assign different audio outputs to modems, scroll the bandwidth, record demods audio in Wav files....etc.
- One of my explanations here : https://github.com/cjcliffe/CubicSDR/issues/556
