### ISSUE TITLE
Center Frequency Scroll, Doesn't Tune

### ISSUE THREAD

**Issue by ithinkimongithub** [cjcliffe/CubicSDR#760]
Using a mouse-wheel to scroll center frequency, changes adjusts the scale properly, and the center frequency increments, but the radio tuning remains at the old frequency.

e.g., tune 94.3 and then scroll only the 1's MHz place of center frequency, and listen to same station now on 95.3 Mhz. Appears to be only a case with 1's MHz or greater place.
![pic1](https://user-images.githubusercontent.com/56378727/66539296-b87aa800-eae4-11e9-9910-b8d9760341f5.jpg)
![pic2](https://user-images.githubusercontent.com/56378727/66539299-ba446b80-eae4-11e9-9dc8-28a40377c89f.jpg)

**Comment by ithinkimongithub** [comment]
What this also means that I can return to 194.3MHz and still pick up 94.3MHz.
![pic3](https://user-images.githubusercontent.com/56378727/66539509-6e45f680-eae5-11e9-8ed2-b4be3c987198.jpg)

**Comment by vsonnier** [comment]
Using a mouse-wheel to scroll center frequency, changes adjusts the scale properly, and the center frequency increments, but the radio tuning remains at the old frequency.

That is the general idea of SDR: the Center frequency is the tuning frequency, but any nimber of demodulators (VFOs) can be created in the range [Center - bandwidth / 2 ; Center + bandwidth / 2].
Once created, those demods have no reason to move from their "virtual" frequency and remain listenable if they are in the [Center - bandwidth / 2 ; Center + bandwidth / 2]. 
Once they are out of band, they become inactive and silent, of course.

You can see Cubic and SDRs that way: you can create any number of VFOs anywhere in you device reception full range (ex. 24MHz - 1500MHz for and RTL-SDR, 10KHz-2GHz for an RSP..) and they become live once your observation window, as large as your bandwidth, pass over them. That is How you explore the RF spectrum.    
 
Please inform further here #756 to find out how Cubic works. Sorry for having not much time to explain further.
