### ISSUE TITLE
Won’t load on Mac OS Mojave

### ISSUE THREAD

**Issue by whcassing** [cjcliffe/CubicSDR#768]
i have tried for several days to load the CubicSDR dmg file onto my iMac with Mojave.  Every attempt has ended with only 17k loading, even after several hours.

**Comment by Dantali0n** [comment]
In order for us to be able to help you, we will need more information.

- Were do you download the dmg from with which url?
- Which version of the CubicSDR dmg are you downloading?
- What exactly do you mean with 'only 17k loading', does the download not work or are you unable to open the dmg image?
- If the download isen't working with which browser are you trying to download it and have you tried another browser?

**Comment by whcassing** [comment]
I have attached two screen shots, one from Google and another from Firefox.  I have also tried Safari.  I tried to download from the GitHub software site, https://github.com/cjcliffe/CubicSDR/releases <https://github.com/cjcliffe/CubicSDR/releases>.  I am using an iMac running Mojave.

**Comment by Dantali0n** [comment]
> I have attached two screen shots, one from Google and another from Firefox. I have also tried Safari. I tried to download from the GitHub software site, https://github.com/cjcliffe/CubicSDR/releases. I am using an iMac running Mojave.

Unfortunately, attaching images via email to reply to Github comments does not work. As a result we can not see the images you have attached.

@whcassing Could you upload the screenshots as attachment using the Github website? you can upload them by dragging & dropping them into the comment box.

**Comment by whcassing** [comment]
Here are the images I sent in my last email.  Please note that the downloads stopped early.

**Comment by Dantali0n** [comment]
> Here are the images I sent in my last email. Please note that the downloads stopped early.

I am sorry the images aren't sent, as again you replied via email and it is not possible to send images via email to Github.

**Comment by Dantali0n** [comment]
@vsonnier should we close this one to? I do not think the author will come back to post the pictures and even than it seems like a local browser issue on the authors end. I can download and open all release files just fine.

**Comment by vsonnier** [comment]
Thanks @Dantali0n for the report, let's close it then.
