### ISSUE TITLE
 CMake Error - LibUSB 1.0 required to compile rtl-sdr

### ISSUE THREAD

**Issue by serj053** [cjcliffe/CubicSDR#790]
![Error_librtlsdr_CMake](https://user-images.githubusercontent.com/10112259/73550366-83a8ad00-4455-11ea-80cc-b4f699b319a8.png)
Friends, please tell me what this error message means.

**Comment by vsonnier** [comment]
Please follow the procedure here : https://github.com/cjcliffe/CubicSDR/wiki/Build-Windows everything is described, including hpw to get or compile your own `libusb`.
