### ISSUE TITLE
Why are all people authorized to edit wiki pages?

### ISSUE THREAD

**Issue by Dantali0n** [cjcliffe/CubicSDR#798]
Asked by @magentos-pl by creating wiki pages in Polish...

**Comment by parkerlreed** [comment]
I mean isn't that part of the point of a wiki? Users can contribute updated documentation easier than a full pull request. 

I mean yeah if it gets out of hand and is abuse then a lockdown to contributors would be good.

**Comment by vsonnier** [comment]
@parkerlreed Agreed that anybody should be able to contribute, but on the other hand nothing is stopping fucking up the whole thing... I don't see how to simply revert a whole commit, except by comparing 2 revisions and reverting line-by-line.

**Comment by Dantali0n** [comment]
I get were the question by @magentos-pl is coming from, I have seen wikis defaced before and it is basically impossible to restore. Maybe editing wiki's by pull request is a better approach.

**Comment by vsonnier** [comment]
@cjcliffe  Has the ability to control access to the Wiki if he wish to, in Settings > Restrict editing to collaborators only.

**Comment by cjcliffe** [comment]
@vsonnier seems like a good idea; I've updated the settings
