### ISSUE TITLE
Problem installing CubicSDR on Pi4B

### ISSUE THREAD

**Issue by W9KJO** [cjcliffe/CubicSDR#804]
I followed the 782 solution, I think.  I not very good at this Linux stuff.

Now I get this

pi@raspberrypi4b1:~/Downloads/CubicSDR/build $ cmake ../ -DOTHER_LIBRARIES:FILEPATH=/usr/lib/gcc/arm-linux-gnueabihf/8/libatomic.so -DCMAKE_BUILD_TYPE=Release -DwxWidgets_CONFIG_EXECUTABLE=~/Develop/wxWidgets-staticlib/bin/wx-config
-- Found hamlib library at: /usr/local/lib/libhamlib.so
-- Found hamlib static library at: /usr/local/lib/libhamlib.a
-- Found hamlib static modules: 
-- Found hamlib include directory at: /usr/local/include
32 bit compiler detected
CMake Warning (dev) at /usr/share/cmake-3.13/Modules/FindOpenGL.cmake:270 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/arm-linux-gnueabihf/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/arm-linux-gnueabihf/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/arm-linux-gnueabihf/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:170 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Copying /home/pi/Downloads/CubicSDR/font/*.fnt to directory /home/pi/Downloads/CubicSDR/build/x86/fonts
-- Configuring file vera_sans_mono12.fnt
-- Configuring file vera_sans_mono16.fnt
-- Configuring file vera_sans_mono18.fnt
-- Configuring file vera_sans_mono24.fnt
-- Configuring file vera_sans_mono27.fnt
-- Configuring file vera_sans_mono32.fnt
-- Configuring file vera_sans_mono36.fnt
-- Configuring file vera_sans_mono48.fnt
-- Configuring file vera_sans_mono64.fnt
-- Configuring file vera_sans_mono72.fnt
-- Configuring file vera_sans_mono96.fnt
-- Copying /home/pi/Downloads/CubicSDR/font/*.png to directory /home/pi/Downloads/CubicSDR/build/x86/fonts
-- Configuring file vera_sans_mono12_0.png
-- Configuring file vera_sans_mono16_0.png
-- Configuring file vera_sans_mono18_0.png
-- Configuring file vera_sans_mono24_0.png
-- Configuring file vera_sans_mono27_0.png
-- Configuring file vera_sans_mono32_0.png
-- Configuring file vera_sans_mono36_0.png
-- Configuring file vera_sans_mono48_0.png
-- Configuring file vera_sans_mono64_0.png
-- Configuring file vera_sans_mono72_0.png
-- Configuring file vera_sans_mono96_0.png
-- Copying /home/pi/Downloads/CubicSDR/icon/CubicSDR.ico to directory /home/pi/Downloads/CubicSDR/build/x86
-- Configuring file CubicSDR.ico
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pi/Downloads/CubicSDR/build
pi@raspberrypi4b1:~/Downloads/CubicSDR/build $ ls
CMakeCache.txt  cmake_install.cmake    CubicSDR.desktop  Makefile
CMakeFiles      cmake_uninstall.cmake  deb_post.sh       x86
pi@raspberrypi4b1:~/Downloads/CubicSDR/build $ cd x86
pi@raspberrypi4b1:~/Downloads/CubicSDR/build/x86 $ ls
CubicSDR.ico  fonts
pi@raspberrypi4b1:~/Downloads/CubicSDR/build/x86 $ ./CubicSDR
bash: ./CubicSDR: No such file or directory
pi@raspberrypi4b1:~/Downloads/CubicSDR/build/x86 $ cd ..
pi@raspberrypi4b1:~/Downloads/CubicSDR/build $ build$ sudo make install
bash: build$: command not found

What do I need to do now?

Thanks W9KJO Walter

**Comment by vsonnier** [comment]
Please don't create a new issue each time you have a question: participate instead to the #782 discussion, asking questions there. Thank you.
