### ISSUE TITLE
v0.2.6a on HiDPI Screen

### ISSUE THREAD

**Issue by jawatson** [cjcliffe/CubicSDR#805]
I've compiled CubicSDR v0.2.61 on a Dell XPS with a HiDPI screen (3840x2160).  The screen scaling is set to 200%. 

Everything appears to work correctly but the dialogue box used for entering frequencies manually is too small to display any content.

As a quick fix for my computer, I changed the dialogue size in /src/CubicSDR.cpp, line 974 as follows, setting the size to 700x150;

    FrequencyDialog fdialog(appframe, -1, title, activeModem, wxPoint(-100,-100), wxSize(700, 150), wxDEFAULT_DIALOG_STYLE, targetMode, initString);

This is obviously not a general fix but gets the application running on my machine.  The attached two photos show the dialogue box before and after the modification.
![before](https://user-images.githubusercontent.com/1736162/78505458-52619b80-777c-11ea-99ee-2ec98a410812.png)
![after](https://user-images.githubusercontent.com/1736162/78505464-5b526d00-777c-11ea-8b31-bd0ab09c49a9.png)

**Comment by Dantali0n** [comment]
I think it would be better to continue discussing Retina / HiDPI problems in an already created issue #758.

**Comment by jawatson** [comment]
Apologies - I didn't see the original issue when scanning through.  I've submitted a pull request for this particular issue.

**Comment by vsonnier** [comment]
@jawatson  Thanks for
