### ISSUE TITLE
RSPdx Notch Filters?

### ISSUE THREAD

**Issue by 101jallen** [cjcliffe/CubicSDR#814]
How are the hardware filters handled within Soapy and CubicSDR?

**Comment by vsonnier** [comment]
Generally speaking, SDRPlay device support is quite complete in Cubic through the SoapySDR module, with the Rf Notch filters in particular.

However both RSPDuo and RSPdX support are still in the making there: https://github.com/SDRplay/SoapySDRPlay and will be only supported through the API v3.

You'll have to compile and test this module youself to test it with RSPdx for now. What I can say oon my side is that the support of the RSP2 Rf notch filter is working perfectly.
