### ISSUE TITLE
Signal Strength Units

### ISSUE THREAD

**Issue by TJNII** [cjcliffe/CubicSDR#815]
Good evening:

In the main spectrum window I see the signal strength is displayed in decibels, but it is unclear decibels of what.  I assume this is dBm, is that correct?

Thanks for the great program!

**Comment by vsonnier** [comment]
> but it is unclear decibels of what. I assume this is dBm, is that correct?

Short answer: no, it is a relative mesure in dB from... whatever the device gives us. A dBm would be an enhancement. Follow the white rabbit #652 and mentioned issues there for explanation.
