### ISSUE TITLE
Option to disable dynamic squelch

### ISSUE THREAD

**Issue by driazati** [cjcliffe/CubicSDR#816]
The dynamic squelch works great except at the very end of a transmission when the signal drops off, it takes a second for the squelch level to drop so the noise is audible for that second. It would be nice if the dynamic squelch feature could be turned off and have the squelch level stay where it is manually set (If there's another way to fix the noise issue that'd be great too).

**Comment by Dantali0n** [comment]
You can manually set the squelch level by clicking in the volume slider on the right side of the zoomed in FFT.
