### ISSUE TITLE
Cannot "Start Device" after "Stop"

### ISSUE THREAD

**Issue by LOTR-Magic** [cjcliffe/CubicSDR#817]

**Comment by LOTR-Magic** [comment]
I use CubicSDR 0.2.4 and 0.2.5 with LimeSDR Mini on Mac Cataline.  AFter I push the "Stop/Start Device" button in "File" menu, it never be restart again after push "Stop/Start Device" button again. This happened with both version of  0.2.4 and 0.2.5. How to solve?

**Comment by vsonnier** [comment]
Issue is too old. Closing.
