### ISSUE TITLE
Using SDRPlay RSPDx, no audio under USB but working in other modulations

### ISSUE THREAD

**Issue by deltatango2** [cjcliffe/CubicSDR#818]
I can hear output in all other modes including LSB.  When I switch to USB audio output disappears, I am not sure if I am missing something operationally with the software.  I was not able to find in the docs or the UI any setting that would rectify it.  The audio waveform on the top right also goes to zero in USB, so its not just a machine audio issue. 

Thanks,

**Comment by vsonnier** [comment]
Thanks @deltatango2 for your report, looks like at least another user have the same problem. Please continue discussion in #820. We are interested in the description of your configration (Linux ? how it was built ? CubicSDR settings ? ...etc...
