### ISSUE TITLE
WHERE ARE THE UPDATES?

### ISSUE THREAD

**Issue by MiamiC70** [cjcliffe/CubicSDR#824]
WHERE ARE THE UPDATES?

**Comment by vsonnier** [comment]
@cjcliffe Owns this projects, and decides when a new version is to be out.

**Comment by MiamiC70** [comment]
Well, it would be nice if the guy stepped up and UPDATED it don't you think? It has been a while and this site is a mess. I have v0.2.5 yet the site still shows 0.2.4 WTF?
