### ISSUE TITLE
Where did cjcliffe go?

### ISSUE THREAD

**Issue by ah1102** [cjcliffe/CubicSDR#828]
Sorry for the spam, but where did cjcliffe go? A very promising project CubicSDR has stopped moving forward. Errors are rarely corrected, but no significant forward movements occur. A lot of things in "Roadmap and Ideas" are not implemented https://github.com/cjcliffe/CubicSDR/wiki/CubicSDR-Roadmap-and-Ideas . This project is the only worthy option on all platforms. Where did cjcliffe disappear or why did it stop supporting the project?

**Comment by vsonnier** [comment]
Hi @ah1102, looks like you are right on time for that question. I've just got a message form @cjcliffe telling me he'll be back to CubicSDR "soon" : It basically means he is still interested in Cubic and will make evolutions there, in the incomming months.
