### ISSUE TITLE
CubicSDR git master version not working on RPi OS Buster

### ISSUE THREAD

**Issue by BuddyButterfly** [cjcliffe/CubicSDR#830]
Hardware:
Raspberry PI 3

OS:
RPi OS Buster (current as of today) version "Raspberry Pi OS (32-bit) with desktop" (without additionl software). This OS uses LXDE.

CubicSDR:
- Curent git master version
- Compiled with all "standard libraries"  including wxWidges 3.1.3 on pi.

Symptom:
Cubic SDR does not show any graphics. Only small windows on the left side are show.  Functionality seems to be OK. It detects SDRPlay and it can be selected. See 
screenshot:

![Screenshot_20200608_204332](https://user-images.githubusercontent.com/8482998/84068071-bac13900-a9c8-11ea-9c52-78e2856cada2.png)

Counter-Verification:
Same build has been done on notebook with Kubuntu 18.04. CubicSDR works perfectly there.

Any Ideas?

**Comment by BuddyButterfly** [comment]
Reason found. On a direct display, CubcSDR shows up like it should.

So there is a problem when connecting remote via x2go or xrdp. In this mode, graphics is  not shown. I will further investigate.

**Comment by Dantali0n** [comment]
> Reason found. On a direct display, CubcSDR shows up like it should.
> 
> So there is a problem when connecting remote via x2go or xrdp. In this mode, graphics is not shown. I will further investigate.

CubicSDR uses graphics acceleration using OpenGL which does not work over x2go / xrdp. afaik this limitation can not be resolved using x windows based remote desktop solutions.

**Comment by cjcliffe** [comment]
@BuddyButterfly thanks for the submission, but it looks like supporting display protocols is outside the scope of CubicSDR itself.   

If you find something that works please feel free to follow-up as I'm sure others would be interested.
