### ISSUE TITLE
Pluto SDR

### ISSUE THREAD

**Issue by EA7TB** [cjcliffe/CubicSDR#849]
Hi.
Can you use the Adam PlutoSDR?

**Comment by Dantali0n** [comment]
Yes, by installing https://github.com/pothosware/SoapyPlutoSDR

**Comment by vsonnier** [comment]
Support exists as @Dantali0n said. Eventual issues should be submitted at https://github.com/pothosware/SoapyPlutoSDR , this is not directly Cubic-related. I've tried PlutoSDR myself with the existing module, and it worked rather fine.
