### ISSUE TITLE
Recording stops after changing demodulator bandwidth

### ISSUE THREAD

**Issue by shuyuan-liu** [cjcliffe/CubicSDR#854]
Recording "stops" after changing demodulator bandwidth during recording. The button still says "Stop recording" so it looks like it's still recording, but the recorded file only goes up to the point when the bandwidth was changed.

## Steps to reproduce

1. Run CubicSDR and start a device.
2. Press "Start recording".
3. Wait a few seconds for it to record something (A).
4. Change the demodulator bandwidth.
5. Wait a few seconds for it to record something (B).
6. Press "Stop recording".

### Result

Only audio during (A) is recorded. The audio file ends at the end of (A) and contains none of (B).

No error messages either graphically or in the console.

## Frequency

Always.

## Build information
OS: Arch Linux
Compiler: gcc 10.2.0
liquid-dsp: 1.3.2, with SSE4.1 extensions
soapysdr: 0.7.2

**Comment by vsonnier** [comment]
Hi @shuyuan-liu what you observe may or may not be normal. It **is** normal that the recording (A) is stopped when tou change the bandwith, but the recording actually do not stop, but automatically create another file.

In your case (B) is recording in another file created automatically.
