### ISSUE TITLE
Direct frequency entry doesn't seem to work in Linux

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#86]
Wasn't able to type into the direct entry box in linux, need to debug.

**Comment by UbhaSecurity** [comment]
Can confirm bug.

**Comment by cjcliffe** [comment]
now working in latest hotfix to master

**Comment by quantegy** [comment]
I am having issues with this on Mac as well. I'm not sure I am doing it correctly though. I put in a frequency in MHz, but it doesn't seem to correlate. It seems to just go to any random frequency.
