### ISSUE TITLE
Problem talking to Airspy HF+ via SoapyServer 

### ISSUE THREAD

**Issue by mkierczak** [cjcliffe/CubicSDR#862]
My setup: Linux Ubuntu machine + SoapySDRServer + Airspy HF+ discovery and on the other end OsX + CubicSDR.
When I connect, on the remote machine:

`SoapySDRServer --bind='0.0.0.0:5555'
######################################################
######################################################

Server version: 0.6.0-gc09b2f10
Server UUID: fed5251f-3eea-164c-8567-1844007f0101
Launching the server... tcp://0.0.0.0:5555
Server bound to 0.0.0.0:5555
Launching discovery server...
Connecting to DNS-SD daemon...
[INFO] Avahi version:  avahi 0.7
[INFO] Avahi hostname: rg
[INFO] Avahi domain:   local
[INFO] Avahi FQDN:     rg.local
[INFO] avahi_entry_group_add_service(rg._soapy._tcp)
Press Ctrl+C to stop the server
SoapyServerListener::accept(192.168.1.214:60219)
SoapyServerListener::close()
SoapyServerListener::accept(192.168.1.214:60221)
SoapyServerListener::accept(192.168.1.214:60222)
SoapyServerListener::close()
SoapyServerListener::accept(192.168.1.214:60223)
SoapyServerListener::close()
SoapyServerListener::close()
SoapyServerListener::accept(192.168.1.214:60225)
SoapyServerListener::accept(192.168.1.214:60226)
SoapyServerListener::close()
SoapyServerListener::accept(192.168.1.214:60227)`

On the OsX machine:
<img width="564" alt="Screenshot 2020-11-30 at 10 36 10" src="https://user-images.githubusercontent.com/4972207/100593012-2c36d000-32f8-11eb-949a-2987450a6059.png">

And then I connect, nothing happens:
<img width="1273" alt="Screenshot 2020-11-30 at 10 39 02" src="https://user-images.githubusercontent.com/4972207/100593099-496b9e80-32f8-11eb-8572-672ea2aec7ca.png">

No matter what I do, no waterfall, no response. From time to time a bunch of
`SoapyServerListener::close()
SoapyServerListener::accept(192.168.1.214:60422)
`
on the Soapy side and long silence again. 

Any ideas what can be wrong? I installed Soapy by compiling from sources.

**Comment by vsonnier** [comment]
Too old issue, closing. This issue is about `SoapyRemote` and device-specific anyway, nothing that Cubic can do.
