### ISSUE TITLE
widgets not visible OrangePi Plus

### ISSUE THREAD

**Issue by nsklyarov** [cjcliffe/CubicSDR#870]
Hi, i try compile CubicSdr on:
 
OrangePi Plus 2e 
Ubuntu 16.04.7 xenial
armv7l

..according to wiki instructions.

All steps go through without errors, but when I launched Cubic and selected the required device, Cubic did not display Waterfall and other widgets:

![1609167468402 remmina-2021-1-15-1:3:41 934991](https://user-images.githubusercontent.com/12935413/104667529-577a5080-56e7-11eb-8774-b66daf846efa.png)

What could be the problem? 
Thanks

**Comment by nsklyarov** [comment]
maybe the case is in libGL.so, cannot find this library on the system

**Comment by vsonnier** [comment]
> maybe the case is in libGL.so, cannot find this library on the system

Of course it is, CubicSDR is an OpenGL application : you need WxWidgets compiled with OpenGL support, AND your Pi must have Hardware acceleration.

**Comment by nsklyarov** [comment]
Yes you are right. the problem is not in the assembly, the problem is that I ran the application through VNC. VNC does not support openGL, but the board itself supports. if I use the board directly - then all is well. Thank you for your prompt reply.
