### ISSUE TITLE
Crash when setting bandwidth lover than 40. IE 39

### ISSUE THREAD

**Issue by UbhaSecurity** [cjcliffe/CubicSDR#88]
Crashes with "error: liquid_iirdes(), cutoff frequency out of range"

- Upgraded Liquid-dsp with git pull;make ldconfig. No Change.
- Reproduceable. Just set and bandwith lower than 40.

**Comment by cjcliffe** [comment]
probably related to the new iir band-pass filter for stereo FM; it's only been tested with 200khz/44khz+ so far.  Will fix this up shortly.

**Comment by UbhaSecurity** [comment]
Thx! :)

**Comment by cjcliffe** [comment]
just pushed a hotfix -- prevents generating bad filters and disables stereo path below 100khz
