### ISSUE TITLE
Installation problem with CubicSDR and RSPduo device!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by bh2raj** [cjcliffe/CubicSDR#880]
No SoapySDR modules were found.

CubicSDR requires at least one SoapySDR device support module to be installed.

Please visit https://github.com/cjcliffe/CubicSDR/wiki and in the build instructions for your platform read the 'Support Modules' section for more information.

**Comment by vsonnier** [comment]
I don't know what your are supposed to mean, however the RSPDuo support exists and works. And yes, CubicSDR access devices with modules that need to be build for your device of choice here: https://github.com/pothosware/SoapySDRPlay3
