### ISSUE TITLE
Debian bullseye unable to run

### ISSUE THREAD

**Issue by assasukasse** [cjcliffe/CubicSDR#881]
Hello
I have a RTL-SDR unit and I used to run it with gqrx until I came to know about CubicSDR.
I installed the cubicSDR package from Debian Bullseye repository in my system and attempted to run it.
Unfortunately it fails to start:

`$ CubicSDR 
Loaded 256 rig models via hamlib.

Audio Device #0 PulseAudio
	Default Output? Yes
	Default Input? Yes
	Input channels: 2
	Output channels: 2
	Duplex channels: 2
	Native formats:
		16-bit signed integer.
		32-bit signed integer.
		32-bit float normalized between plus/minus 1.0.
	Supported sample rates:
		8000hz
		16000hz
		22050hz
		32000hz
		44100hz
		48000hz
		96000hz

SDR enumerator starting.
SoapySDR init..
	API Version: v0.7.1
	ABI Version: v0.7
	Install root: /usr
	Loading modules... 
	Available factories...airspy, audio, bladerf, hackrf, lime, null, osmosdr, redpitaya, remote, rtlsdr, uhd
[INFO] [UHD] linux; GNU C++ version 10.2.1 20201207; Boost_107400; UHD_3.15.0.0-4+b1
Hash collision!!! Fatal error!!
CubicSDR: simple-watch.c:454: avahi_simple_poll_prepare: Assertion `s->state == STATE_INIT || s->state == STATE_DISPATCHED || s->state == STATE_FAILURE' failed.
Aborted
`
Could someone help me in troubleshooting this? This is a new amd64 Bullseye install and I am running Gnome3.
Many thanks

**Comment by vsonnier** [comment]
This is related to the `SoapyRemote` and `SoapyServer`. Consider opening an issue here instead : https://github.com/pothosware/SoapyRemote
