### ISSUE TITLE
Failing to compile with Ubuntu 20.10 on 64bit Linux Box

### ISSUE THREAD

**Issue by m0roj** [cjcliffe/CubicSDR#884]
$ sudo make install
After four attempts at entering directory:...............CubicSDR/build'
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libGL.so', needed by 'x64/CubicSDR'. Stop.
make[2]: Leaving directory ..............
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/CubicSDR.dir/all] Error 2
make[1]: Leaving directory .....................
make: *** [Makefile:130: all] Error 2
Does anyone have a solution for this, please?
Thanks in advance.

**Comment by vsonnier** [comment]
So, please describe here the remaining problem you may have.
