### ISSUE TITLE
no window refresh/update with wxWidgets-3.1.5 (Gtk+-3 backend)

### ISSUE THREAD

**Issue by stefantalpalaru** [cjcliffe/CubicSDR#886]
![screenshot_2021-04-16_19:04:30](https://user-images.githubusercontent.com/495550/115059442-db122c00-9ee6-11eb-9920-2bb2534e20f8.png)

**Comment by vsonnier** [comment]
Either your wxWidgets was compiled without OpenGL support, or you don't have proper OpenGL. Both are mandatory. Have a look at the Wiki.

**Comment by stefantalpalaru** [comment]
> Either your wxWidgets was compiled without OpenGL support, or you don't have proper OpenGL.

```text
$ lddtree /usr/bin/CubicSDR
...
    libwx_gtk3u_gl-3.1-gtk3.so.5 => /usr/lib64/libwx_gtk3u_gl-3.1-gtk3.so.5
...
        libEGL.so.1 => /usr/lib64/libEGL.so.1
            libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0
...
    libGL.so.1 => /usr/lib64/libGL.so.1
        libGLX.so.0 => /usr/lib64/libGLX.so.0
```

**Comment by stefantalpalaru** [comment]
Configuring wxWidgets-3.1.5 with `--disable-glcanvasegl` fixed the problem.

**Comment by Dantali0n** [comment]
> Configuring wxWidgets-3.1.5 with `--disable-glcanvasegl` fixed the problem.

Do you think this should be added to the wiki or is this some edge case due to your Graphics cards its egl implementation being funky.

Perhaps you could indicate the hardware and accompanying driver being used.

**Comment by stefantalpalaru** [comment]
> Do you think this should be added to the wiki or is this some edge case due to your Graphics cards its egl implementation being funky.

I think it's a matter of the CubicSDR GLX context competing with a wxWidget's EGL context. I'm no expert, but from a summary reading, it looks like you can't mix the two in the same application.

Sure, you can document that in the wiki for people building their own wxWidgets, but when 3.1.5 hits distro package repositories, with EGL built in by default, the problem is back.

A long-term solution would be to allow choosing between GLX and EGL in CubicSDR, at configuration time.

**Comment by vsonnier** [comment]
> I think it's a matter of the CubicSDR GLX context competing with a wxWidgets EGL context. I'm no expert, but from a summary reading it looks like you can't mix the two in the same application.

Me neither, I just heard of EGL here... Since CubicSDR access OpenGL "raw" in the GL wxGL context, it then make sense of disable EGL in wxWigets as @stefantalpalaru found. I've changed the Wiki accordingly.

Thanks @stefantalpalaru for your contribution ! Thanks @Dantali0n for your support as well.

**Comment by vsonnier** [comment]
I've updated the Travis scripts as well, referencing 3.1.5 with @stefantalpalaru fix.

**Comment by vsonnier** [comment]
I think the issue can be closed now.
