### ISSUE TITLE
Problem in attempting to run CubicSDR in terminal on Ubuntu 20.10

### ISSUE THREAD

**Issue by m0roj** [cjcliffe/CubicSDR#887]
The following error message is given in the terminal:
--------------------------------------------------
The program 'CubicSDR' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 356 error_code 2 request_code 152 minor_code 3)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
---------------------------------------------------------
Can anyone please offer advice on fixing this, as this error message is somewhat beyond my pay grade?
Thanks in advance.

**Comment by vsonnier** [comment]
Please don't turn every single issue you have on new issue, just use  the #884 you already opened.
