### ISSUE TITLE
Use built in wifi antenna as input source?

### ISSUE THREAD

**Issue by NeuroForLunch** [cjcliffe/CubicSDR#891]
Hi, the RTL-SDR dongles don't go above 1.7Ghz but built in wifi can be used for 2.4 and 5Ghz. There are paid software programs that show a waterfall plot using wifi data but is there a way to do this with CubicSDR?

**Comment by vsonnier** [comment]
Hi @NeuroForLunch , the question has already answered (some time ago) in #631: the short answer is : No.
