### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [cjcliffe/CubicSDR#893]
Hi, can you add the following topic to this repository?
* https://github.com/topics/sdr

Thanks!

**Comment by Dantali0n** [comment]
Seems like a good addition, you can have quite a collection of topics so perhaps using more than just five could help with find ability. Although in practice I rarely see a difference in exposure between any of my repositories with and without topics.

**Comment by mendel5** [comment]
Hi @vsonnier , can you do this? It takes only a few seconds and helps other people to find this repository.

**Comment by cjcliffe** [comment]
Added; thanks

**Comment by mendel5** [comment]
Thank you!
