### ISSUE TITLE
Code Contributions? - Recommended Development Environment / UI Framework?

### ISSUE THREAD

**Issue by ericmandm** [cjcliffe/CubicSDR#902]
Hello, 
Does this project accept code contributions?  What would b the recommended IDE, plug-ins, etc, for working on the application and UI?
Thanks,

**Comment by vsonnier** [comment]
Sorry for the late response:
- Does this project accept code contributions? : Yes, but it could be slow to be accepted by @cjcliffe or I nowadays for real-life reasons.
- For me, I develop exclusively on Windows : https://github.com/cjcliffe/CubicSDR/wiki/Build-Windows completely describes the whole setup. (almost)
- The Wiki has other MacOS / Linux entries described where you should find information as well, but I don't practice those platforms so I can't give advice of IDE and such for them.

CubicSDR is by itself is a portable application written entirely in Cxx11+ using OpenGL and wxWidgets which exists on all platforms in one form or another, with very little OS-specific pieces of code inside.
