### ISSUE TITLE
Manual Gain controls

### ISSUE THREAD

**Issue by cjcliffe** [cjcliffe/CubicSDR#92]
- [x] Allow enable/disable of the built-in automatic AGC states
- [x] Add a new slider control somewhere that appears for manual gain control mode.
- [x] Allow adjustment of waterfall and spectrum floor/ceiling

**Comment by Gussi** [comment]
Manual gain control would be fantastic. :+1:

**Comment by Toontje** [comment]
+1 although i think the automatic gain works great. Not a high priority for me.

**Comment by cjcliffe** [comment]
Going to bump this to 0.1.5 so that I can get the 0.1.4 build out this week; also might do it in tandem with the gr-osmosdr stuff since the gain controls may be different across devices.

**Comment by dc1rdb** [comment]
With SoapySDR integration progressing so well, maybe this could be changed into "Provide submenu for frontend-specific controls" like:
- Manual gain control for LNA, mixer, IF, as applicable
- AGC on/off
- PreAmp on/off
- Antenna power on/off
- etc.

**Comment by cjcliffe** [comment]
Almost ready here; should have a working commit tomorrow.

**Comment by cjcliffe** [comment]
Manual Gain control now committed to soapysdr-support branch; requires latest SoapySDRPlay and SoapyHackRF drivers for proper gain control.  SoapyRTLSDR should be already good to go.

Just disable AGC from settings menu and the manual gain controls will appear; enjoy :-)
