### ISSUE TITLE
windows10 can't build librtlsdr

### ISSUE THREAD

**Issue by erichuanhuan** [cjcliffe/CubicSDR#923]
Open "Developer Command Prompt for VS 2019" by right-clicking and "Run as Administrator".
ERROR:
C:\MSVCDev\librtlsdr_win64\src\rtlsdr.rc(2): fatal error RC1015: cannot open include file 'afxres.h'. [C:\MSVCDev\librtlsdr_win64\src\rtlsdr_shared.vcxproj]
LINK : fatal error LNK1181: cannot open include file “m.lib” [C:\MSVCDev\librtlsdr_win64\src\rtl_raw2wav.vcxproj]
thanks..

**Comment by vsonnier** [comment]
> C:\MSVCDev\librtlsdr_win64\src\rtlsdr.rc(2): fatal error RC1015: cannot open include file 'afxres.h'.

This suggests that building that lib needs `MFC`, so install them from your VS installer or use a pre-built Dll from Github repo.
