### ISSUE TITLE
Windows 10 issue 21H1 - First time user.

### ISSUE THREAD

**Issue by jphutch60bj** [cjcliffe/CubicSDR#924]
Windows 10 issue 21H1, Lenovo W150 laptop;  
Settings:  CPU (High Enhanced DSP) did not improve issue. 
Upon booting my laptop Lenovo W150 with a SDR dongle plugged in I typically have to open and close Cubic SDR software  start device, stop device close application at least 3 times to get a clean connection.  The audio thumps, motor boats, display is choppy.  Once in a while the application will come up and perform just fine on the first try.  I have Cubic SDR set to high priority.   This behavior  applies to to 2 differnet dongles, Noo Elec NE SDR SMART  XTR   with Enhanced Tuning Range,  and  RTL-SDR RTL2832U R20T2 TXCO Bias T + HF.     Both Dongles have the same issue.  Any Ideas on how to solve this issue .   Happy to drop logs to work out the problems/solution.

**Comment by jphutch60bj** [comment]
Left out Cubic SDR version : V0.2.5

**Comment by vsonnier** [comment]
Your device is too weak, most likely. Otherwise, Cubic works perfectly with Windows 10.

**Comment by jphutch60bj** [comment]
Found 2021/11/13 : Here is the actual issue - USB3.0 port/ports are 
dropping connections, reasons may be 2 fold.  Hardware - electronics 
driving the USB port or a new SDD drive and reinstall windows10.

Found buy using Find  "rlt_test"   find this under RTL tools find and 
download

run rtl_test -d 0 , where 0 is the device number.

**Comment by vsonnier** [comment]
Also remember that the max practical throughtput is 2.4 Msps generally for RTL-SDR. Between 2.4 and 3.2 Msps you will increasingly loose packets and deteriorate signal quality. Use 'rtl_test' to find the max pratical value.
