### ISSUE TITLE
error: ‘modem’ has not been declared

### ISSUE THREAD

**Issue by emanuele-dedonatis** [cjcliffe/CubicSDR#926]
I'm not able to install CubicSDR on Ubuntu 20.04 nor 16.04.

I followed all the steps from the wiki but I'm stuck on building CubicSDR
![image](https://user-images.githubusercontent.com/6308233/140285635-f4927763-ddfd-47af-8954-709a4f60ed4f.png)

**Comment by emanuele-dedonatis** [comment]
Found the problem: [master branch](https://github.com/jgaeddert/liquid-dsp) of **liquid-dsp** doesn't have modem definition anymore!

I built and installed **liquid-dsp** from [v1.3.2 tags](https://github.com/jgaeddert/liquid-dsp/tree/v1.3.2) and it works!

Please update the wiki!

**Comment by nmaster2042** [comment]
I confirm building liquid-dsp from v1.3.2 tag is working.

**Comment by ElwinCabrera** [comment]
I too can confirm that this build works when building liquid-dsp from v1.3.2 tag.

**Comment by vsonnier** [comment]
The problem were with the Digital Modems only, where `modem` in liquid-dsp was renamed to `modemcf` in the current master. I think it is fixed now.
