### ISSUE TITLE
cmake for windows sets link.AdditionalOptions to machine:X86

### ISSUE THREAD

**Issue by Dantali0n** [cjcliffe/CubicSDR#93]
When configuring the project for windows ( 7 ) with cmake gui the link.AdditionalOptions parameter in the cubicsdr.vcxproj file is set to machine:X86 creating an compile error later on when linking the object file.

I have resolved this issue by manually editing the vcxproj file and changing all "machine:X86" strings to "machine:X64"

I'm not sure if this is CubicSDR related or more cmake for windows but maybe this could be added as additional tip for building on windows?

**Comment by cjcliffe** [comment]
Shouldn't be an issue now; 32-bit overrides/hacks have been removed -- just build via CMake as 32 or 64 and it works as expected.
