### ISSUE TITLE
Raspberry GPIO interface for hardware controls?

### ISSUE THREAD

**Issue by iz2ewv** [cjcliffe/CubicSDR#934]
Hello,
I'm playing with a RSP1A and Raspberry Pi 3b+, and I ask if there is a way to provide the tuning control by means of a rotary encoder, and connect it to the GPIO interface of the RPi: the control should be active all the time. Other two controls that I should like to replicate in hardware form (rotary encoders as well) are: the bandwidth and the modes selection.
Tnx es 73 de
Alberto, IZ2EWV

**Comment by vsonnier** [comment]
CubicSDR interacts with devices through `Hamlib` for integration HAM setps. If something is possible, it is through this library. See  https://github.com/Hamlib/Hamlib .
