### ISSUE TITLE
Hi, does the official website still running?

### ISSUE THREAD

**Issue by TurnOffNOD** [cjcliffe/CubicSDR#964]
Hi, when I visited the official website cubicsdr.com today, the broswer says "The connection has timed out".
I am wondering is this due to my network issue, or the website is down?

**Comment by SDRplay** [comment]
Working here at the moment - might have been an ISP or hosting issue?

**Comment by TurnOffNOD** [comment]
> Working here at the moment - might have been an ISP or hosting issue?

Oh, now it is working. It is a temporary problem.
By the way, there is no latest release version on the website. Will the latest version of windows binary and other thing be put on the website?

**Comment by cjcliffe** [comment]
Will post an update on the site when all the 0.2.7 binaries are available.

There's technically an updated windows install at https://github.com/cjcliffe/CubicSDR-WinBuild/releases but it has some liquid-dsp build related performance issues.   

That repository will hopefully contain all the automated builds in the future.
