### ISSUE TITLE
Recording IQ signals in stereo

### ISSUE THREAD

**Issue by VK1IAN** [cjcliffe/CubicSDR#965]
I'm trying to decode a FSK signal with some python scripts I found, however they require IQ signals in the .wav file (I=left and Q=right).
Is this the way CubicSDR records FMS received signals? If not, is there a way I can do this?
Apparently SDR# can do this but I'm on a Linux box.

**Comment by vsonnier** [comment]
You'll need to use the `Recording` function, with `I/Q` modulation. Likely https://github.com/cjcliffe/CubicSDR/issues/872 has a more comple answer.
