### ISSUE TITLE
dragging the frequency causes the frequency to jump in 1 MHz increments

### ISSUE THREAD

**Issue by dborup63** [cjcliffe/CubicSDR#967]
Hi, I am having a problem with cubicsdr.  Originally, I could drag the frequency in very fine increments.  Now dragging the frequency jump in 1 MHz increments.  Does anyone know what causes this?

Thank you,
Dave

**Comment by Dantali0n** [comment]
Duplicate #966, please don't open multiple tickets for the same issue
@vsonnier can you close this?

**Comment by vsonnier** [comment]
@Dantali0n  That I can do :)
