### ISSUE TITLE
How to start recording

### ISSUE THREAD

**Issue by rlatoska** [cjcliffe/CubicSDR#968]
Hello,

I've installed CubicSDR on Ubuntu 20.04 and use it with an RTL-SDR.COM V3. There is a menu for Recording. I can set the path for the files but where is the button for starting an ending the recording process. The manual does not mention this process either. 

How to start and end recording in CubicSDR?

**Comment by dmaltsiniotis** [comment]
Hi @rlatoska ,

Select the de-modulator and press the R key to start and stop recording on that particular de-modulator. There's also a handy tool tip (on Windows at least) that will give hints to some of the keyboard shortcuts:

![image](https://user-images.githubusercontent.com/106233/191298413-1018faf7-9d32-495c-ac00-5a076a09c924.png)
