### ISSUE TITLE
modemcf not declared

### ISSUE THREAD

**Issue by emrecio** [cjcliffe/CubicSDR#970]
Latest version cloned from git seems to have references to modemcf that are missing all over the code base. Not sure where to start debugging? Is it a missing library?

**Comment by emrecio** [comment]
``In file included from /home/erecio/elDrive/RTL/CubicSDR/src/demod/DemodulatorInstance.h:11:0,
from /home/erecio/elDrive/RTL/CubicSDR/src/BookmarkMgr.h:12,
from /home/erecio/elDrive/RTL/CubicSDR/src/forms/Bookmark/BookmarkView.h:10,
from /home/erecio/elDrive/RTL/CubicSDR/src/forms/Bookmark/BookmarkView.cpp:9:
/home/erecio/elDrive/RTL/CubicSDR/src/modules/modem/ModemDigital.h:45:53: error: ‘modemcf’ has not been declared
virtual void digitalStart(ModemKitDigital *kit, modemcf mod, ModemIQData *input);
^~~~~~~
/home/erecio/elDrive/RTL/CubicSDR/src/modules/modem/ModemDigital.h:46:54: error: ‘modemcf’ has not been declared
virtual void digitalFinish(ModemKitDigital *kit, modemcf mod);
^~~~~~~
/home/erecio/elDrive/RTL/CubicSDR/src/modules/modem/ModemDigital.h:51:40: error: ‘modemcf’ has not been declared
virtual void updateDemodulatorLock(modemcf mod, float sensitivity);
^~~~~~~
make[2]: *** [CMakeFiles/CubicSDR.dir/build.make:1084: CMakeFiles/CubicSDR.dir/src/forms/Bookmark/BookmarkView.cpp.o] Error 1``

**Comment by emrecio** [comment]
![image](https://user-images.githubusercontent.com/3452752/194729014-9eed3861-6c62-4d74-9dff-213ce2d23a3c.png)

**Comment by emrecio** [comment]
Bump?

**Comment by emrecio** [comment]
Downloaded and compiled
git clone git://github.com/jgaeddert/liquid-dsp.git
./bootstrap.sh
./configure
make
sudo make install

Worked.... IDK why I missed this before.

**Comment by dmaltsiniotis** [comment]
Glad you figured it out!
