### ISSUE TITLE
Headphone output generates errors when there are two HDMI monitors

### ISSUE THREAD

**Issue by w0dz** [cjcliffe/CubicSDR#974]
I am using the SDRPlay image, v0.7, which includes CubicSDR, on a Raspberry Pi 4B. I have found that it works fine to the headphone jack when I don't plug in the second HDMI monitor. Not sure which of the numerous ways to select the headphones actually worked - tried raspi-config, alsamixer, CubicSDR itself, and of course added dtparam=audio=on to the config.txt file. But nothing makes the audio work when I have both HDMI1 and 2 (0 and 1 on the RPi board) enabled. The output window shows scads of this error:

DemodulatorThread::run() cannot push ati into audioOutputQueue, is full !

And if I select HDMI1 or 2 from CubicSDR, I get an IO error. I can select the headphones as long as only one HDMI display is connected.

Any thoughts? I must have both monitors in use as well as headphone jack audio.

**Comment by w0dz** [comment]
Follow-up - It's not just Cubic SDR. A program I wrote that produces audio is also not working when the 2nd HDMI port is there, Oddly, it doesn't come out hte second HDMI monitor speakers either. And the audio to the headphone jack is much lower volume when I do remove that second HDMI cable. This worked fine on SDRPlay's v0.6 image. What changed?

**Comment by dmaltsiniotis** [comment]
Hi @w0dz, it sounds like this might be an issue with the SDR Play image, rather than with CubicSDR. You may want to reach out to the maintainers of that image or distribution for additional help.

I have noticed on rare occasions (on Windows) that when audio devices change dynamically (like when HDMI monitors are turned off/on) that the audio source dropdown box in CubicSDR is off by one. Meaning: it's the selection above/below the actual device you want to send audio to. I don't think that is what is going on here based on your description though, it sounds like something related to the SDR play image or Raspberry Pi itself.

**Comment by w0dz** [comment]
They pawned me off on you, saying they don't know anything about CubicSDR and don't offer support. And apparently they also don't support the Linux inage that they offer for download. Version v0.6 works, but v0.7 does not. They said it would be better to go get my own Debian installation and build everything from scratch. Not gonna happen. So any advice is appreciated.

**Comment by w0dz** [comment]
Just observed that the alsamixer has a volume setting that must be max volume. When I finally realized I could tweak that, I got normal volume out and the volume slider worked as expected. But that did not resolve the HDMI issue. I have an earlier image, v0.6, in which I was able to run both monitors and the headphone jack, so I know there's a setting somewhere that will fix it. But I can't remember what I did to get that working, and I have Googled it till I'm blue in the face and can't find anyone else who's tried it and solved it.

**Comment by w0dz** [comment]
Just found a link on RPi forums. Apparently a known problem with a workaround,

https://forums.raspberrypi.com/viewtopic.php?t=282166

**Comment by w0dz** [comment]
Just tried this workaround, and it works!

**Comment by dmaltsiniotis** [comment]
Nice find, glad it worked out.

**Comment by vsonnier** [comment]
Closing, since it is not a CubicSDR issue.
