### ISSUE TITLE
Display only refreshes on mouse movement in El Capitan

### ISSUE THREAD

**Issue by mikelagasse** [cjcliffe/CubicSDR#98]
In OS X El Capitan DP2, The entire contents of the display in CubicSDR do not refresh unless the mouse is currently moving.

**Comment by cjcliffe** [comment]
Wow that's an oddball -- The entire display refreshes on mouse move (like all views) or just the view the mouse is currently over?

**Comment by mikelagasse** [comment]
I'm not sure the distinction, but nothing within the CubicSDR window (ex: graphs, waterfall) refreshes unless the mouse is actively moving. Audio does continue to play back. As long as you constantly wiggle the mouse everything updates smoothly.

**Comment by cjcliffe** [comment]
The waterfall, scope, etc are all separate wx panels at the moment so it's strange -- I'm guessing there's some missed refresh event at the AppFrame that's now interpreted as a non-update.

I will investigate, thanks.

**Comment by cjcliffe** [comment]
@mikelagasse if you (or someone) is able to test the latest commits to master to see if this is resolved in El Capitan I'd appreciate it.

thanks!

**Comment by alienshop** [comment]
Hi, I can confirm that its now working correctly in El Capitan with release 0.1.4. Thanks!

**Comment by cjcliffe** [comment]
perfect, cheers!
